project:
  type: website
  preview:
    port: 4200
  resources:
    - /publications

website:
  title: "FraLab"
  favicon: "img/logo.png"
  site-url: "https:/tester"
  description: "Website for the Carbon Cycle Lab at Caltech."
  twitter-card: true
  open-graph: true
  google-analytics: "G-V5MKFZWK6P"
  page-footer:
    left: |
      [![](/img/Caltech_Logo.png){fig-alt="Caltech" width=65px}](https://www.caltech.edu/)
    #center:
    #  - text: "About"
    #    href: about.qmd
    #  - text: "FAQ"
    #    href: docs/faq/index.qmd
    #  - text: "License"
    #    href: license.qmd
    #  - text: "Trademark"
    #    href: trademark.qmd
    right:
      - text: "{{< ai google-scholar >}} Google Scholar"
        href: https://scholar.google.com/citations?user=7XYDtdYAAAAJ&hl=en 
      - icon: twitter
        href: https://twitter.com/chr_fronge
        aria-label: PI Twitter
      - icon: github
        href: https://github.com/RemoteSensingTools/
        aria-label: Quarto GitHub
  navbar:
    logo: "/img/FraLabLogo.png"
    left:
      - href: index.qmd
        text: Home
      - href: people.qmd
        text: People
      - href: publications.qmd
        text: Publications
      - href: LabGuide.qmd
        text: Lab Guide
      - href: join.qmd
        text: Join the Group
      - href: blogs.qmd
        text: Blog
    right:
      - href: https://scholar.google.com/citations?user=7XYDtdYAAAAJ&hl=en
        text: "{{< ai google-scholar >}}"
        aria-label: Google Scholar 
      - icon: github
        href: https://github.com/cfranken
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/chr_fronge
        aria-label: Twitter


format:
  html:
    page-layout: full
    theme:
      light: [flatly, custom.scss]
      dark: [darkly, custom.scss]
    toc: true
    css: custom.css
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px

editor: visual
