---
title: 'Data Drought in the Humid Tropics: How to Overcome the Cloud Barrier in Greenhouse Gas Remote Sensing'
author: 'Frankenberg, Christian and Bar-On, Yinon Moise and Yin, Yi and Wenberg, Paul O. and Jacob, Daniel J. and Michalak, Anna M'
type: 'preprint'
year: 2024
publication: ''
doi: '10.22541/essoar.170923255.57545328/v1'
materials: ''
supplement: ''
orcid_type: 'preprint'
toc: false
---

## Abstract

Diagnosing land-atmosphere fluxes of carbon-dioxide (CO2) and
methane (CH4), is essential for evaluating carbon-climate
feedbacks. Greenhouse gas satellite missions aim to fill data gaps in
regions like the humid tropics, but obtain very few valid measurements
due to cloud contamination. We examined data yields from the Orbiting
Carbon Observatory alongside Sentinel 2 cloud statistics. We find that
the main contribution to low data yields are frequent shallow cumulus
clouds. In the Amazon, the success rate in obtaining valid measurements
vary from 0.1\% to 1.0\%. By far the
lowest yields occur in the wet season, consistent with Sentinel 2 cloud
patterns. We find that increasing the spatial resolution of observations
to \sim200\,m would increase yields by
2-3 orders of magnitude, and allow regular measurements in the wet
season. Thus, the key effective tropical greenhouse gas observations
lies in regularly acquiring high-spatial resolution data, rather than
more frequent low-resolution measurements.