---
title: 'Thermal fertilization of the high-latitude northern forests'
author: 'Liu, Junjie and Wennberg, Paul O. and Parazoo, Nicholas Cody and YIN, Yi and Frankenberg, Christian'
type: 'preprint'
year: 2020
publication: ''
doi: '10.1002/essoar.10503282.1'
materials: ''
supplement: ''
orcid_type: 'preprint'
toc: false
---

## Abstract

Since the 1960s, carbon cycling in the high-latitude northern forest
(HLNF) has experienced dramatic changes: most of the forest is greening
and net carbon uptake from the atmosphere has increased. During the same
time period, the COseasonal cycle amplitude (SCA) has almost doubled.
Disentangling complex processes that drive these changes has been
challenging. In this study, we substitute spatial sensitivity to
temperature for time to quantify the impact of temperature increase on
Gross Primary Production (GPP), total ecosystem respiration (TER), the
fraction of Photosynthetic Active Radiation (fPAR), and the resulted
contribution of these changes in amplifying the COSCA over the HLNF
since 1960s. We use the spatial heterogeneity of GPP inferred from
solar-induced chlorophyll Fluorescence in combination with net ecosystem
exchange (NEE) inferred from column COobservations made between 2015 and
2017 from NASA’s Orbiting Carbon Observatory -2. We find that three
quarters of the spatial variations in GPP and in the fPAR absorbed by
the HLNF can be explained by the spatial variation in the growing season
mean temperature (GSMT). The long term hindcast captures both the
magnitude and spatial variability of the trends in observed fPAR. We
estimate that between 1960 and 2010, the increase in GSMT enhanced both
GPP and the SCA of NEE by ~20%. The calculated
enhancement of NEE due to increase in GSMT contributes 56–72% of the
trend in the CO SCA at high latitudes, much larger than simulations by
most biogeochemical models.