---
title: 'Investigation of Urban Vegetative Fluxes of Carbon Dioxide over the Greater Toronto and Hamilton Area'
author: 'Madsen, Sabrina and Wunch, Debra and Arain, Muhammad Altaf and Frankenberg, Christian and Koehler, Philipp and Rogers, Cheryl and Staebler, Ralf and Vogel, Felix and Wu, Dien'
type: 'preprint'
year: 2022
publication: ''
doi: '10.1002/essoar.10510330.1'
materials: ''
supplement: ''
orcid_type: 'preprint'
toc: false
---

## Abstract

Terrestrial vegetation is known to be an important sink for carbon
dioxide (CO<sub>2</sub>). However, fluxes to and from vegetation are often not
accounted for when studying anthropogenic CO<sub>2</sub> emissions in urban areas.
This project seeks to quantify urban biogenic fluxes in the Greater
Toronto and Hamilton Area located in Southern Ontario, Canada. Toronto
is Canada’s most populated city but also has a large amount of
green-space, covering approximately 13 % of the city. In addition,
vegetation is not evenly distributed throughout the region. We therefore
expect biogenic fluxes to play an important role in the spatial patterns
of CO<sub>2</sub> concentrations and the overall local carbon budget. In order to
fully understand biogenic fluxes they can be partitioned into the amount
of CO<sub>2</sub> sequestered via photosynthesis, gross primary productivity (GPP),
and the amount respired by vegetation, ecosystem respiration (Reco).
Solar induced chlorophyll fluorescence (SIF) measured from space has
been shown to be a valuable proxy for photosynthesis and thus can be
used to estimate GPP. Vegetation models, including the Urban Vegetation
Photosynthesis and Respiration Model (UrbanVPRM) and the SIF for
Modelling Urban biogenic Fluxes (SMUrF) model, have also been used to
estimate both GPP and Reco In this study we compare modelled and
SIF-derived biogenic CO<sub>2</sub> fluxes at a 500 m by 500 m resolution, to
ground-based flux tower measurements in Southern Ontario to determine
how well these methods estimate biogenic CO<sub>2</sub> fluxes. This study works
towards determining the importance of biogenic fluxes in the Greater
Toronto and Hamilton Area. Furthermore, the results of this work may
inform policy makers and city planners on how urban vegetation affects
CO<sub>2</sub> concentrations and patterns within cities.