---
title: 'Observed impacts of COVID-19 on urban CO<sub>2</sub> emissions'
author: 'Turner, Alexander and Kim, Jinsol and Fitzmaurice, Helen and Newman, Catherine and Worthington, Kevin and Chan, Katherine and Wooldridge, Paul and Köhler, Philipp and Frankenberg, Christian and Cohen, Ronald C'
type: 'preprint'
year: 2020
publication: ''
doi: '10.1002/essoar.10504138.1'
materials: ''
supplement: ''
orcid_type: 'preprint'
toc: false
---

## Abstract

Governments restricted mobility and effectively shuttered much of the
global economy in response to the COVID-19 pandemic. Six San Francisco
Bay Area counties were the first region in the United States to issue a
“shelter-in-place” order asking non-essential workers to stay home.
Here we use CO<sub>2</sub> observations from 35 Berkeley Environment, Air-quality
and CO<sub>2</sub> Network (BEACO<sub>2</sub>N) nodes and an atmospheric transport model to
quantify changes in urban CO<sub>2</sub> emissions due to the order. We infer
hourly emissions at 900-m spatial resolution for 6 weeks before and 6
weeks during the order. We observe a 28% decrease in anthropogenic CO<sub>2</sub>
emissions during the order and show this decrease is primarily due to
changes in traffic (-44%) with pronounced changes to daily and weekly
cycles; non-traffic emissions show small changes (-8%). These findings
provide a glimpse into a future with reduced CO<sub>2</sub> emissions through
electrification of vehicles. (submitted to GRL: 2020-07-24 16:49:19)