---
title: 'Monitoring the impact of forest changes on carbon uptake with solar-induced fluorescence measurements from GOME-2A and TROPOMI for an Australian and Chinese case study'
author: 'Anema, Juliëtte C. S. and Boersma, Klaas Folkert and Stammes, Piet and Koren, Gerbrand and Woodgate, William and Köhler, Philipp and Frankenberg, Christian and Stol, Jacqui'
type: 'journal-article'
year: 2024
publication: 'Biogeosciences'
doi: '10.5194/bg-21-2297-2024'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. Reliable and robust monitoring tools are crucial to assess the effectiveness of land mitigation techniques (LMTs) in enhancing carbon uptake, enabling informed decision making by policymakers. This study, addressing one of the scientific goals of the EU Horizon 2020 Land Use Based Mitigation for Resilient Climate Pathways (LANDMARC) project, examines the feasibility of using satellite solar-induced fluorescence (SIF) in combination with other satellite data as a monitoring proxy to evaluate the effects of LMTs on carbon uptake. Two distinct cases are explored: (1) instantaneous vegetation destruction caused by a 2019 eucalyptus wildfire in southeast Australia and (2) gradual forest gain resulting from reforestation efforts in northern China in 2007–2012. The cases are monitored using SIF from the TROPOspheric Monitoring Instrument (TROPOMI) and Global Ozone Monitoring Experiment-2A (GOME-2A), respectively. Comparing the temporal variability in SIF across the affected areas and nearby reference areas reveals that vegetation dynamics changed as a consequence of the land-use changes in both cases. Specifically, in the Australia case, TROPOMI demonstrated an immediate reduction in the SIF signal of 0.6 mW m−2 sr−1 nm−1 (−72 %) over the eucalypt forest right after the fire. Exploiting the strong correspondence between TROPOMI SIF and gross primary productivity (GPP) at the nearby representative eddy covariance Tumbarumba site and through the FluxSat product, we estimate that the Australian fire led to a loss in GPP of 130–200 GgC in the first 8 months after the fire. Over the northern Chinese provinces of Gansu, Shaanxi, Sichuan, Chongqing, and Shanxi, we report an increase in GOME-2A summertime SIF of 0.1–0.2 mW m−2 sr−1 nm−1, coinciding with reforestation efforts between 2007 and 2012. This increase in the SIF signal is likely driven by a combination of increasingly favourable natural conditions and by the reforestation effort itself. A multivariate model that takes into account growth factors such as water availability and maximum temperature as well as satellite-derived forest-cover data explains the observed variability in GOME-2A SIF in the Chinese case reasonably well (R<sub>2</sub>=0.72). The model suggests that increases in both forest cover and soil moisture have led, in step, to the observed increase in vegetation activity over northern China. In that region, for every 100 km2 of additional forest cover, SIF increases by 0.1 mW m−2 sr−1 nm−1 between 2007 and 2012. Our study highlights that the use of satellite-based SIF, together with supporting in situ, modelled, and satellite data, allows us to monitor the impact of LMT implementation on regional carbon uptake as long as the scale of the LMT is of sufficient spatial extent.