---
title: 'Differences Between OCO‐2 and GOME‐2 SIF Products From a Model‐Data Fusion Perspective'
author: 'Bacour, C. and Maignan, F. and Peylin, P. and MacBean, N. and Bastrikov, V. and Joiner, J. and Köhler, P. and Guanter, L. and Frankenberg, C.'
type: 'journal-article'
year: 2019
publication: 'Journal of Geophysical Research: Biogeosciences'
doi: '10.1029/2018jg004938'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

AbstractSpace‐borne retrievals of solar‐induced chlorophyll fluorescence (SIF) over land surfaces have recently become a resource for studying and quantifying the broad scale dynamics of gross carbon uptake (gross primary productivity—GPP) across ecosystems. To prepare for the assimilation of SIF data in terrestrial biosphere models, we examine how differences between SIF products (due to differences in acquisition characteristics and processing chain) may affect the optimization of model parameters and the resultant GPP estimate. We compare recent daily mean SIF products (one from the Orbiting Carbon Observatory‐2 [OCO‐2] and two from the Global Ozone Monitoring Experiment–2 [GOME‐2], GlobFluo [GF] and NASA‐v28 [N<sub>28</sub>], missions), averaged at 0.5° × 0.5° spatial resolution and 16‐day temporal resolution, at the biome level. Phase differences between these products are relatively small. A first‐order correction of the difference in spectral sampling between the two instruments shows that OCO‐2 and N<sub>28</sub> are consistent in terms of magnitude and amplitude, while GF is twice as large as the others. Using a bias‐blind toy data assimilation framework, we analyze how biases between SIF products, and between model and products, can be partially alleviated by optimizing the slope and intercept parameters of a linear GPP‐SIF operator. As observation biases can transfer to biases in other optimized process‐based parameters and to modeled carbon fluxes— thereby resulting in unidentified inaccurate parameter values—we argue that potential SIF biases should be treated cautiously in real‐world experiments in order to achieve realistic and reliable future simulations.