---
title: 'Satellite chartography of atmospheric methane from SCIAMACHY on board ENVISAT: 2. Evaluation based on inverse model simulations'
author: 'Bergamaschi, P. and Frankenberg, C. and Meirink, J. F. and Krol, M. and Dentener, F. and Wagner, T. and Platt, U. and Kaplan, J. O. and Körner, S. and Heimann, M. and Dlugokencky, E. J. and Goede, A.'
type: 'journal-article'
year: 2007
publication: 'Journal of Geophysical Research: Atmospheres'
doi: '10.1029/2006jd007268'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

We extend the analysis of a global CH<sub>4</sub> data set retrieved from SCIAMACHY (Frankenberg et al., 2006) by making a detailed comparison with inverse TM<sub>5</sub> model simulations for 2003 that are optimized versus high accuracy CH<sub>4</sub> surface measurements from the NOAA ESRL network. The comparison of column averaged mixing ratios over remote continental and oceanic regions shows that major features of the atmospheric CH<sub>4</sub> distribution are consistent between SCIAMACHY observations and model simulations. However, the analysis suggests that SCIAMACHY CH<sub>4</sub> retrievals may have some bias that depends on latitude and season (up to ∼30 ppb). Large enhancements of column averaged CH<sub>4</sub> mixing ratios (∼50–100 ppb) are observed and modeled over India, Southeast Asia, and the tropical regions of South America, and Africa. We present a detailed comparison of observed spatial patterns and their seasonal evolution with TM<sub>5</sub> 1° × 1° zoom simulations over these regions. Application of a new wetland inventory leads to a significant improvement in the agreement between SCIAMACHY retrievals and model simulations over the Amazon basin during the first half of the year. Furthermore, we present an initial coupled inversion that simultaneously uses the surface and satellite observations and that allows the inverse system to compensate for the potential systematic bias. The results suggest significantly greater tropical emissions compared to either the a priori estimates or the inversion based on the surface measurements only. Emissions from rice paddies in India and Southeast Asia are relatively well constrained by the SCIAMACHY data and are slightly reduced by the inversion.