---
title: 'Large-Scale Controls of Methanogenesis Inferred from Methane and Gravity Spaceborne Data'
author: 'Bloom, A. Anthony and Palmer, Paul I. and Fraser, Annemarie and Reay, David S. and Frankenberg, Christian'
type: 'journal-article'
year: 2010
publication: 'Science'
doi: '10.1126/science.1175176'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Measuring Methanogenesis

After carbon dioxide, methane is the second most important greenhouse gas, and an important species in terms of its role in atmospheric chemistry. The sources and sinks of methane, particularly the natural ones, are too poorly quantified, however, even to explain why the decades-long, steady increase of its concentration in the atmosphere was interrupted between 1999 and 2006.

Bloom
et al.

(p.
322
) use a combination of satellite data, which indicate water table depth and surface temperature, and atmospheric methane concentrations to determine the location and strength of methane emissions from wetlands, the largest natural global source. The constraints placed on these sources should help to improve predictions of how climate change will affect wet-land emissions of methane.