---
title: 'Remote‐sensing constraints on South America fire traits by Bayesian fusion of atmospheric and surface data'
author: 'Bloom, A. Anthony and Worden, John and Jiang, Zhe and Worden, Helen and Kurosu, Thomas and Frankenberg, Christian and Schimel, David'
type: 'journal-article'
year: 2015
publication: 'Geophysical Research Letters'
doi: '10.1002/2014gl062584'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

AbstractSatellite observations reveal substantial burning during the 2007 and 2010 tropical South America fire season, with both years exhibiting similar total burned area. However, 2010 CO fire emissions, based on satellite CO concentration measurements, were substantially lower (−28%), despite the once‐in‐a‐century drought in 2010. We use Bayesian inference with satellite measurements of CH<sub>4</sub> and CO concentrations and burned area to quantify shifts in combustion characteristics in 2010 relative to 2007. We find an 88% probability in reduced combusted biomass density associated with the 2010 fires and an 82% probability of lower fire carbon losses in 2010 relative to 2007. Higher combustion efficiency was a smaller contributing factor to the reduced 2010 CO emissions. The reduction in combusted biomass density is consistent with a reduction (4–6%) in Global Ozone Monitoring Experiment 2 solar‐induced fluorescence (a proxy for gross primary production) during the preceding months and a potential reduction in biomass (≤8.3%) due to repeat fires.