---
title: 'Detection and quantification of CH
<sub>4</sub>
plumes using the WFM-DOAS retrieval on AVIRIS-NG hyperspectral data'
author: 'Borchardt, Jakob and Gerilowski, Konstantin and Krautwurst, Sven and Bovensmann, Heinrich and Thorpe, Andrew K. and Thompson, David R. and Frankenberg, Christian and Miller, Charles E. and Duren, Riley M. and Burrows, John Philip'
type: 'journal-article'
year: 2021
publication: 'Atmospheric Measurement Techniques'
doi: '10.5194/amt-14-1267-2021'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. Methane is the second most important anthropogenic greenhouse gas in the Earth's atmosphere. To effectively reduce these emissions,
a good knowledge of source locations and strengths is required.
Airborne remote sensing instruments
such as the Airborne Visible InfraRed Imaging Spectrometer – Next Generation (AVIRIS-NG)
with meter-scale imaging capabilities are able to yield
information about the locations and magnitudes of methane sources.
In this study, we successfully applied the weighting function modified differential optical absorption spectroscopy (WFM-DOAS) algorithm to AVIRIS-NG data measured in Canada and
the Four Corners region. The WFM-DOAS retrieval is conceptually located between the statistical matched filter (MF) and the optimal-estimation-based iterative maximum a posteriori DOAS (IMAP-DOAS)
retrieval algorithm, both of which were already applied successfully to AVIRIS-NG data.
The WFM-DOAS algorithm is based on a first order Taylor series approximation of the Lambert–Beer law using only one precalculated radiative transfer calculation per scene.
This yields the fast quantitative processing of large data sets.
We detected several methane plumes in the AVIRIS-NG images recorded during the Arctic-Boreal Vulnerability Experiment (ABoVE) Airborne Campaign and successfully retrieved
a coal mine ventilation shaft plume observed during the Four Corners measurement campaign.
The comparison between IMAP-DOAS, MF, and WFM-DOAS showed good agreement for the coal mine ventilation shaft plume.
An additional comparison between MF and WFM-DOAS for a subset of plumes showed good agreement for one plume and some differences for the others.
For five plumes,
the emissions were estimated using a simple cross-sectional flux method.
The retrieved fluxes originated from well pads, cold vents, and a coal mine ventilation shaft and
ranged between (155 ± 71) kg (CH<sub>4</sub>) h−1
and (1220 ± 450) kg (CH<sub>4</sub>) h−1.
The wind velocity was a significant source of uncertainty
in all plumes, followed by the single pixel retrieval noise and the uncertainty due to atmospheric variability.
The noise
of the retrieved CH<sub>4</sub> imagery over bright surfaces (>1 µW cm−2 nm−1 sr−1 at 2140 nm)
was typically ±2.3 % of the background total column of CH<sub>4</sub> when fitting
strong absorption lines around 2300 nm but could
reach over ±5 % for darker surfaces (< 0.3 µW cm−2 nm−1 sr−1 at 2140 nm). Additionally, a worst case
large-scale bias due to the assumptions made in the WFM-DOAS retrieval was estimated to be
±5.4 %. Radiance and fit quality filters were implemented to exclude
the most uncertain results from further analysis mostly due to either dark surfaces or
surfaces where the surface spectral reflection structures are similar to CH<sub>4</sub> absorption features at
the spectral resolution of the AVIRIS-NG instrument.