---
title: 'The Importance of Hyperspectral Soil Albedo Information for Improving Earth System Model Projections'
author: 'Braghiere, R. K. and Wang, Y. and Gagné‐Landmann, A. and Brodrick, P. G. and Bloom, A. A. and Norton, A. J. and Ma, S. and Levine, P. and Longo, M. and Deck, K. and Gentine, P. and Worden, J. R. and Frankenberg, C. and Schneider, T.'
type: 'journal-article'
year: 2023
publication: 'AGU Advances'
doi: '10.1029/2023av000910'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

AbstractEarth system models (ESMs) typically simplify the representation of land surface spectral albedo to two values, which correspond to the photosynthetically active radiation (PAR, 400–700 nm) and the near infrared (NIR, 700–2,500 nm) spectral bands. However, the availability of hyperspectral observations now allows for a more direct retrieval of ecological parameters and reduction of uncertainty in surface reflectance. To investigate sensitivity and quantify biases of incorporating hyperspectral albedo information into ESMs, we examine how shortwave soil albedo affects surface radiative forcing and simulations of the carbon and water cycles. Results reveal that the use of two broadband values to represent soil albedo can introduce systematic radiative‐forcing differences compared to a hyperspectral representation. Specifically, we estimate soil albedo biases of ±0.2 over desert areas, which can result in spectrally integrated radiative forcing divergences of up to 30 W m−2, primarily due to discrepancies in the blue (404–504 nm) and far‐red (702–747 nm) regions. Furthermore, coupled land‐atmosphere simulations indicate a significant difference in net solar flux at the top of the atmosphere (>3.3 W m−2), which can impact global energy fluxes, rainfall, temperature, and photosynthesis. Finally, simulations show that considering the hyperspectrally resolved soil reflectance leads to increased maximum daily temperatures under current and future CO<sub>2</sub> concentrations.