---
title: 'Tipping point in North American Arctic-Boreal carbon sink persists in new generation Earth system models despite reduced uncertainty'
author: 'Braghiere, Renato K and Fisher, Joshua B and Miner, Kimberley R and Miller, Charles E and Worden, John R and Schimel, David S and Frankenberg, Christian'
type: 'journal-article'
year: 2023
publication: 'Environmental Research Letters'
doi: '10.1088/1748-9326/acb226'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract
Estimating the impacts of climate change on the global carbon cycle relies on projections from Earth system models (ESMs). While ESMs currently project large warming in the high northern latitudes, the magnitude and sign of the future carbon balance of Arctic-Boreal ecosystems are highly uncertain. The new generation of increased complexity ESMs in the Intergovernmental Panel on Climate Change Sixth Assessment Report (IPCC AR<sub>6</sub>) is intended to improve future climate projections. Here, we benchmark the Coupled Model Intercomparison Project (CMIP) 5 and 6 (8 CMIP<sub>5</sub> members and 12 CMIP<sub>6</sub> members) with the International Land Model Benchmarking (ILAMB) tool over the region of NASA’s Arctic-Boreal vulnerability experiment (ABoVE) in North America. We show that the projected average net biome production (NBP) in 2100 from CMIP<sub>6</sub> is higher than that from CMIP<sub>5</sub> in the ABoVE domain, despite the model spread being slightly narrower. Overall, CMIP<sub>6</sub> shows better agreement with contemporary observed carbon cycle variables (photosynthesis, respiration, biomass) than CMIP<sub>5</sub>, except for soil carbon and turnover time. Although both CMIP ensemble members project the ABoVE domain will remain a carbon sink by the end of the 21st century, the sink strength in CMIP<sub>6</sub> increases with CO<sub>2</sub> emissions. CMIP<sub>5</sub> and CMIP<sub>6</sub> ensembles indicate a tipping point defined here as a negative inflection point in the NBP curve by 2050–2080 independently of the shared socioeconomic pathway (SSP) for CMIP<sub>6</sub> or representative concentration pathway (RCP) for CMIP<sub>5</sub>. The model ensembles therefore suggest that, if the carbon sink strength keeps declining throughout the 21st century, the Arctic-Boreal ecosystems in North America may become a carbon source over the next century.