---
title: 'Satellite-derived methane hotspot emission estimates using a fast data-driven method'
author: 'Buchwitz, Michael and Schneising, Oliver and Reuter, Maximilian and Heymann, Jens and Krautwurst, Sven and Bovensmann, Heinrich and Burrows, John P. and Boesch, Hartmut and Parker, Robert J. and Somkuti, Peter and Detmers, Rob G. and Hasekamp, Otto P. and Aben, Ilse and Butz, André and Frankenberg, Christian and Turner, Alexander J.'
type: 'journal-article'
year: 2017
publication: 'Atmospheric Chemistry and Physics'
doi: '10.5194/acp-17-5751-2017'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. Methane is an important atmospheric greenhouse gas and an adequate understanding of its emission sources is needed for climate change assessments, predictions, and the development and verification of emission mitigation strategies. Satellite retrievals of near-surface-sensitive column-averaged dry-air mole fractions of atmospheric methane, i.e. XCH<sub>4</sub>, can be used to quantify methane emissions. Maps of time-averaged satellite-derived XCH<sub>4</sub> show regionally elevated methane over several methane source regions. In order to obtain methane emissions of these source regions we use a simple and fast data-driven method to estimate annual methane emissions and corresponding 1σ uncertainties directly from maps of annually averaged satellite XCH<sub>4</sub>. From theoretical considerations we expect that our method tends to underestimate emissions. When applying our method to high-resolution atmospheric methane simulations, we typically find agreement within the uncertainty range of our method (often 100 %) but also find that our method tends to underestimate emissions by typically about 40 %. To what extent these findings are model dependent needs to be assessed. We apply our method to an ensemble of satellite XCH<sub>4</sub> data products consisting of two products from SCIAMACHY/ENVISAT and two products from TANSO-FTS/GOSAT covering the time period 2003–2014. We obtain annual emissions of four source areas: Four Corners in the south-western USA, the southern part of Central Valley, California, Azerbaijan, and Turkmenistan. We find that our estimated emissions are in good agreement with independently derived estimates for Four Corners and Azerbaijan. For the Central Valley and Turkmenistan our estimated annual emissions are higher compared to the EDGAR v4.2 anthropogenic emission inventory. For Turkmenistan we find on average about 50 % higher emissions with our annual emission uncertainty estimates overlapping with the EDGAR emissions. For the region around Bakersfield in the Central Valley we find a factor of 5–8 higher emissions compared to EDGAR, albeit with large uncertainty. Major methane emission sources in this region are oil/gas and livestock. Our findings corroborate recently published studies based on aircraft and satellite measurements and new bottom-up estimates reporting significantly underestimated methane emissions of oil/gas and/or livestock in this area in EDGAR.