---
title: 'The greenhouse gas project of ESA’s climate change initiative (GHG-CCI): overview, achievements and future plans'
author: 'Buchwitz, M. and Reuter, M. and Schneising, O. and Boesch, H. and Aben, I. and Alexe, M. and Armante, R. and Bergamaschi, P. and Bovensmann, H. and Brunner, D. and Buchmann, B. and Burrows, J. P. and Butz, A. and Chevallier, F. and Chédin, A. and Crevoisier, C. D. and Gonzi, S. and De Mazière, M. and De Wachter, E. and Detmers, R. and Dils, B. and Frankenberg, C. and Hahne, P. and Hasekamp, O. P. and Hewson, W. and Heymann, J. and Houweling, S. and Hilker, M. and Kaminski, T. and Kuhlmann, G. and Laeng, A. and v. Leeuwen, T. T. and Lichtenberg, G. and Marshall, J. and Noël, S. and Notholt, J. and Palmer, P. and Parker, R. and Scholze, M. and Stiller, G. P. and Warneke, T. and Zehner, C.'
type: 'journal-article'
year: 2015
publication: 'The International Archives of the Photogrammetry, Remote Sensing and Spatial Information Sciences'
doi: '10.5194/isprsarchives-xl-7-w3-165-2015'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. The GHG-CCI project (http://www.esa-ghg-cci.org/) is one of several projects of the European Space Agency’s (ESA) Climate Change Initiative (CCI). The goal of the CCI is to generate and deliver data sets of various satellite-derived Essential Climate Variables (ECVs) in line with GCOS (Global Climate Observing System) requirements. The “ECV Greenhouse Gases” (ECV GHG) is the global distribution of important climate relevant gases – namely atmospheric CO<sub>2</sub> and CH<sub>4</sub> - with a quality sufficient to obtain information on regional CO<sub>2</sub> and CH<sub>4</sub> sources and sinks. The main goal of GHG-CCI is to generate long-term highly accurate and precise time series of global near-surface-sensitive satellite observations of CO<sub>2</sub> and CH<sub>4</sub>, i.e., XCO<sub>2</sub> and XCH<sub>4</sub>, starting with the launch of ESA’s ENVISAT satellite. These products are currently retrieved from SCIAMACHY/ENVISAT (2002-2012) and TANSO-FTS/GOSAT (2009-today) nadir mode observations in the near-infrared/shortwave-infrared spectral region. In addition, other sensors (e.g., IASI and MIPAS) and viewing modes (e.g., SCIAMACHY solar occultation) are also considered and in the future also data from other satellites. The GHG-CCI data products and related documentation are freely available via the GHG-CCI website and yearly updates are foreseen. Here we present an overview about the latest data set (Climate Research Data Package No. 2 (CRDP#2)) and summarize key findings from using satellite CO<sub>2</sub> and CH<sub>4</sub> retrievals to improve our understanding of the natural and anthropogenic sources and sinks of these important atmospheric greenhouse gases. We also shortly mention ongoing activities related to validation and initial user assessment of CRDP#2 and future plans.