---
title: 'CH<sub>4</sub> retrievals from space‐based solar backscatter measurements: Performance evaluation against simulated aerosol and cirrus loaded scenes'
author: 'Butz, A. and Hasekamp, O. P. and Frankenberg, C. and Vidot, J. and Aben, I.'
type: 'journal-article'
year: 2010
publication: 'Journal of Geophysical Research: Atmospheres'
doi: '10.1029/2010jd014514'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Monitoring of atmospheric methane (CH<sub>4</sub>) concentrations from space‐based instruments such as the Scanning Imaging Absorption Spectrometer for Atmospheric Chartography (SCIAMACHY) and the Greenhouse Gases Observing Satellite (GOSAT) relies on observations of sunlight backscattered to space by the Earth's surface and atmosphere. Retrieval biases occur due to unaccounted scattering effects by aerosols and thin cirrus that modify the lightpath. Here, we evaluate the accuracy of two retrieval methods that aim at minimizing such scattering induced errors. The lightpath “proxy” method, applicable to SCIAMACHY and GOSAT, retrieves CH<sub>4</sub> and carbon dioxide (CO<sub>2</sub>) simultaneously and uses CO<sub>2</sub> as a proxy for lightpath modification. The “physics‐based” method, which we propose for GOSAT, aims at simultaneously retrieving CH<sub>4</sub> concentrations and scattering properties of the atmosphere. We evaluate performance of the methods against a trial ensemble of simulated aerosol and cirrus loaded scenes. More than 80% of the trials yield residual scattering induced CH<sub>4</sub> errors below 0.6% and 0.8% for the proxy and the physics‐based approach, respectively. Very few cases result in errors greater than 2% for both methods. Advantages of the proxy approach are efficient and robust performance yielding more useful retrievals than the physics‐based method which reveals some nonconvergent cases. The major disadvantage of the proxy method is the uncertainty of the proxy CO<sub>2</sub> concentration contributing to the overall error budget. Residual errors generally correlate with particle and surface properties and thus might impact inverse modeling of CH<sub>4</sub> sources and sinks.