---
title: 'Understanding Terrestrial Water and Carbon Cycles and Their Interactions Using Integrated SMAP Soil Moisture and OCO‐2 SIF Observations and Land Surface Models'
author: 'Cao, Zhijiong and Xue, Yongkang and Nayak, Hara Prasad and Lettenmaier, Dennis P. and Frankenberg, Christian and Köhler, Philipp and Li, Ziwei'
type: 'journal-article'
year: 2024
publication: 'Journal of Geophysical Research: Atmospheres'
doi: '10.1029/2024jd041077'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

AbstractRecently, more advanced synchronous global‐scale satellite observations, the Soil Moisture Active Passive enhanced Level 3 (SMAP L<sub>3</sub>) soil moisture product and the Orbiting Carbon Observatory 2 (OCO‐2) solar‐induced chlorophyll fluorescence (SIF) product, provide an opportunity to improve the predictive understanding of both water and carbon cycles in land surface modeling. The Simplified Simple Biosphere Model version 4 (SSiB<sub>4</sub>) was coupled with the Top‐down Representation of Interactive Foliage and Flora Including Dynamics Model (TRIFFID) and a mechanistic representation of SIF. Incorporating dynamic vegetation processes reduced global SIF root‐mean‐squared error (RMSE) by 12%. Offline experiments were conducted to understand the water and carbon cycles and their interactions using satellite data as constraints. Results indicate that soil hydraulic properties, the soil hydraulic conductivity at saturation (Ks) and the water retention curve, significantly impact soil moisture and SIF simulation, especially in the semi‐arid regions. The wilting point and maximum Rubisco carboxylation rate (Vmax) affect photosynthesis and transpiration, then soil moisture. However, without atmospheric feedback processes, their effects on soil moisture are undermined due to the compensation between soil evaporation and transpiration. With optimized parameters based on SMAP L<sub>3</sub> and OCO‐2 data, the global RMSE of soil moisture and SIF simulations decreased by 15% and 12%, respectively. These findings highlight the importance of integrating advanced satellite data and dynamic vegetation processes to improve land surface models, enhancing understanding of terrestrial water and carbon cycles.