---
title: 'Systematic Assessment of Retrieval Methods for Canopy Far‐Red Solar‐Induced Chlorophyll Fluorescence Using High‐Frequency Automated Field Spectroscopy'
author: 'Chang, Christine Y. and Guanter, Luis and Frankenberg, Christian and Köhler, Philipp and Gu, Lianhong and Magney, Troy S. and Grossmann, Katja and Sun, Ying'
type: 'journal-article'
year: 2020
publication: 'Journal of Geophysical Research: Biogeosciences'
doi: '10.1029/2019jg005533'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

AbstractRemote sensing of solar‐induced chlorophyll fluorescence (SIF) offers potential to infer photosynthesis across scales and biomes. Many retrieval methods have been developed to estimate top‐of‐canopy SIF using ground‐based spectroscopy. However, inconsistencies among methods may confound interpretation of SIF dynamics, eco‐physiological/environmental drivers, and its relationship with photosynthesis. Using high temporal‐ and spectral resolution ground‐based spectroscopy, we aimed to (1) evaluate performance of SIF retrieval methods under diverse sky conditions using continuous field measurements; (2) assess method sensitivity to fluctuating light, reflectance, and fluorescence emission spectra; and (3) inform users for optimal ground‐based SIF retrieval. Analysis included field measurements from bi‐hemispherical and hemispherical‐conical systems and synthetic upwelling radiance constructed from measured downwelling radiance, simulated reflectance, and simulated fluorescence for benchmarking. Fraunhofer‐based differential optical absorption spectroscopy (DOAS) and singular vector decomposition (SVD) retrievals exhibit convergent SIF‐PAR relationships and diurnal consistency across different sky conditions, while O<sub>2</sub>A‐based spectral fitting method (SFM), SVD, and modified Fraunhofer line discrimination (3FLD) exhibit divergent SIF‐PAR relationships across sky conditions. Such behavior holds across system configurations, though hemispherical‐conical systems diverge less across sky conditions. O<sub>2</sub>A retrieval accuracy, influenced by atmospheric distortion, improves with a narrower fitting window and when training SVD with temporally local spectra. This may impact SIF‐photosynthesis relationships interpreted by previous studies using O<sub>2</sub>A‐based retrievals with standard (759–767.76 nm) fitting windows. Fraunhofer‐based retrievals resist atmospheric impacts but are noisier and more sensitive to assumed SIF spectral shape than O<sub>2</sub>A‐based retrievals. We recommend SVD or SFM using reduced fitting window (759.5–761.5 nm) for robust far‐red SIF retrievals across sky conditions.