---
title: 'Moisture availability mediates the relationship between terrestrial gross primary production and solar‐induced chlorophyll fluorescence: Insights from global‐scale variations'
author: 'Chen, Anping and Mao, Jiafu and Ricciuto, Daniel and Xiao, Jingfeng and Frankenberg, Christian and Li, Xing and Thornton, Peter E. and Gu, Lianhong and Knapp, Alan K.'
type: 'journal-article'
year: 2020
publication: 'Global Change Biology'
doi: '10.1111/gcb.15373'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract
Effective use of solar‐induced chlorophyll fluorescence (SIF) to estimate and monitor gross primary production (GPP) in terrestrial ecosystems requires a comprehensive understanding and quantification of the relationship between SIF and GPP. To date, this understanding is incomplete and somewhat controversial in the literature. Here we derived the GPP/SIF ratio from multiple data sources as a diagnostic metric to explore its global‐scale patterns of spatial variation and potential climatic dependence. We found that the growing season GPP/SIF ratio varied substantially across global land surfaces, with the highest ratios consistently found in boreal regions. Spatial variation in GPP/SIF was strongly modulated by climate variables. The most striking pattern was a consistent decrease in GPP/SIF from cold‐and‐wet climates to hot‐and‐dry climates. We propose that the reduction in GPP/SIF with decreasing moisture availability may be related to stomatal responses to aridity. Furthermore, we show that GPP/SIF can be empirically modeled from climate variables using a machine learning (random forest) framework, which can improve the modeling of ecosystem production and quantify its uncertainty in global terrestrial biosphere models. Our results point to the need for targeted field and experimental studies to better understand the patterns observed and to improve the modeling of the relationship between SIF and GPP over broad scales.