---
title: 'Decomposing reflectance spectra to track gross primary production in a subalpine evergreen forest'
author: 'Cheng, Rui and Magney, Troy S. and Dutta, Debsunder and Bowling, David R. and Logan, Barry A. and Burns, Sean P. and Blanken, Peter D. and Grossmann, Katja and Lopez, Sophia and Richardson, Andrew D. and Stutz, Jochen and Frankenberg, Christian'
type: 'journal-article'
year: 2020
publication: 'Biogeosciences'
doi: '10.5194/bg-17-4523-2020'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. Photosynthesis by terrestrial plants represents the majority of CO<sub>2</sub> uptake on Earth, yet it is difficult to measure directly from space. Estimation of gross primary production (GPP) from remote sensing indices represents a primary source of uncertainty, in particular for observing seasonal variations in evergreen forests. Recent vegetation remote sensing techniques have highlighted spectral regions sensitive to dynamic changes in leaf/needle carotenoid composition, showing promise for tracking seasonal changes in photosynthesis of evergreen forests. However, these have mostly been investigated with intermittent field campaigns or with narrow-band spectrometers in these ecosystems. To investigate this potential, we continuously measured vegetation reflectance (400–900 nm) using a canopy spectrometer system, PhotoSpec, mounted on top of an eddy-covariance flux tower in a subalpine evergreen forest at Niwot Ridge, Colorado, USA. We analyzed driving spectral components in the measured canopy reflectance using both statistical and process-based approaches. The decomposed spectral components co-varied with carotenoid content and GPP, supporting the interpretation of the photochemical reflectance index (PRI) and the chlorophyll/carotenoid index (CCI). Although the entire 400–900 nm range showed additional spectral changes near the red edge, it did not provide significant improvements in GPP predictions. We found little seasonal variation in both normalized difference vegetation index (NDVI) and the near-infrared vegetation index (NIRv) in this ecosystem. In addition, we quantitatively determined needle-scale chlorophyll-to-carotenoid ratios as well as anthocyanin contents using full-spectrum inversions, both of which were tightly correlated with seasonal GPP changes. Reconstructing GPP from vegetation reflectance using partial least-squares regression (PLSR) explained approximately 87 % of the variability in observed GPP. Our results linked the seasonal variation in reflectance to the pool size of photoprotective pigments, highlighting all spectral locations within 400–900 nm associated with GPP seasonality in evergreen forests.