---
title: 'On the consistency between global and regional methane emissions inferred from SCIAMACHY, TANSO-FTS, IASI and surface measurements'
author: 'Cressot, C. and Chevallier, F. and Bousquet, P. and Crevoisier, C. and Dlugokencky, E. J. and Fortems-Cheiney, A. and Frankenberg, C. and Parker, R. and Pison, I. and Scheepmaker, R. A. and Montzka, S. A. and Krummel, P. B. and Steele, L. P. and Langenfelds, R. L.'
type: 'journal-article'
year: 2014
publication: 'Atmospheric Chemistry and Physics'
doi: '10.5194/acp-14-577-2014'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. Satellite retrievals of methane weighted atmospheric columns are assimilated within a Bayesian inversion system to infer the global and regional methane emissions and sinks for the period August 2009 to July 2010. Inversions are independently computed from three different space-borne observing systems and one surface observing system under several hypotheses for prior-flux and observation errors. Posterior methane emissions are compared and evaluated against surface mole fraction observations via a chemistry-transport model. Apart from SCIAMACHY (SCanning Imaging Absorption spectroMeter for Atmospheric CartograpHY), the simulations agree fairly well with the surface mole fractions. The most consistent configurations of this study using TANSO-FTS (Thermal And Near infrared Sensor for carbon Observation – Fourier Transform Spectrometer), IASI (Infrared Atmospheric Sounding Interferometer) or surface measurements induce posterior methane global emissions of, respectively, 565 ± 21 Tg yr−1, 549 ± 36 Tg yr−1 and 538 ± 15 Tg yr−1 over the one-year period August 2009–July 2010. This consistency between the satellite retrievals (apart from SCIAMACHY) and independent surface measurements is promising for future improvement of CH<sub>4</sub> emission estimates by atmospheric inversions.