---
title: 'The on-orbit performance of the Orbiting Carbon Observatory-2 (OCO-2) instrument and its radiometrically calibrated products'
author: 'Crisp, David and Pollock, Harold R. and Rosenberg, Robert and Chapsky, Lars and Lee, Richard A. M. and Oyafuso, Fabiano A. and Frankenberg, Christian and O''Dell, Christopher W. and Bruegge, Carol J. and Doran, Gary B. and Eldering, Annmarie and Fisher, Brendan M. and Fu, Dejian and Gunson, Michael R. and Mandrake, Lukas and Osterman, Gregory B. and Schwandner, Florian M. and Sun, Kang and Taylor, Tommy E. and Wennberg, Paul O. and Wunch, Debra'
type: 'journal-article'
year: 2017
publication: 'Atmospheric Measurement Techniques'
doi: '10.5194/amt-10-59-2017'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. The Orbiting Carbon Observatory-2 (OCO-2) carries and points a three-channel imaging grating spectrometer designed to collect high-resolution, co-boresighted spectra of reflected sunlight within the molecular oxygen (O<sub>2</sub>) A-band at 0.765 microns and the carbon dioxide (CO<sub>2</sub>) bands at 1.61 and 2.06 microns. These measurements are calibrated and then combined into soundings that are analyzed to retrieve spatially resolved estimates of the column-averaged CO<sub>2</sub> dry-air mole fraction, XCO<sub>2</sub>. Variations of XCO<sub>2</sub> in space and time are then analyzed in the context of the atmospheric transport to quantify surface sources and sinks of CO<sub>2</sub>. This is a particularly challenging remote-sensing observation because all but the largest emission sources and natural absorbers produce only small (< 0.25 %) changes in the background XCO<sub>2</sub> field. High measurement precision is therefore essential to resolve these small variations, and high accuracy is needed because small biases in the retrieved XCO<sub>2</sub> distribution could be misinterpreted as evidence for CO<sub>2</sub> fluxes.  To meet its demanding measurement requirements, each OCO-2 spectrometer channel collects 24 spectra s−1 across a narrow (< 10 km) swath as the observatory flies over the sunlit hemisphere, yielding almost 1 million soundings each day. On monthly timescales, between 7 and 12 % of these soundings pass the cloud screens and other data quality filters to yield full-column estimates of XCO<sub>2</sub>. Each of these soundings has an unprecedented combination of spatial resolution (< 3 km2/sounding), spectral resolving power (λ∕Δλ > 17 000), dynamic range (∼ 104), and sensitivity (continuum signal-to-noise ratio > 400).  The OCO-2 instrument performance was extensively characterized and calibrated prior to launch. In general, the instrument has performed as expected during its first 18 months in orbit. However, ongoing calibration and science analysis activities have revealed a number of subtle radiometric and spectroscopic challenges that affect the yield and quality of the OCO-2 data products. These issues include increased numbers of bad pixels, transient artifacts introduced by cosmic rays, radiance discontinuities for spatially non-uniform scenes, a misunderstanding of the instrument polarization orientation, and time-dependent changes in the throughput of the oxygen A-band channel. Here, we describe the OCO-2 instrument, its data products, and its on-orbit performance. We then summarize calibration challenges encountered during its first 18 months in orbit and the methods used to mitigate their impact on the calibrated radiance spectra distributed to the science community.