---
title: 'Quantifying Global Power Plant Carbon Dioxide Emissions With Imaging Spectroscopy'
author: 'Cusworth, Daniel H. and Duren, Riley M. and Thorpe, Andrew K. and Eastwood, Michael L. and Green, Robert O. and Dennison, Philip E. and Frankenberg, Christian and Heckler, Joseph W. and Asner, Gregory P. and Miller, Charles E.'
type: 'journal-article'
year: 2021
publication: 'AGU Advances'
doi: '10.1029/2020av000350'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

AbstractAnthropogenic carbon dioxide (CO<sub>2</sub>) emissions dominate uncertainties in the global carbon budget. Global inventories, such as the National Greenhouse Gas Inventories, have latencies of 12–24 months and may not keep pace with rapidly changing infrastructure, particularly in the developing world. Our work reveals that airborne and satellite imaging spectrometers provide 3–30 m spatial resolution and accurate quantification of CO<sub>2</sub> emissions at the facility scale. Examples from 17 coal and gas fired power plants across the United States demonstrate robust correlation and 21% agreement on average between our remotely sensed estimates and simultaneous in situ measured emissions. We highlight four examples of coal‐fired power plants in India, Poland, and South Korea, where we quantify significant carbon dioxide emissions from power plants where limited public emissions data exist. Leveraging previous work on methane (CH<sub>4</sub>) plume detection, we present a strategy to exploit joint CO<sub>2</sub> and CH<sub>4</sub> plume imaging to quantify carbon emissions across widely distributed industrial infrastructure, including facilities that co‐emit CO<sub>2</sub> and CH<sub>4</sub>. We show an example of a coal operation, where we attribute 25% of greenhouse gas emissions to coal extraction (CH<sub>4</sub>) and the remaining 75% to energy generation (CO<sub>2</sub>). Satellite spectrometers could track high emitting coal‐fired power plants that collectively contribute to 60% or more of global coal CO<sub>2</sub> emissions. Multiple revisits and coordinated targeting of these high emitting facilities by multiple spaceborne instruments will be key to reducing uncertainties in global anthropogenic CO<sub>2</sub> emissions and supporting emissions mitigation strategies.