---
title: 'Potential of next-generation imaging spectrometers to detect and quantify methane point sources from space'
author: 'Cusworth, Daniel H. and Jacob, Daniel J. and Varon, Daniel J. and Chan Miller, Christopher and Liu, Xiong and Chance, Kelly and Thorpe, Andrew K. and Duren, Riley M. and Miller, Charles E. and Thompson, David R. and Frankenberg, Christian and Guanter, Luis and Randles, Cynthia A.'
type: 'journal-article'
year: 2019
publication: 'Atmospheric Measurement Techniques'
doi: '10.5194/amt-12-5655-2019'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. We examine the potential for global detection of methane plumes from
individual point sources with the new generation of spaceborne imaging
spectrometers (EnMAP, PRISMA, EMIT, SBG, CHIME) scheduled for launch in
2019–2025. These instruments are designed to map the Earth's surface at high
spatial resolution (30 m×30 m) and have a spectral resolution
of 7–10 nm in the 2200–2400 nm band that should also allow useful detection
of atmospheric methane. We simulate scenes viewed by EnMAP (10 nm spectral
resolution, 180 signal-to-noise ratio) using the EnMAP end-to-end simulation tool with superimposed methane plumes generated by large-eddy simulations.
We retrieve atmospheric methane and surface reflectivity for these scenes
using the IMAP-DOAS optimal estimation algorithm. We find an EnMAP precision
of 3 %–7 % for atmospheric methane depending on surface type. This allows
effective single-pass detection of methane point sources as small as 100 kg h−1 depending on surface brightness, surface homogeneity, and wind speed. Successful retrievals over very heterogeneous surfaces such as an
urban mosaic require finer spectral resolution. We tested the EnMAP
capability with actual plume observations over oil/gas fields in California
from the Airborne Visible/Infrared Imaging Spectrometer – Next Generation (AVIRIS-NG) sensor (3 m×3 m pixel resolution,
5 nm spectral resolution, SNR 200–400), by spectrally and spatially
downsampling the AVIRIS-NG data to match EnMAP instrument specifications.
Results confirm that EnMAP can successfully detect point sources of
∼100 kg h−1 over bright surfaces. Source rates inferred
with a generic integrated mass enhancement (IME) algorithm were lower for
EnMAP than for AVIRIS-NG. Better agreement may be achieved with a more
customized IME algorithm. Our results suggest that imaging spectrometers in
space could play an important role in the future for quantifying methane
emissions from point sources worldwide.