---
title: 'ClimaLand: A Land Surface Model Designed to Enable Data‐Driven Parameterizations'
author: 'Deck, Katherine and Braghiere, Renato K. and Renchon, Alexandre A. and Sloan, Julia and Bozzola, Gabriele and Speer, Edward and Ben Mackay, J. and Reddy, Teja and Phan, Kevin and Gagné‐Landmann, Anna L. and Li, Yuchen and Yatunin, Dennis and Charbonneau, Andrew and Efrat‐Henrici, Nat and Bach, Eviatar and Ma, Shuang and Gentine, Pierre and Frankenberg, Christian and Bloom, A. Anthony and Wang, Yujie and Longo, Marcos and Schneider, Tapio'
type: 'journal-article'
year: 2026
publication: 'Journal of Advances in Modeling Earth Systems'
doi: '10.1029/2025ms005118'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract
Land surface models (LSMs) are essential tools for simulating the coupled climate system, representing the dynamics of water, energy, and carbon fluxes on land and their interaction with the atmosphere. However, parameterizing sub‐grid processes at the scales relevant to climate models (10–100 km) remains a considerable challenge. The parameterizations typically have a large number of unknown and often correlated parameters, making calibration and uncertainty quantification difficult. Moreover, many existing LSMs are not readily adaptable to the incorporation of modern machine learning (ML) parameterizations trained with in situ and satellite data. This article presents the first version of ClimaLand, a new LSM designed for overcoming these limitations, including a description of the core equations underlying the model, the results of an extensive set of validation exercises, and an assessment of the computational performance of the model. We show that ClimaLand can leverage graphics processing units for computational efficiency, and that its modular architecture and high‐level programming language, Julia, allows for integration with ML libraries. In the future, this will enable efficient simulation, calibration, and uncertainty quantification with ClimaLand.