---
title: 'Optimal inverse estimation of ecosystem parameters from observations of carbon and energy fluxes'
author: 'Dutta, Debsunder and Schimel, David S. and Sun, Ying and van der Tol, Christiaan and Frankenberg, Christian'
type: 'journal-article'
year: 2019
publication: 'Biogeosciences'
doi: '10.5194/bg-16-77-2019'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. Canopy
structural and leaf photosynthesis parameterizations such as maximum
carboxylation capacity (Vcmax), slope of the Ball–Berry
stomatal conductance model (BBslope) and leaf area index (LAI)
are crucial for modeling plant physiological processes and canopy radiative
transfer. These parameters are large sources of uncertainty in predictions of
carbon and water fluxes. In this study, we develop an optimal moving window
nonlinear Bayesian inversion framework to use the Soil Canopy Observation
Photochemistry and Energy fluxes (SCOPE) model for constraining
Vcmax, BBslope and LAI with observations of
coupled carbon and energy fluxes and spectral reflectance from satellites. We
adapted SCOPE to follow the biochemical implementation of the Community Land
Model and applied the inversion framework for parameter retrievals of plant
species that have both the C<sub>3</sub> and C<sub>4</sub> photosynthetic pathways across
three ecosystems. We present comparative analysis of parameter retrievals
using observations of (i) gross primary productivity (GPP) and latent energy
(LE) fluxes and (ii) improvement in results when using flux observations
along with reflectance. Our results demonstrate the applicability of the
approach in terms of capturing the seasonal variability and posterior error
reduction (40 %–90 %) of key ecosystem parameters. The optimized
parameters capture the diurnal and seasonal variability in the GPP and LE
fluxes well when compared to flux tower observations (0.95>R<sub>2</sub>>0.79).
This study thus demonstrates the feasibility of parameter inversions using
SCOPE, which can be easily adapted to incorporate additional data sources
such as spectrally resolved reflectance and fluorescence and thermal
emissions.