---
title: 'A spatially downscaled sun-induced fluorescence global product for enhanced monitoring of vegetation productivity'
author: 'Duveiller, Gregory and Filipponi, Federico and Walther, Sophia and Köhler, Philipp and Frankenberg, Christian and Guanter, Luis and Cescatti, Alessandro'
type: 'journal-article'
year: 2020
publication: 'Earth System Science Data'
doi: '10.5194/essd-12-1101-2020'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. Sun-induced chlorophyll fluorescence (SIF) retrieved from satellite spectrometers can be a highly valuable proxy for photosynthesis. The SIF signal is very small and notoriously difficult to measure, requiring sub-nanometre spectral-resolution measurements, which to date are only available from atmospheric spectrometers sampling at low spatial resolution. For example, the widely used SIF dataset derived from the GOME-2 mission is typically provided in 0.5∘ composites. This paper presents a new SIF dataset based on GOME-2 satellite observations with an enhanced spatial resolution of 0.05∘ and an 8 d time step covering the period 2007–2018. It leverages on a proven methodology that relies on using a light-use efficiency (LUE) modelling approach to establish a semi-empirical relationship between SIF and various explanatory variables derived from remote sensing at higher spatial resolution. An optimal set of explanatory variables is selected based on an independent validation with OCO-2 SIF observations, which are only sparsely available but have a high accuracy and spatial resolution. After bias correction, the resulting downscaled SIF data show high spatio-temporal agreement with the first SIF retrievals from the new TROPOMI mission, opening the path towards establishing a surrogate archive for this promising new dataset. We foresee this new SIF dataset becoming a valuable asset for Earth system science in general and for monitoring vegetation productivity in particular. The dataset is available at https://doi.org/10.2905/21935FFC-B<sub>797</sub>-4BEE-94DA-8FEC85B3F9E1
(Duveiller et al., 2019).