---
title: 'The Orbiting Carbon Observatory-2 early science investigations of regional carbon dioxide fluxes'
author: 'Eldering, A. and Wennberg, P. O. and Crisp, D. and Schimel, D. S. and Gunson, M. R. and Chatterjee, A. and Liu, J. and Schwandner, F. M. and Sun, Y. and O’Dell, C. W. and Frankenberg, C. and Taylor, T. and Fisher, B. and Osterman, G. B. and Wunch, D. and Hakkarainen, J. and Tamminen, J. and Weir, B.'
type: 'journal-article'
year: 2017
publication: 'Science'
doi: '10.1126/science.aam5745'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

INTRODUCTIONEarth’s carbon cycle involves large fluxes of carbon dioxide (CO<sub>2</sub>) between the atmosphere, land biosphere, and oceans. Over the past several decades, net loss of CO<sub>2</sub> the atmosphere to the land and oceans has varied considerably from year to year, equaling 20 to 80% of CO<sub>2</sub> from fossil fuel combustion and land use change. On average, the uptake is about 50%. The imbalance between CO<sub>2</sub> and removal is seen in increasing atmospheric CO<sub>2</sub>. In recent years, an increase of 2 to 3 parts per million (ppm) per year in the atmospheric mole fraction, which is currently about 400 ppm, has been observed.Almost a quarter of the CO<sub>2</sub> by human activities is being absorbed by the ocean, and another quarter is absorbed by processes on land. The identity and location of the terrestrial sinks are poorly understood. This absorption has been attributed by some to tropical or Eurasian temperate forests, whereas others argue that these regions may be net sources of CO<sub>2</sub>. The efficiency of these land sinks appears to vary dramatically from year to year. Because the identity, location, and processes controlling these natural sinks are not well constrained, substantial additional uncertainty is added to projections of future CO<sub>2</sub>.RATIONALEThe NASA satellite, the Orbiting Carbon Observatory-2 (OCO-2), which was launched on 2 July 2014, is designed to collect global measurements with sufficient precision, coverage, and resolution to aid in resolving sources and sinks of CO<sub>2</sub> regional scales. Since 6 September 2014, the OCO-2 mission has been producing about 2 million estimates of the column-averaged CO<sub>2</sub>-air mole fraction (XCO<sub>2</sub>) each month after quality screening, with spatial resolution of <3 km2per sounding. Solar-induced chlorophyll fluorescence (SIF), a small amount of light emitted during photosynthesis, is detected in remote sensing measurements of radiance within solar Fraunhofer lines and is another data product from OCO-2.RESULTSThe measurements from OCO-2 provide a global view of the seasonal cycles and spatial patterns of atmospheric CO<sub>2</sub>, with the anticipated year-over-year growth rate. The buildup of CO<sub>2</sub> the Northern Hemisphere during winter and its rapid decrease in concentration as spring arrives (and the SIF increases) is seen in unprecedented detail. The enhanced CO<sub>2</sub> urban areas relative to nearby background areas is observed with a single overpass of OCO-2. Increases in CO<sub>2</sub> to the biomass burning in Africa are also clearly observed. The dense, global,XCO<sub>2</sub> SIF data sets from OCO-2 are combined with other remote sensing data sets and used to disentangle the processes driving the carbon cycle on regional scales during the recent 2015–2016 El Niño event. This analysis shows more carbon release in 2015 relative to 2011 over Africa, South America, and Southeast Asia. Now, the fundamental driver for the change in carbon release can be assessed continent by continent, rather than treating the tropics as a single, integrated region. Small changes inXCO2were also observed early in the El Niño over the equatorial eastern Pacific, due to less upwelling of cold, carbon-rich water than is typical.CONCLUSIONNASA’s OCO-2 mission is collecting a dense, global set of high-spectral resolution measurements that are used to estimateXCO2and SIF. The OCO-2 mission data set can now be used to assess regional-scale sources and sinks of CO<sub>2</sub> the globe. The papers in this collection present early scientific findings from this new data set.El Niño impact on carbon flux in 2015 relative to 2011, detected from Greenhouse Gases Observing Satellite (GOSAT) and OCO-2 data.OCO-2 uses reflected sunlight to deriveXCO2and SIF. This shows OCO-2XCO2data over North America from 12 August 2015 to 26 August 2015.