---
title: 'Remote Sensing of Chlorophyll Fluorescence in the Ocean Using Imaging Spectrometry: Toward a Vertical Profile of Fluorescence'
author: 'Erickson, Z. K. and Frankenberg, C. and Thompson, D. R. and Thompson, A. F. and Gierach, M.'
type: 'journal-article'
year: 2019
publication: 'Geophysical Research Letters'
doi: '10.1029/2018gl081273'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

AbstractChlorophyll fluorescence measurements provide valuable information on phytoplankton abundance and physiology. High spectral resolution measurements from the aircraft‐mounted Portable Remote Imaging SpectroMeter (PRISM) allow for a more robust and informative fluorescence measurement than previous methods. An increase in radiation in the fluorescence wavelength range is approximated by a skew‐normal distribution. Positive skew suggests the influence of water attenuation and motivates the use of an inverse retrieval model to solve for the most likely vertical distribution of fluorescence quantum yield. This approach is tested with theoretical fluorescence profiles and applied to a PRISM flightline located in southern Drake Passage, Southern Ocean during austral summer. The resulting profiles suggest vertical structure in fluorescence quantum yield in the upper 10 m, which matches expectations from in situ studies. The framework developed in this paper can be applied to current and future satellite missions, providing more information on phytoplankton concentrations, vertical profiles, and physiology.