---
title: 'Retrieval of CO from SCIAMACHY onboard ENVISAT: detection of strongly polluted areas and seasonal patterns in global CO abundances'
author: 'Frankenberg, C. and Platt, U. and Wagner, T.'
type: 'journal-article'
year: 2005
publication: 'Atmospheric Chemistry and Physics'
doi: '10.5194/acp-5-1639-2005'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. SCIAMACHY onboard the European environmental research satellite ENVISAT is an UV/visible/near-infrared spectrometer providing 3 near infrared channels covering wavelengths from 1-1.75 µm, 1.94-2.04 µm and 2.26-2.38 µm with moderate spectral resolution (0.22-1.5nm). From their structured absorption in these spectral regions, we can quantitatively determine the total column densities of the greenhouse gases CO<sub>2</sub>, CH<sub>4</sub>, N<sub>2</sub>O and H<sub>2</sub>O as well as of CO. A modified DOAS algorithm based on optimal estimation (IMAP-DOAS) has been developed at the University of Heidelberg to account for the peculiarities of these absorbers. CO is a relatively weak absorber whose spectral signature is overlapped by strong CH<sub>4</sub> and H<sub>2</sub>O absorptions. Hence, retrieval of CO from SCIAMACHY spectra (within 2.26-2.38 µm) is a challenging task. Therefore, the calibration of the raw spectra with respect to dark current issues and nonlinearity were analysed in detail and substantially improved to enable reasonable retrieval of CO. This paper focusses on first results of the CO retrieval where various sources like biomass burning events and their seasonal variability can be clearly identified.