---
title: 'Tropical methane emissions: A revised view from SCIAMACHY onboard ENVISAT'
author: 'Frankenberg, Christian and Bergamaschi, Peter and Butz, André and Houweling, Sander and Meirink, Jan Fokke and Notholt, Justus and Petersen, Anna Katinka and Schrijver, Hans and Warneke, Thorsten and Aben, Ilse'
type: 'journal-article'
year: 2008
publication: 'Geophysical Research Letters'
doi: '10.1029/2008gl034300'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Methane retrievals from near‐infrared spectra recorded by the SCIAMACHY instrument onboard ENVISAT hitherto suggested unexpectedly large tropical emissions. Even though recent studies confirm substantial tropical emissions, there were indications for an unresolved error in the satellite retrievals. Here we identify a retrieval error related to inaccuracies in water vapor spectroscopic parameters, causing a substantial overestimation of methane correlated with high water vapor abundances. We report on the overall implications of an update in water spectroscopy on methane retrievals with special focus on the tropics where the impact is largest. The new retrievals are applied in a four‐dimensional variational (4D‐VAR) data assimilation system to derive a first estimate of the impact on tropical CH<sub>4</sub> sources. Compared to inversions based on previous SCIAMACHY retrievals, annual tropical emission estimates are reduced from 260 to about 201 Tg CH<sub>4</sub> but still remain higher than previously anticipated.