---
title: 'Using airborne HIAPER Pole-to-Pole Observations (HIPPO)  to evaluate model and remote sensing estimates of atmospheric carbon dioxide'
author: 'Frankenberg, Christian and Kulawik, Susan S. and Wofsy, Steven C. and Chevallier, Frédéric and Daube, Bruce and Kort, Eric A. and O''Dell, Christopher and Olsen, Edward T. and Osterman, Gregory'
type: 'journal-article'
year: 2016
publication: 'Atmospheric Chemistry and Physics'
doi: '10.5194/acp-16-7867-2016'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. In recent years, space-borne observations of atmospheric carbon dioxide (CO<sub>2</sub>) have been increasingly used in global carbon-cycle studies. In order to obtain added value from space-borne measurements, they have to suffice stringent accuracy and precision requirements, with the latter being less crucial as it can be reduced by just enhanced sample size. Validation of CO<sub>2</sub> column-averaged dry air mole fractions (XCO<sub>2</sub>) heavily relies on measurements of the Total Carbon Column Observing Network (TCCON). Owing to the sparseness of the network and the requirements imposed on space-based measurements, independent additional validation is highly valuable. Here, we use observations from the High-Performance Instrumented Airborne Platform for Environmental Research (HIAPER) Pole-to-Pole Observations (HIPPO) flights from 01/2009 through 09/2011 to validate CO<sub>2</sub> measurements from satellites (Greenhouse Gases Observing Satellite – GOSAT, Thermal Emission Sounder – TES, Atmospheric Infrared Sounder – AIRS) and atmospheric inversion models (CarbonTracker CT<sub>2013</sub>B, Monitoring Atmospheric Composition and Climate (MACC) v13r1). We find that the atmospheric models capture the XCO<sub>2</sub> variability observed in HIPPO flights very well, with correlation coefficients (r2) of 0.93 and 0.95 for CT<sub>2013</sub>B and MACC, respectively. Some larger discrepancies can be observed in profile comparisons at higher latitudes, in particular at 300 hPa during the peaks of either carbon uptake or release. These deviations can be up to 4 ppm and hint at misrepresentation of vertical transport.  Comparisons with the GOSAT satellite are of comparable quality, with an r2 of 0.85, a mean bias μ of −0.06 ppm, and a standard deviation σ of 0.45 ppm. TES exhibits an r2 of 0.75, μ of 0.34 ppm, and σ of 1.13 ppm. For AIRS, we find an r2 of 0.37, μ of 1.11 ppm, and σ of 1.46 ppm, with latitude-dependent biases. For these comparisons at least 6, 20, and 50 atmospheric soundings have been averaged for GOSAT, TES, and AIRS, respectively. Overall, we find that GOSAT soundings over the remote Pacific Ocean mostly meet the stringent accuracy requirements of about 0.5 ppm for space-based CO<sub>2</sub> observations.