---
title: 'Satellite chartography of atmospheric methane from SCIAMACHY on board ENVISAT: Analysis of the years 2003 and 2004'
author: 'Frankenberg, C. and Meirink, J. F. and Bergamaschi, P. and Goede, A. P. H. and Heimann, M. and Körner, S. and Platt, U. and van Weele, M. and Wagner, T.'
type: 'journal-article'
year: 2006
publication: 'Journal of Geophysical Research: Atmospheres'
doi: '10.1029/2005jd006235'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

The UV/Vis/near infrared spectrometer SCIAMACHY on board the European ENVISAT satellite enables total column retrieval of atmospheric methane with high sensitivity to the lower troposphere. The vertical column density of methane is converted to column averaged mixing ratio by using carbon dioxide retrievals as proxy for the probed atmospheric column. For this purpose, we apply concurrent total column measurements of CO<sub>2</sub> in combination with modeled column‐averaged CO<sub>2</sub> mixing ratios. Possible systematic errors are discussed in detail while the precision error is 1.8% on average. This paper focuses on methane retrievals from January 2003 through December 2004. The measurements with global coverage over continents are compared with model results from the chemistry–transport model TM<sub>4</sub>. In the retrievals, the north‐south gradient as well as regions with enhanced methane levels can be clearly identified. The highest abundances are found in the Red Basin of China, followed by northern South America, the Gangetic plains of India and central parts of Africa. Especially the abundances in northern South America and the Red Basin are generally higher than modeled. Further, we present the seasonal variations within the investigated time period. Peak values in Asia due to rice emissions are observed from August through October. We expand earlier investigations that suggest underestimated emissions in the tropics. It is shown that these underestimations show a seasonal behavior that peaks from August through December. The global measurements may be used for inverse modeling and are thus an important step towards better quantification of the methane budget.