---
title: 'Aerosol information content analysis of multi-angle high spectral resolution measurements and its benefit for high accuracy greenhouse gas retrievals'
author: 'Frankenberg, C. and Hasekamp, O. and O''Dell, C. and Sanghavi, S. and Butz, A. and Worden, J.'
type: 'journal-article'
year: 2012
publication: 'Atmospheric Measurement Techniques'
doi: '10.5194/amt-5-1809-2012'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. New generations of space-borne spectrometers for the retrieval of atmospheric abundances of greenhouse gases require unprecedented accuracies as atmospheric variability of long-lived gases is very low. These instruments, such as GOSAT and OCO-2, typically use a high spectral resolution oxygen channel (O<sub>2</sub> A-band) in addition to CO<sub>2</sub> and CH<sub>4</sub> channels to discriminate changes in the photon path-length distribution from actual trace gas amount changes. Inaccurate knowledge of the photon path-length distribution, determined by scatterers in the atmosphere, is the prime source of systematic biases in the retrieval. In this paper, we investigate the combined aerosol and greenhouse gas retrieval using multiple satellite viewing angles simultaneously. We find that this method, hitherto only applied in multi-angle imagery such as from POLDER or MISR, greatly enhances the ability to retrieve aerosol properties by 2–3 degrees of freedom. We find that the improved capability to retrieve aerosol parameters significantly reduces interference errors introduced into retrieved CO<sub>2</sub> and CH<sub>4</sub> total column averages. Instead of focussing solely on improvements in spectral and spatial resolution, signal-to-noise ratios or sampling frequency, multiple angles reduce uncertainty in space based greenhouse gas retrievals more effectively and provide a new potential for dedicated aerosols retrievals.