---
title: 'Remote sensing of near-infrared chlorophyll fluorescence from space in scattering atmospheres: implications for its retrieval and interferences with atmospheric CO
<sub>2</sub>
retrievals'
author: 'Frankenberg, C. and O''Dell, C. and Guanter, L. and McDuffie, J.'
type: 'journal-article'
year: 2012
publication: 'Atmospheric Measurement Techniques'
doi: '10.5194/amt-5-2081-2012'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. With the advent of dedicated greenhouse gas space-borne spectrometers sporting high resolution spectra in the O<sub>2</sub> A-band spectral region (755–774 nm), the retrieval of chlorophyll fluorescence has become feasible on a global scale. If unaccounted for, however, fluorescence can indirectly perturb the greenhouse gas retrievals as it perturbs the oxygen absorption features. As atmospheric CO<sub>2</sub> measurements are used to invert net fluxes at the land–atmosphere interface, a bias caused by fluorescence can be crucial as it will spatially correlate with the fluxes to be inverted. Avoiding a bias and retrieving fluorescence accurately will provide additional constraints on both the net and gross fluxes in the global carbon cycle. We show that chlorophyll fluorescence, if neglected, systematically interferes with full-physics multi-band XCO<sub>2</sub> retrievals using the O<sub>2</sub> A-band. Systematic biases in XCO<sub>2</sub> can amount to +1 ppm if fluorescence constitutes 1% to the continuum level radiance. We show that this bias can be largely eliminated by simultaneously fitting fluorescence in a full-physics based retrieval.  If fluorescence is the primary target, a dedicated but very simple retrieval based purely on Fraunhofer lines is shown to be more accurate and very robust even in the presence of large scattering optical depths. We find that about 80% of the surface fluorescence is retained at the top-of-atmosphere, even for cloud optical thicknesses around 2–5. We further show that small instrument modifications to future O<sub>2</sub> A-band spectrometer spectral ranges can result in largely reduced random errors in chlorophyll fluorescence, paving the way towards a more dedicated instrument exploiting solar absorption features only.