---
title: 'The Orbiting Carbon Observatory (OCO-2): spectrometer performance evaluation using pre-launch direct sun measurements'
author: 'Frankenberg, C. and Pollock, R. and Lee, R. A. M. and Rosenberg, R. and Blavier, J.-F. and Crisp, D. and O''Dell, C. W. and Osterman, G. B. and Roehl, C. and Wennberg, P. O. and Wunch, D.'
type: 'journal-article'
year: 2015
publication: 'Atmospheric Measurement Techniques'
doi: '10.5194/amt-8-301-2015'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. The Orbiting Carbon Observatory-2 (OCO-2), launched on 2 July 2014, is a NASA mission designed to measure the column-averaged CO<sub>2</sub> dry air mole fraction, XCO<sub>2</sub>. Towards that goal, it will collect spectra of reflected sunlight in narrow spectral ranges centered at 0.76, 1.6 and 2.0 μm with a resolving power (λ/Δ λ) of 20 000. These spectra will be used in an optimal estimation framework to retrieve XCO<sub>2</sub>. About 100 000 cloud free soundings of XCO<sub>2</sub> each day will allow estimates of net CO<sub>2</sub> fluxes on regional to continental scales to be determined. Here, we evaluate the OCO-2 spectrometer performance using pre-launch data acquired during instrument thermal vacuum tests in April 2012. A heliostat and a diffuser plate were used to feed direct sunlight into the OCO-2 instrument and spectra were recorded. These spectra were compared to those collected concurrently from a nearby high-resolution Fourier Transform Spectrometer that was part of the Total Carbon Column Observing Network (TCCON). Using the launch-ready OCO-2 calibration and spectroscopic parameters, we performed total column scaling fits to all spectral bands and compared these to TCCON results. On 20 April, we detected a CO<sub>2</sub> plume from the Los Angeles basin at the JPL site with strongly enhanced short-term variability on the order of 1% (3–4 ppm). We also found good (< 0.5 ppm) inter-footprint consistency in retrieved XCO<sub>2</sub>. The variations in spectral fitting residuals are consistent with signal-to-noise estimates from instrument calibration, while average residuals are systematic and mostly attributable to remaining errors in our knowledge of the CO<sub>2</sub> and O<sub>2</sub> spectroscopic parameters. A few remaining inconsistencies observed during the tests may be attributable to the specific instrument setup on the ground and will be re-evaluated with in-orbit data.