---
title: 'A convolutional neural network for spatial downscaling of satellite-based solar-induced chlorophyll fluorescence (SIFnet)'
author: 'Gensheimer, Johannes and Turner, Alexander J. and Köhler, Philipp and Frankenberg, Christian and Chen, Jia'
type: 'journal-article'
year: 2022
publication: 'Biogeosciences'
doi: '10.5194/bg-19-1777-2022'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. Gross primary productivity (GPP) is the sum of leaf photosynthesis and represents a crucial component of the global carbon cycle. Space-borne estimates of GPP typically rely on observable quantities that co-vary with GPP such as vegetation indices using reflectance measurements (e.g., normalized difference vegetation index, NDVI, near-infrared reflectance of terrestrial vegetation, NIRv, and kernel normalized difference vegetation index, kNDVI). Recent work has also utilized measurements of solar-induced chlorophyll fluorescence (SIF) as a proxy for GPP. However, these SIF measurements are typically coarse resolution, while many processes influencing GPP occur at fine spatial scales. Here, we develop a convolutional neural network (CNN), named SIFnet, that increases the resolution of SIF from the TROPOspheric Monitoring Instrument (TROPOMI) on board of the satellite Sentinel-5P by a factor of 10 to a spatial resolution of 500 m. SIFnet utilizes coarse SIF observations together with high-resolution auxiliary data. The auxiliary data used here may carry information related to GPP and SIF. We use training data from non-US regions between April 2018 until March 2021 and evaluate our CNN over the conterminous United States (CONUS). We show that SIFnet is able to increase the resolution of TROPOMI SIF by a factor of 10 with a r2 and RMSE metrics of 0.92 and 0.17 mW m−2 sr−1 nm−1, respectively. We further compare SIFnet against a recently developed downscaling approach and evaluate both methods against independent SIF measurements from Orbiting Carbon Observatory 2 and 3 (together OCO-2/3). SIFnet performs systematically better than the downscaling approach (r=0.78 for SIFnet, r=0.72 for downscaling), indicating that it is picking up on key features related to SIF and GPP. Examination of the feature importance in the neural network indicates a few key parameters and the spatial regions in which these parameters matter. Namely, the CNN finds low-resolution SIF data to be the most significant parameter with the NIRv vegetation index as the second most important parameter. NIRv consistently outperforms the recently proposed kNDVI vegetation index. Advantages and limitations of SIFnet are investigated and presented through a series of case studies across the United States. SIFnet represents a robust method to infer continuous, high-spatial-resolution SIF data.