---
title: 'Potential of the TROPOspheric Monitoring Instrument (TROPOMI) onboard the Sentinel-5 Precursor for the monitoring of terrestrial chlorophyll fluorescence'
author: 'Guanter, L. and Aben, I. and Tol, P. and Krijger, J. M. and Hollstein, A. and Köhler, P. and Damm, A. and Joiner, J. and Frankenberg, C. and Landgraf, J.'
type: 'journal-article'
year: 2015
publication: 'Atmospheric Measurement Techniques'
doi: '10.5194/amt-8-1337-2015'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. Global monitoring of sun-induced chlorophyll fluorescence (SIF) is improving our knowledge about the photosynthetic functioning of terrestrial ecosystems. The feasibility of SIF retrievals from spaceborne atmospheric spectrometers has been demonstrated by a number of studies in the last years. In this work, we investigate the potential of the upcoming TROPOspheric Monitoring Instrument (TROPOMI) onboard the Sentinel-5 Precursor satellite mission for SIF retrieval. TROPOMI will sample the 675–775 nm spectral window with a spectral resolution of 0.5 nm and a pixel size of 7 km × 7 km. We use an extensive set of simulated TROPOMI data in order to assess the uncertainty of single SIF retrievals and subsequent spatio-temporal composites. Our results illustrate the enormous improvement in SIF monitoring achievable with TROPOMI with respect to comparable spectrometers currently in-flight, such as the Global Ozone Monitoring Experiment-2 (GOME-2) instrument. We find that TROPOMI can reduce global uncertainties in SIF mapping by more than a factor of 2 with respect to GOME-2, which comes together with an approximately 5-fold improvement in spatial sampling. Finally, we discuss the potential of TROPOMI to map other important vegetation parameters at a global scale with moderate spatial resolution and short revisit time. Those include leaf photosynthetic pigments and proxies for canopy structure, which will complement SIF retrievals for a self-contained description of vegetation condition and functioning.