---
title: 'The TROPOSIF global sun-induced fluorescence dataset from the Sentinel-5P TROPOMI mission'
author: 'Guanter, Luis and Bacour, Cédric and Schneider, Andreas and Aben, Ilse and van Kempen, Tim A. and Maignan, Fabienne and Retscher, Christian and Köhler, Philipp and Frankenberg, Christian and Joiner, Joanna and Zhang, Yongguang'
type: 'journal-article'
year: 2021
publication: 'Earth System Science Data'
doi: '10.5194/essd-13-5423-2021'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. The first satellite-based global retrievals of terrestrial sun-induced
chlorophyll fluorescence (SIF) were achieved in 2011. Since then, a number of
global SIF datasets with different spectral, spatial, and temporal sampling characteristics have become available to the scientific community. These
datasets have been useful to monitor the dynamics and productivity of a range
of vegetated areas worldwide, but the coarse spatiotemporal sampling and low
signal-to-noise ratio of the data hamper their application over small or
fragmented ecosystems. The recent advent of the Copernicus Sentinel-5P TROPOMI
mission and the high quality of its data products promise to alleviate this
situation, as TROPOMI provides daily global measurements at a much denser
spatial and temporal sampling than earlier satellite instruments. In this
work, we present a global SIF dataset produced from TROPOMI measurements
within the TROPOSIF project funded by the European Space Agency. The current
version of the TROPOSIF dataset covers the time period between May 2018 and
April 2021. Baseline SIF retrievals are derived from the 743–758 nm
window. A secondary SIF dataset derived from an extended fitting window
(735–758 nm window) is included. This provides an enhanced signal-to-noise
ratio at the expense of a higher sensitivity to atmospheric effects. Spectral
reflectance spectra at seven 3 nm windows devoid of atmospheric absorption
within the 665–785 nm range are also included in the TROPOSIF dataset as an
important ancillary variable to be used in combination with SIF. The
methodology to derive SIF and ancillary data as well as results from an
initial data quality assessment are presented in this work. The TROPOSIF
dataset is available through the following digital object identifier (DOI):
https://doi.org/10.5270/esa-s5p_innovation-sif-20180501_20210320-v2.1-202104
(Guanter et al., 2021).