---
title: 'From the Ground to Space: Using Solar‐Induced Chlorophyll Fluorescence to Estimate Crop Productivity'
author: 'He, Liyin and Magney, Troy and Dutta, Debsunder and Yin, Yi and Köhler, Philipp and Grossmann, Katja and Stutz, Jochen and Dold, Christian and Hatfield, Jerry and Guan, Kaiyu and Peng, Bin and Frankenberg, Christian'
type: 'journal-article'
year: 2020
publication: 'Geophysical Research Letters'
doi: '10.1029/2020gl087474'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract

Timely and accurate monitoring of crops is essential for food security. Here, we examine how well solar‐induced chlorophyll fluorescence (SIF) can inform crop productivity across the United States. Based on tower‐level observations and process‐based modeling, we find highly linear gross primary production (GPP):SIF relationships for C<sub>4</sub> crops, while C<sub>3</sub> crops show some saturation of GPP at high light when SIF continues to increase. C<sub>4</sub> crops yield higher GPP:SIF ratios (30–50%) primarily because SIF is most sensitive to the light reactions (does not account for photorespiration). Scaling to the satellite, we compare SIF from the TROPOspheric Monitoring Instrument (TROPOMI) against tower‐derived GPP and county‐level crop statistics. Temporally, TROPOMI SIF strongly agrees with GPP observations upscaled across a corn and soybean dominated cropland (
R
2
= 0.89). Spatially, county‐level TROPOMI SIF correlates with crop productivity (
R
2
= 0.72; 0.86 when accounting for planted area and C<sub>3</sub>/C<sub>4</sub> contributions), highlighting the potential of SIF for reliable crop monitoring.