---
title: 'Tracking Seasonal and Interannual Variability in Photosynthetic Downregulation in Response to Water Stress at a Temperate Deciduous Forest'
author: 'He, Liyin and Wood, Jeffrey D. and Sun, Ying and Magney, Troy and Dutta, Debsunder and Köhler, Philipp and Zhang, Yongguang and Yin, Yi and Frankenberg, Christian'
type: 'journal-article'
year: 2020
publication: 'Journal of Geophysical Research: Biogeosciences'
doi: '10.1029/2018jg005002'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

AbstractThe understanding and modeling of photosynthetic dynamics affected by climate variability can be highly uncertain. In this paper, we examined a well‐characterized eddy covariance site in a drought‐prone temperate deciduous broadleaf forest combining tower measurements and satellite observations. We find that an increase in spring temperature usually leads to enhanced spring gross primary production (GPP), but a GPP reduction in late growing season due to water limitation. We evaluated how well a coupled fluorescence‐photosynthesis model (SCOPE) and satellite data sets track the interannual and seasonal variations of tower GPP from 2007 to 2016. In SCOPE, a simple stress factor scaling of Vcmax as a linear function of observed predawn leaf water potential (ψpd) shows a good agreement between modeled and measured interannual variations in both GPP and solar‐induced chlorophyll fluorescence (SIF) from the Global Ozone Monitoring Experiment‐2 (GOME‐2). The modeled and satellite‐observed changes in SIFyield are ~30% smaller than corresponding changes in light use efficiency (LUE) under severe stress, for which a common linear SIF to GPP scaling would underestimate the stress reduction in GPP. Overall, GOME‐2 SIF tracks interannual tower GPP variations better than satellite vegetations indices (VIs) representing canopy “greenness.” However, it is still challenging to attribute observed SIF variations unequivocally to greenness or physiological changes due to large GOME‐2 footprint. Higher‐resolution SIF data sets (e.g., TROPOMI) already show the potential to well capture the downregulation of late‐season GPP and could pave the way to better disentangle canopy structural and physiological changes in the future.