---
title: 'Remote‐Sensing Derived Trends in Gross Primary Production Explain Increases in the CO<sub>2</sub> Seasonal Cycle Amplitude'
author: 'He, Liyin and Byrne, Brendan and Yin, Yi and Liu, Junjie and Frankenberg, Christian'
type: 'journal-article'
year: 2022
publication: 'Global Biogeochemical Cycles'
doi: '10.1029/2021gb007220'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

AbstractAn increase in the seasonal cycle amplitude (SCA) of atmospheric CO<sub>2</sub> since the 1960s has been observed in the Northern Hemisphere (NH). However, the underlying dominant drivers are still debated. The peak season CO<sub>2</sub> uptake by vegetation is critical in shaping the CO<sub>2</sub> seasonality. Using satellite‐upscaled gross primary production (GPP) from FLUXCOM and near‐infrared reflectance of vegetation (NIRV), we demonstrate that peak GPP has increased across the NH over the last two decades. We relate this productivity increase to changes in the CO<sub>2</sub> SCA using an atmospheric transport model. The increased photosynthesis has strongly contributed to CO<sub>2</sub> SCA trends, but with substantial latitudinal and longitudinal variations. Despite a general increase in the CO<sub>2</sub> SCA, there are distinct regional differences. These differences are mainly controlled by regional biosphere carbon fluxes, with the remainder explained by non‐biome factors, including large‐scale atmospheric transport, changes in fossil fuel combustion, biomass burning and oceanic fluxes. Using the global flask and in situ CO<sub>2</sub> measurement sites, we find that SCA trends at high latitude are mainly driven by increasingly productive natural ecosystems, whereas mid latitude sites around the Midwest United States are mainly impacted by intensified agriculture and atmospheric transport. Averaging across the 15 long‐term surface sites, forests contribute 26% (7%) to the SCA trends, while crops contribute 17% (24%) and the combined shrubland, grassland and wetland regions contribute 23% (37%) for simulations driven by FLUXCOM (NIRv) ecosystem fluxes. Our findings demonstrate that satellite inferred trends of ecosystem fluxes can capture the observed CO<sub>2</sub> SCA trend.