---
title: 'Atmospheric constraints on global emissions of methane from plants'
author: 'Houweling, S. and Röckmann, T. and Aben, I. and Keppler, F. and Krol, M. and Meirink, J. F. and Dlugokencky, E. J. and Frankenberg, C.'
type: 'journal-article'
year: 2006
publication: 'Geophysical Research Letters'
doi: '10.1029/2006gl026162'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

We investigate whether a recently proposed large source of CH<sub>4</sub> from vegetation can be reconciled with atmospheric measurements. Atmospheric transport model simulations with and without vegetation emissions are compared with background CH<sub>4</sub>, δ13C‐CH<sub>4</sub> and satellite measurements. For present–day CH<sub>4</sub> we derive an upper limit to the newly discovered source of 125 Tg CH<sub>4</sub> yr−1. Analysis of preindustrial CH<sub>4</sub>, however, points to 85 Tg CH<sub>4</sub> yr−1 as a more plausible limit. Model calculations with and without vegetation emissions show strikingly similar results at background surface monitoring sites, indicating that these measurements are rather insensitive to CH<sub>4</sub> from plants. Simulations with 125 Tg CH<sub>4</sub> yr−1 vegetation emissions can explain up to 50% of the previously reported unexpectedly high CH<sub>4</sub> column abundances over tropical forests observed by SCIAMACHY. Our results confirm the potential importance of vegetation emissions, and call for further research.