---
title: 'Methane Growth Rate Estimation and Its Causes in Western Canada Using Satellite Observations'
author: 'Islam, S. M. Nazrul and Jackson, Peter L. and Sweeney, Colm and McKain, Kathryn and Frankenberg, Christian and Aben, Ilse and Parker, Robert J. and Boesch, Hartmut and Wunch, Debra'
type: 'journal-article'
year: 2021
publication: 'Journal of Geophysical Research: Atmospheres'
doi: '10.1029/2020jd033948'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

AbstractIn this study, the GOSAT Proxy Retrieval (v9.0) data product of column‐averaged dry‐air mole fractions of atmospheric methane (XCH<sub>4</sub>) for the period 2009–2019 was analyzed to detect methane (CH<sub>4</sub>) trends in the three western Canadian provinces where oil and gas development activities have changed significantly over the last decade. Although we found statistically significant increasing XCH<sub>4</sub> trends in all subdomains (northeast British Columbia‐NE, Alberta‐AB, southern Saskatchewan‐SK), XCH<sub>4</sub> trends are not higher than the background trend (7.25 ± 0.30 ppb/yr) and enhancement trends (ΔXCH4, after removing the background quantity) are not detectable at any subdomain during 2009–2019. For further insight into trends in all subdomains, we divided the whole period (2009–2019) into two shorter periods (2009–2013 and 2014–2019) and estimated trends. We found XCH<sub>4</sub> trends are higher than background trends particularly in the AB and SK subdomains during 2009–2013, and their ΔXCH4 trends are positive and also marginally statistically significant. However, we do not find any detectable ΔXCH4 trend if we consider either long‐term (2009–2019) or the second shorter period (2014–2019), suggesting local emission sources are dominating year to year fluctuation. From the source attribution analysis, we found both wetland and oil and gas sectors are controlling the CH<sub>4</sub> growth rate in western Canada, but the oil and gas sector is the dominant driver in NE and SK subdomains. We also found the satellite‐based average ΔXCH4 trend (15.43 ± 8.19%/yr) between 2009 and 2013 likely reflects a trend in oil and gas CH<sub>4</sub> emissions in AB and SK for the same period.