---
title: 'Satellite observations of atmospheric methane and their value for quantifying methane emissions'
author: 'Jacob, Daniel J. and Turner, Alexander J. and Maasakkers, Joannes D. and Sheng, Jianxiong and Sun, Kang and Liu, Xiong and Chance, Kelly and Aben, Ilse and McKeever, Jason and Frankenberg, Christian'
type: 'journal-article'
year: 2016
publication: 'Atmospheric Chemistry and Physics'
doi: '10.5194/acp-16-14371-2016'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. Methane is a greenhouse gas emitted by a range of natural and anthropogenic sources. Atmospheric methane has been measured continuously from space since 2003, and new instruments are planned for launch in the near future that will greatly expand the capabilities of space-based observations. We review the value of current, future, and proposed satellite observations to better quantify and understand methane emissions through inverse analyses, from the global scale down to the scale of point sources and in combination with suborbital (surface and aircraft) data. Current global observations from Greenhouse Gases Observing Satellite (GOSAT) are of high quality but have sparse spatial coverage. They can quantify methane emissions on a regional scale (100–1000 km) through multiyear averaging. The Tropospheric Monitoring Instrument (TROPOMI), to be launched in 2017, is expected to quantify daily emissions on the regional scale and will also effectively detect large point sources. A different observing strategy by GHGSat (launched in June 2016) is to target limited viewing domains with very fine pixel resolution in order to detect a wide range of methane point sources. Geostationary observation of methane, still in the proposal stage, will have the unique capability of mapping source regions with high resolution, detecting transient "super-emitter" point sources and resolving diurnal variation of emissions from sources such as wetlands and manure. Exploiting these rapidly expanding satellite measurement capabilities to quantify methane emissions requires a parallel effort to construct high-quality spatially and sectorally resolved emission inventories. Partnership between top-down inverse analyses of atmospheric data and bottom-up construction of emission inventories is crucial to better understanding methane emission processes and subsequently informing climate policy.