---
title: 'Towards accurate methane point-source quantification from high-resolution 2-D plume imagery'
author: 'Jongaramrungruang, Siraput and Frankenberg, Christian and Matheou, Georgios and Thorpe, Andrew K. and Thompson, David R. and Kuai, Le and Duren, Riley M.'
type: 'journal-article'
year: 2019
publication: 'Atmospheric Measurement Techniques'
doi: '10.5194/amt-12-6667-2019'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. Methane is the second most important anthropogenic greenhouse gas
in the Earth climate system but emission quantification of localized point
sources has been proven challenging, resulting in ambiguous regional budgets
and source category distributions. Although recent advancements in
airborne remote sensing instruments enable retrievals of methane
enhancements at an unprecedented resolution of 1–5 m at regional scales,
emission quantification of individual sources can be limited by the lack of
knowledge of local wind speed. Here, we developed an algorithm that can
estimate flux rates solely from mapped methane plumes, avoiding the need for
ancillary information on wind speed. The algorithm was trained on synthetic
measurements using large eddy simulations under a range of background wind
speeds of 1–10 m s−1 and source emission rates ranging from 10 to 1000 kg h−1. The surrogate measurements mimic plume mapping performed by the next-generation Airborne Visible/Infrared Imaging Spectrometer (AVIRIS-NG)
and provide an ensemble of 2-D snapshots of column methane enhancements at 5 m spatial resolution. We make use of the integrated total methane
enhancement in each plume, denoted as integrated methane enhancement (IME),
and investigate how this IME relates to the actual methane flux rate. Our
analysis shows that the IME corresponds to the flux rate nonlinearly and is
strongly dependent on the background wind speed over the plume. We
demonstrate that the plume width, defined based on the plume angular
distribution around its main axis, provides information on the associated
background wind speed. This allows us to invert source flux rate based
solely on the IME and the plume shape itself. On average, the error estimate
based on randomly generated plumes is approximately 30 % for an individual
estimate and less than 10 % for an aggregation of 30 plumes. A validation
against a natural gas controlled-release experiment agrees to within 32 %,
supporting the basis for the applicability of this technique to quantifying
point sources over large geographical areas in airborne field campaigns and
future space-based observations.