---
title: 'Mineral Luminescence Observed From Space'
author: 'Köhler, Philipp and Fischer, Woodward W. and Rossman, George R. and Grotzinger, John P. and Doughty, Russell and Wang, Yujie and Yin, Yi and Frankenberg, Christian'
type: 'journal-article'
year: 2021
publication: 'Geophysical Research Letters'
doi: '10.1029/2021gl095227'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

AbstractMethods developed to explore the luminescent properties of the moon facilitated the development of techniques to infer terrestrial solar‐induced chlorophyll fluorescence (SIF) from satellite instruments. While single SIF retrievals are inherently noisy, averaging many retrievals allows us to obtain highly accurate estimates. We analyzed several years of aggregated SIF data collected by the TROPOspheric Monitoring Instrument (TROPOMI) and the Orbiting Carbon Observatory‐2 (OCO‐2) over nonvegetated areas to explore the potential of SIF retrievals beyond the realm of photosynthesis. The fundamentally different retrievals at varying wavelengths in the near‐infrared reveal that about 10% of all barren surfaces are weakly luminescent, while a few areas luminesce strongly—amounts comparable to SIF from vegetation. By means of lithological maps, we attributed the strongest luminescence signals to exposed carbonate sedimentary rocks. Besides a detailed evaluation of the signal properties, we discussed implications for SIF data sets and other remote sensing products.