---
title: 'A physiological signal derived from sun-induced chlorophyll fluorescence quantifies crop physiological response to environmental stresses in the U.S. Corn Belt'
author: 'Kimm, Hyungsuk and Guan, Kaiyu and Jiang, Chongya and Miao, Guofang and Wu, Genghong and Suyker, Andrew E and Ainsworth, Elizabeth A and Bernacchi, Carl J and Montes, Christopher M and Berry, Joseph A and Yang, Xi and Frankenberg, Christian and Chen, Min and Köhler, Philipp'
type: 'journal-article'
year: 2021
publication: 'Environmental Research Letters'
doi: '10.1088/1748-9326/ac3b16'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract

Sun-induced chlorophyll fluorescence (SIF) measurements have shown unique potential for quantifying plant physiological stress. However, recent investigations found canopy structure and radiation largely control SIF, and physiological relevance of SIF remains yet to be fully understood. This study aims to evaluate whether the SIF-derived physiological signal improves quantification of crop responses to environmental stresses, by analyzing data at three different spatial scales within the U.S. Corn Belt, i.e. experiment plot, field, and regional scales, where ground-based portable, stationary and space-borne hyperspectral sensing systems are used, respectively. We found that, when controlling for variations in incoming radiation and canopy structure, crop SIF signals can be decomposed into non-physiological (i.e. canopy structure and radiation, 60% ∼ 82%) and physiological information (i.e. physiological SIF yield, Φ
F
, 17% ∼ 31%), which confirms the contribution of physiological variation to SIF. We further evaluated whether Φ
F
indicated plant responses under high-temperature and high vapor pressure deficit (VPD) stresses. The plot-scale data showed that Φ
F
responded to the proxy for physiological stress (partial correlation coefficient,
r
p
= 0.40,
p
< 0.001) while non-physiological signals of SIF did not respond (
p
> 0.1). The field-scale Φ
F
data showed water deficit stress from the comparison between irrigated and rainfed fields, and Φ
F
was positively correlated with canopy-scale stomatal conductance, a reliable indicator of plant physiological condition (correlation coefficient
r
= 0.60 and 0.56 for an irrigated and rainfed sites, respectively). The regional-scale data showed Φ
F
was more strongly correlated spatially with air temperature and VPD (
r
= 0.23 and 0.39) than SIF (
r
= 0.11 and 0.34) for the U.S. Corn Belt. The lines of evidence suggested that Φ
F
reflects crop physiological responses to environmental stresses with greater sensitivity to stress factors than SIF, and the stress quantification capability of Φ
F
is spatially scalable. Utilizing Φ
F
for physiological investigations will contribute to improve our understanding of vegetation responses to high-temperature and high-VPD stresses.