---
title: 'Investigating the usefulness of satellite-derived fluorescence data in inferring gross primary productivity within the carbon cycle data assimilation system'
author: 'Koffi, E. N. and Rayner, P. J. and Norton, A. J. and Frankenberg, C. and Scholze, M.'
type: 'journal-article'
year: 2015
publication: 'Biogeosciences'
doi: '10.5194/bg-12-4067-2015'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. Simulations of carbon fluxes with terrestrial biosphere models still exhibit significant uncertainties, in part due to the uncertainty in model parameter values. With the advent of satellite measurements of solar induced chlorophyll fluorescence (SIF), there exists a novel pathway for constraining simulated carbon fluxes and parameter values. We investigate the utility of SIF in constraining gross primary productivity (GPP). As a first test we assess whether SIF simulations are sensitive to important parameters in a biosphere model. SIF measurements at the wavelength of 755 nm are simulated by the Carbon-Cycle Data Assimilation System (CCDAS) which has been augmented by the fluorescence component of the Soil Canopy Observation, Photochemistry and Energy fluxes (SCOPE) model.  Idealized sensitivity tests of the SCOPE model stand-alone indicate strong sensitivity of GPP to the carboxylation capacity (Vcmax) and of SIF to the chlorophyll AB content (Cab) and incoming short wave radiation. Low sensitivity is found for SIF to Vcmax, however the relationship is subtle, with increased sensitivity under high radiation conditions and lower Vcmax ranges.  CCDAS simulates well the patterns of satellite-measured SIF suggesting the combined model is capable of ingesting the data. CCDAS supports the idealized sensitivity tests of SCOPE, with SIF exhibiting sensitivity to Cab and incoming radiation, both of which are treated as perfectly known in previous CCDAS versions. These results demonstrate the need for careful consideration of Cab and incoming radiation when interpreting SIF and the limitations of utilizing SIF to constrain Vcmax in the present set-up in the CCDAS system.