---
title: 'Space‐based observations of megacity carbon dioxide'
author: 'Kort, Eric A. and Frankenberg, Christian and Miller, Charles E. and Oda, Tom'
type: 'journal-article'
year: 2012
publication: 'Geophysical Research Letters'
doi: '10.1029/2012gl052738'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Urban areas now house more than half the world's population, and are estimated to contribute over 70% of global energy‐related CO<sub>2</sub>. Many cities have emission reduction policies in place, but lack objective, observation‐based methods for verifying their outcomes. Here we demonstrate the potential of satellite‐borne instruments to provide accurate global monitoring of megacity CO<sub>2</sub> emissions using GOSAT observations of column averaged CO<sub>2</sub> dry air mole fraction (XCO<sub>2</sub>) collected over Los Angeles and Mumbai. By differencing observations over the megacity with those in nearby background, we observe robust, statistically significant XCO<sub>2</sub> enhancements of 3.2 ± 1.5 ppm for Los Angeles and 2.4 ± 1.2 ppm for Mumbai, and find these enhancements can be exploited to track anthropogenic emission trends over time. We estimate that XCO<sub>2</sub> changes as small as 0.7 ppm in Los Angeles, corresponding to a 22% change in emissions, could be detected with GOSAT at the 95% confidence level.