---
title: 'Consistent evaluation of ACOS-GOSAT, BESD-SCIAMACHY, CarbonTracker, and MACC  through comparisons to TCCON'
author: 'Kulawik, Susan and Wunch, Debra and O''Dell, Christopher and Frankenberg, Christian and Reuter, Maximilian and Oda, Tomohiro and Chevallier, Frederic and Sherlock, Vanessa and Buchwitz, Michael and Osterman, Greg and Miller, Charles E. and Wennberg, Paul O. and Griffith, David and Morino, Isamu and Dubey, Manvendra K. and Deutscher, Nicholas M. and Notholt, Justus and Hase, Frank and Warneke, Thorsten and Sussmann, Ralf and Robinson, John and Strong, Kimberly and Schneider, Matthias and De Mazière, Martine and Shiomi, Kei and Feist, Dietrich G. and Iraci, Laura T. and Wolf, Joyce'
type: 'journal-article'
year: 2016
publication: 'Atmospheric Measurement Techniques'
doi: '10.5194/amt-9-683-2016'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. Consistent validation of satellite CO<sub>2</sub> estimates is a prerequisite for using multiple satellite CO<sub>2</sub> measurements for joint flux inversion, and for establishing an accurate long-term atmospheric CO<sub>2</sub> data record. Harmonizing satellite CO<sub>2</sub> measurements is particularly important since the differences in instruments, observing geometries, sampling strategies, etc. imbue different measurement characteristics in the various satellite CO<sub>2</sub> data products. We focus on validating model and satellite observation attributes that impact flux estimates and CO<sub>2</sub> assimilation, including accurate error estimates, correlated and random errors, overall biases, biases by season and latitude, the impact of coincidence criteria, validation of seasonal cycle phase and amplitude, yearly growth, and daily variability. We evaluate dry-air mole fraction (XCO<sub>2</sub>) for Greenhouse gases Observing SATellite (GOSAT) (Atmospheric CO<sub>2</sub> Observations from Space, ACOS b3.5) and SCanning Imaging Absorption spectroMeter for Atmospheric CHartographY (SCIAMACHY) (Bremen Optimal Estimation DOAS, BESD v2.00.08) as well as the CarbonTracker (CT<sub>2013</sub>) simulated CO<sub>2</sub> mole fraction fields and the Monitoring Atmospheric Composition and Climate (MACC) CO<sub>2</sub> inversion system (v13.1) and compare these to Total Carbon Column Observing Network (TCCON) observations (GGG<sub>2012</sub>/2014). We find standard deviations of 0.9, 0.9, 1.7, and 2.1 ppm vs. TCCON for CT<sub>2013</sub>, MACC, GOSAT, and SCIAMACHY, respectively, with the single observation errors 1.9 and 0.9 times the predicted errors for GOSAT and SCIAMACHY, respectively. We quantify how satellite error drops with data averaging by interpreting according to error2 = a2 + b2/n (with n being the number of observations averaged, a the systematic (correlated) errors, and b the random (uncorrelated) errors). a and b are estimated by satellites, coincidence criteria, and hemisphere. Biases at individual stations have year-to-year variability of  ∼  0.3 ppm, with biases larger than the TCCON-predicted bias uncertainty of 0.4 ppm at many stations. We find that GOSAT and CT<sub>2013</sub> underpredict the seasonal cycle amplitude in the Northern Hemisphere (NH) between 46 and 53° N, MACC overpredicts between 26 and 37° N, and CT<sub>2013</sub> underpredicts the seasonal cycle amplitude in the Southern Hemisphere (SH). The seasonal cycle phase indicates whether a data set or model lags another data set in time. We find that the GOSAT measurements improve the seasonal cycle phase substantially over the prior while SCIAMACHY measurements improve the phase significantly for just two of seven sites. The models reproduce the measured seasonal cycle phase well except for at Lauder_125HR (CT<sub>2013</sub>) and Darwin (MACC). We compare the variability within 1 day between TCCON and models in JJA; there is correlation between 0.2 and 0.8 in the NH, with models showing 10–50 % the variability of TCCON at different stations and CT<sub>2013</sub> showing more variability than MACC. This paper highlights findings that provide inputs to estimate flux errors in model assimilations, and places where models and satellites need further investigation, e.g., the SH for models and 45–67° N for GOSAT and CT<sub>2013</sub>.