---
title: 'Observational Constraints on the Response of High‐Latitude Northern Forests to Warming'
author: 'Liu, Junjie and Wennberg, Paul O. and Parazoo, Nicholas C. and Yin, Yi and Frankenberg, Christian'
type: 'journal-article'
year: 2020
publication: 'AGU Advances'
doi: '10.1029/2020av000228'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

AbstractSince the 1960s, carbon cycling in the high‐latitude northern forest (HLNF) has experienced dramatic changes: Most of the forest is greening and net carbon uptake from the atmosphere has increased. During the same time period, the CO<sub>2</sub> seasonal cycle amplitude (SCA) has increased by ~50% or more. Disentangling complex processes that drive these changes has been challenging. In this study, we substitute spatial sensitivity to temperature for time to quantify the impact of temperature increase on gross primary production (GPP), total ecosystem respiration (TER), the fraction of Photosynthetic Active Radiation (fPAR), and the resulted contribution of these changes in amplifying the CO<sub>2</sub> SCA over the HLNF since 1960s. We use the spatial heterogeneity of GPP inferred from solar‐induced chlorophyll Fluorescence in combination with net ecosystem exchange (NEE) inferred from column CO<sub>2</sub> observations made between 2015 and 2017 from NASA's Orbiting Carbon Observatory‐2. We find that three quarters of the spatial variations in GPP can be explained by the spatial variation in the growing season mean temperature (GSMT). The long term hindcast captures both the magnitude and spatial variability of the trends in observed fPAR. We estimate that between 1960 and 2010, the increase in GSMT enhanced both GPP and the SCA of NEE by ~20%. The calculated enhancement of NEE due to increase in GSMT contributes 56–72% of the trend in the CO<sub>2</sub> SCA at high latitudes, much larger than simulations by most biogeochemical models.