---
title: 'Non-steady-state stomatal conductance modeling and its implications: from leaf to ecosystem'
author: 'Liu, Ke and Wang, Yujie and Magney, Troy S. and Frankenberg, Christian'
type: 'journal-article'
year: 2024
publication: 'Biogeosciences'
doi: '10.5194/bg-21-1501-2024'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. Accurate and efficient modeling of stomatal conductance (gs) has been a key challenge in vegetation models across scales. Current practice of most land surface models (LSMs) assumes steady-state gs and predicts stomatal responses to environmental cues as immediate jumps between stationary regimes. However, the response of stomata can be orders of magnitude slower than that of photosynthesis and often cannot reach a steady state before the next model time step, even on half-hourly timescales. Here, we implemented a simple dynamic gs model in the vegetation module of an LSM developed within the Climate Modeling Alliance and investigated the potential biases caused by the steady-state assumption from leaf to canopy scales. In comparison with steady-state models, the dynamic model better predicted the coupled temporal response of photosynthesis and stomatal conductance to changes in light intensity using leaf measurements. In ecosystem flux simulations, while the impact of gs hysteresis response may not be substantial in terms of monthly integrated fluxes, our results highlight the importance of considering this effect when quantifying fluxes in the mornings and evenings, as well as interpreting diurnal hysteresis patterns observed in ecosystem fluxes. Simulations also indicate that the biases in the integrated fluxes are more significant when stomata exhibit different speeds for opening and closure. Furthermore, prognostic modeling can bypass the A-Ci iterations required for steady-state simulations and can be robustly run with comparable computational costs. Overall, our study demonstrates the implications of dynamic gs modeling for improving the accuracy and efficiency of LSMs and for advancing our understanding of plant–environment interactions.