---
title: 'Application of SCIAMACHY and MOPITT CO total column measurements to evaluate model results over biomass burning regions and Eastern China'
author: 'Liu, C. and Beirle, S. and Butler, T. and Liu, J. and Hoor, P. and Jöckel, P. and Penning de Vries, M. and Pozzer, A. and Frankenberg, C. and Lawrence, M. G. and Lelieveld, J. and Platt, U. and Wagner, T.'
type: 'journal-article'
year: 2011
publication: 'Atmospheric Chemistry and Physics'
doi: '10.5194/acp-11-6083-2011'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. We developed a new CO vertical column density product from near IR observations of the SCIAMACHY instrument onboard ENVISAT. For the correction of a temporally and spatially variable offset of the CO vertical column densities we apply a normalisation procedure based on coincident MOPITT (version 4) observations over the oceans. The resulting normalised SCIAMACHY CO data is well suited for the investigation of the CO distribution over continents, where important emission sources are located. We use only SCIAMACHY observations for effective cloud fractions below 20 %. Since the remaining effects of clouds can still be large (up to 100 %), we applied a cloud correction scheme which explicitly considers the cloud fraction, cloud top height and surface albedo of individual observations. The normalisation procedure using MOPITT data and the cloud correction substantially improve the agreement with independent data sets. We compared our new SCIAMACHY CO data set, and also observations from the MOPITT instrument, to the results from three global atmospheric chemistry models (MATCH, EMAC at low and high resolution, and GEOS-Chem); the focus of this comparison is on regions with strong CO emissions (from biomass burning or anthropogenic sources). The comparison indicates that over most of these regions the seasonal cycle is generally captured well but the simulated CO vertical column densities are systematically smaller than those from the satellite observations, in particular with respect to SCIAMACHY observations. Because SCIAMACHY is more sensitive to the lowest part of the atmosphere compared to MOPITT, this indicates that especially close to the surface the model simulations systematically underestimate the true atmospheric CO concentrations, probably caused by an underestimation of CO emissions by current emission inventories. For some biomass burning regions, however, such as Central Africa in July–August, model results are also found to be higher than the satellite observations.