---
title: 'Tracking subtle seasonal shifts in pigment composition with hyperspectral reflectance in a temperate evergreen forest'
author: 'Magney, Troy S and Brissette, Logan E G and Pierrat, Zoe Amie and Logan, Barry and Reblin, Jaret and Nelson, Sara and Stutz, Jochen and Frankenberg, Christian and Bowling, David R and Wong, Christopher Y S'
type: 'journal-article'
year: 2025
publication: 'Tree Physiology'
doi: '10.1093/treephys/tpaf108'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract
Pigment dynamics in temperate evergreen forests remain poorly characterized, despite their year-round photosynthetic activity and importance for carbon cycling. Developing rapid, nondestructive methods to estimate pigment composition enables high-throughput assessment of plant acclimation states. In this study, we investigate the seasonality of eight chlorophyll and carotenoid pigments and hyperspectral reflectance data collected at both the needle (400–2400 nm) and canopy (420–850 nm) scales in longleaf pine (Pinus palustris Mill.) at the Ordway Swisher Biological Station in north-central Florida, USA. Needle spectra were obtained at three distinct times throughout the year, while tower-based spectra were collected continuously over a 9-month period. Seasonal trends in photoprotective pigments (e.g. lutein and xanthophylls) and photosynthetic pigments (e.g. chlorophylls) aligned closely with seasonal changes in photosynthetically active radiation and gross primary productivity. To track inter-tree and seasonal variability in pigment pools with hyperspectral reflectance data, we used correlation analyses and ridge regression models. Ridge regression models using the full hyperspectral range outperformed predictions using standard linear regression with specific wavelengths in a normalized difference index fashion. Ridge regression successfully predicted all pigment pools (R<sub>2</sub> &gt; 0.5) with comparable accuracy at both the needle and canopy scales. The models performed best for lutein, neoxanthin, antheraxanthin, and chlorophyll a and b—which had greater inter-tree and seasonal variation—and achieved moderate accuracy for violaxanthin, alpha-carotene and beta-carotene. These results provide a foundation for scaling biochemical traits from ground-based sensors to airborne and satellite platforms, particularly in ecosystems with subtle changes in pigment dynamics.