---
title: 'Connecting active to passive fluorescence with photosynthesis: a method for evaluating remote sensing measurements of Chl fluorescence'
author: 'Magney, Troy S. and Frankenberg, Christian and Fisher, Joshua B. and Sun, Ying and North, Gretchen B. and Davis, Thomas S. and Kornfeld, Ari and Siebke, Katharina'
type: 'journal-article'
year: 2017
publication: 'New Phytologist'
doi: '10.1111/nph.14662'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Summary



Recent advances in the retrieval of Chl fluorescence from space using passive methods (solar‐induced Chl fluorescence, SIF) promise improved mapping of plant photosynthesis globally. However, unresolved issues related to the spatial, spectral, and temporal dynamics of vegetation fluorescence complicate our ability to interpret SIF measurements.


We developed an instrument to measure leaf‐level gas exchange simultaneously with pulse‐amplitude modulation (PAM) and spectrally resolved fluorescence over the same field of view – allowing us to investigate the relationships between active and passive fluorescence with photosynthesis.



Strongly correlated, slope‐dependent relationships were observed between measured spectra across all wavelengths (
F

λ

, 670–850 nm) and PAM fluorescence parameters under a range of actinic light intensities (steady‐state fluorescence yields,
F
t
) and saturation pulses (maximal fluorescence yields,
F
m
). Our results suggest that this method can accurately reproduce the full Chl emission spectra – capturing the spectral dynamics associated with changes in the yields of fluorescence, photochemical (ΦPSII), and nonphotochemical quenching (NPQ).



We discuss how this method may establish a link between photosynthetic capacity and the mechanistic drivers of wavelength‐specific fluorescence emission during changes in environmental conditions (light, temperature, humidity). Our emphasis is on future research directions linking spectral fluorescence to photosynthesis, ΦPSII, and NPQ.