---
title: 'Spatial covariation between solar-induced fluorescence and vegetation indices from Arctic-Boreal landscapes'
author: 'Maguire, Andrew J and Eitel, Jan U H and Magney, Troy S and Frankenberg, Christian and Köhler, Philipp and Orcutt, Erica L and Parazoo, Nicholas C and Pavlick, Ryan and Pierrat, Zoe A'
type: 'journal-article'
year: 2021
publication: 'Environmental Research Letters'
doi: '10.1088/1748-9326/ac188a'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract
The Arctic-Boreal Zone (ABZ) is characterized by spatially heterogeneous vegetation composition and structure, leading to challenges for inferring patterns in vegetation productivity. A mechanistic understanding of the patterns and processes underlying spectral remote sensing observations is necessary to overcome these challenges. Solar-induced chlorophyll fluorescence (SIF), near-infrared reflectance of vegetation (NIRv), and chlorophyll/carotenoid index (CCI) show promise for tracking productivity and disentangling links to the activity and distribution of chlorophyll at coarse spatial scales (e.g. 0.5°), but their effectiveness for studying mixed landscapes characteristic of the ABZ remains unclear. Here, we use airborne observations collected during NASA’s Arctic-Boreal Vulnerability Experiment to examine the spatial covariation between SIF, NIRv, and CCI at a scale (30 m) commensurate with the best available landcover products across interior Alaska. Additionally, we compare relationships among SIF and vegetation indices from spaceborne observations (TROPOMI and MODIS) resampled to a 0.01° (∼1000 m) scale. We find that the strength of the SIF-NIRv linear relationship degrades when compared from the spaceborne to the airborne scale (R
2 = 0.50 vs. 0.26) as does the strength of the SIF-CCI linear relationship (R
2 = 0.30 vs. 0.18), though the degradation of SIF-CCI is less severe than that of SIF-NIRv. The relationship of SIF with either vegetation index is strongly dependent on landcover class at both airborne and spaceborne scales. We provide context for how further work could leverage SIF with reflectance indices measurable from a variety of platforms to improve mapping of vegetation dynamics in this ecoregion.