---
title: 'Comparison of CH<sub>4</sub> inversions based on 15 months of GOSAT and SCIAMACHY observations'
author: 'Monteil, Guillaume and Houweling, Sander and Butz, André and Guerlet, Sandrine and Schepers, Dinand and Hasekamp, Otto and Frankenberg, Christian and Scheepmaker, Remco and Aben, Ilse and Röckmann, Thomas'
type: 'journal-article'
year: 2013
publication: 'Journal of Geophysical Research: Atmospheres'
doi: '10.1002/2013jd019760'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Over the past decade the development of Scanning Imaging Absorption Spectrometer for Atmospheric Chartography (SCIAMACHY) retrievals has increased the interest in the use of satellite measurements for studying the global sources and sinks of methane. Meanwhile, measurements are becoming available from the more advanced Greenhouse Gases Observing Satellite (GOSAT). The aim of this study is to investigate the application of GOSAT retrievals to inverse modeling, for which we make use of the TM<sub>5</sub>‐4DVAR inverse modeling framework. Inverse modeling calculations are performed using data from two different retrieval approaches: a full physics and a lightpath proxy ratio method. The performance of these inversions is analyzed in comparison with inversions using SCIAMACHY retrievals and measurements from the National Oceanic and Atmospheric Administration‐Earth System Research Laboratory flask‐sampling network. In addition, we compare the inversion results against independent surface, aircraft, and total‐column measurements. Inversions with GOSAT data show good agreement with surface measurements, whereas for SCIAMACHY a similar performance can only be achieved after significant bias corrections. Some inconsistencies between surface and total‐column methane remain in the Southern Hemisphere. However, comparisons with measurements from the Total Column Carbon Observing Network in situ Fourier transform spectrometer network indicate that those may be caused by systematic model errors rather than by shortcomings in the GOSAT retrievals. The global patterns of methane emissions derived from SCIAMACHY (with bias correction) and GOSAT retrievals are in remarkable agreement and allow an increased resolution of tropical emissions. The satellite inversions increase tropical methane emission by 30 to 60 TgCH<sub>4</sub>/yr compared to initial a priori estimates, partly counterbalanced by reductions in emissions at midlatitudes to high latitudes.