---
title: 'Wide discrepancies in the magnitude and direction of modeled solar-induced chlorophyll fluorescence in response to light conditions'
author: 'Parazoo, Nicholas C. and Magney, Troy and Norton, Alex and Raczka, Brett and Bacour, Cédric and Maignan, Fabienne and Baker, Ian and Zhang, Yongguang and Qiu, Bo and Shi, Mingjie and MacBean, Natasha and Bowling, Dave R. and Burns, Sean P. and Blanken, Peter D. and Stutz, Jochen and Grossmann, Katja and Frankenberg, Christian'
type: 'journal-article'
year: 2020
publication: 'Biogeosciences'
doi: '10.5194/bg-17-3733-2020'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. Recent successes in passive remote sensing of far-red solar-induced chlorophyll fluorescence (SIF) have spurred the development and integration of
canopy-level fluorescence models in global terrestrial biosphere models (TBMs) for climate and carbon cycle research. The interaction of fluorescence
with photochemistry at the leaf and canopy scales provides opportunities to diagnose and constrain model simulations of photosynthesis and related
processes, through direct comparison to and assimilation of tower, airborne, and satellite data. TBMs describe key processes related to the absorption of
sunlight, leaf-level fluorescence emission, scattering, and reabsorption throughout the canopy. Here, we analyze simulations from an ensemble of
process-based TBM–SIF models (SiB<sub>3</sub> – Simple Biosphere Model, SiB<sub>4</sub>, CLM<sub>4</sub>.5 – Community Land Model, CLM<sub>5</sub>.0, BETHY – Biosphere Energy Transfer Hydrology, ORCHIDEE – Organizing Carbon and Hydrology In Dynamic Ecosystems, and BEPS – Boreal Ecosystems Productivity Simulator) and the SCOPE (Soil Canopy Observation Photosynthesis Energy) canopy radiation and vegetation model at a subalpine
evergreen needleleaf forest near Niwot Ridge, Colorado. These models are forced with local meteorology and analyzed against tower-based continuous
far-red SIF and gross-primary-productivity-partitioned (GPP) eddy covariance data at diurnal and synoptic scales during the growing season
(July–August 2017). Our primary objective is to summarize the site-level state of the art in TBM–SIF modeling over a relatively short time period
(summer) when light, canopy structure, and pigments are similar, setting the stage for regional- to global-scale analyses. We find that these models
are generally well constrained in simulating photosynthetic yield but show strongly divergent patterns in the simulation of absorbed photosynthetic
active radiation (PAR), absolute GPP and fluorescence, quantum yields, and light response at the leaf and canopy scales. This study highlights the need for
mechanistic modeling of nonphotochemical quenching in stressed and unstressed environments and improved the representation of light absorption (APAR),
distribution of light across sunlit and shaded leaves, and radiative transfer from the leaf to the canopy scale.