---
title: 'Influence of ENSO and the NAO on terrestrial carbon uptake in the Texas‐northern Mexico region'
author: 'Parazoo, Nicholas C. and Barnes, Elizabeth and Worden, John and Harper, Anna B. and Bowman, Kevin B. and Frankenberg, Christian and Wolf, Sebastian and Litvak, Marcy and Keenan, Trevor F.'
type: 'journal-article'
year: 2015
publication: 'Global Biogeochemical Cycles'
doi: '10.1002/2015gb005125'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

AbstractClimate extremes such as drought and heat waves can cause substantial reductions in terrestrial carbon uptake. Advancing projections of the carbon uptake response to future climate extremes depends on (1) identifying mechanistic links between the carbon cycle and atmospheric drivers, (2) detecting and attributing uptake changes, and (3) evaluating models of land response and atmospheric forcing. Here, we combine model simulations, remote sensing products, and ground observations to investigate the impact of climate variability on carbon uptake in the Texas‐northern Mexico region. Specifically, we (1) examine the relationship between drought, carbon uptake, and variability of El Niño–Southern Oscillation (ENSO) and the North Atlantic Oscillation (NAO) using the Joint UK Land‐Environment Simulator (JULES) biosphere simulations from 1950–2012, (2) quantify changes in carbon uptake during record drought conditions in 2011, and (3) evaluate JULES carbon uptake and soil moisture in 2011 using observations from remote sensing and a network of flux towers in the region. Long‐term simulations reveal systematic decreases in regional‐scale carbon uptake during negative phases of ENSO and NAO, including amplified reductions of gross primary production (GPP) (−0.42 ± 0.18 Pg C yr−1) and net ecosystem production (NEP) (−0.14 ± 0.11 Pg C yr−1) during strong La Niña years. The 2011 megadrought caused some of the largest declines of GPP (−0.50 Pg C yr−1) and NEP (−0.23 Pg C yr−1) in our simulations. In 2011, consistent declines were found in observations, including high correlation of GPP and surface soil moisture (r = 0.82 ± 0.23, p = 0.012) in remote sensing‐based products. These results suggest a large‐scale response of carbon uptake to ENSO and NAO, and highlight a need to improve model predictions of ENSO and NAO in order to improve predictions of future impacts on the carbon cycle and the associated feedbacks to climate change.