---
title: 'Interpreting seasonal changes in the carbon balance of southern Amazonia using measurements of XCO<sub>2</sub> and chlorophyll fluorescence from GOSAT'
author: 'Parazoo, Nicholas C. and Bowman, Kevin and Frankenberg, Christian and Lee, Jung‐Eun and Fisher, Joshua B. and Worden, John and Jones, Dylan B. A. and Berry, Joseph and Collatz, G. James and Baker, Ian T. and Jung, Martin and Liu, Junjie and Osterman, Gregory and O''Dell, Chris and Sparks, Athena and Butz, Andre and Guerlet, Sandrine and Yoshida, Yukio and Chen, Huilin and Gerbig, Christoph'
type: 'journal-article'
year: 2013
publication: 'Geophysical Research Letters'
doi: '10.1002/grl.50452'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Amazon forests exert a major influence on the global carbon cycle, but quantifying the impact is complicated by diverse landscapes and sparse data. Here we examine seasonal carbon balance in southern Amazonia using new measurements of column‐averaged dry air mole fraction of CO<sub>2</sub> (XCO<sub>2</sub>) and solar induced chlorophyll fluorescence (SIF) from the Greenhouse Gases Observing Satellite (GOSAT) from July 2009 to December 2010. SIF, which reflects gross primary production (GPP), is used to disentangle the photosynthetic component of land‐atmosphere carbon exchange. We find that tropical transitional forests in southern Amazonia exhibit a pattern of low XCO<sub>2</sub> during the wet season and high XCO<sub>2</sub> in the dry season that is robust to retrieval methodology and with seasonal amplitude double that of cerrado ecosystems to the east (4 ppm versus 2 ppm), including enhanced dilution of 2.5 ppm in the wet season. Concomitant measurements of SIF, which are inversely correlated with XCO<sub>2</sub> in southern Amazonia (r = −0.53, p < 0.001), indicate that the enhanced variability is driven by seasonal changes in GPP due to coupling of strong vertical mixing with seasonal changes in underlying carbon exchange. This finding is supported by forward simulations of the Goddard Chemistry Transport Model (GEOS‐Chem) which show that local carbon uptake in the wet season and loss in the dry season due to emissions by ecosystem respiration and biomass burning produces best agreement with observed XCO<sub>2</sub>. We conclude that GOSAT provides critical measurements of carbon exchange in southern Amazonia, but more samples are needed to examine moist Amazon forests farther north.