---
title: 'First ground-based FTIR observations of methane in the inner tropics over several years'
author: 'Petersen, A. K. and Warneke, T. and Frankenberg, C. and Bergamaschi, P. and Gerbig, C. and Notholt, J. and Buchwitz, M. and Schneising, O. and Schrems, O.'
type: 'journal-article'
year: 2010
publication: 'Atmospheric Chemistry and Physics'
doi: '10.5194/acp-10-7231-2010'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. Total column concentrations of methane have been retrieved from ground-based solar absorption FTIR spectra in the near-infrared recorded in Paramaribo (Suriname). The methane FTIR observations are compared with TM<sub>5</sub> model simulations and satellite observations from SCIAMACHY, and represent the first validation of SCIAMACHY retrievals in the inner tropics using ground-based remote sensing techniques. Apart from local biomass burning features, our methane FTIR observations agree well with TM<sub>5</sub> model simulations. The comparison of the direct measured CH<sub>4</sub>/CO<sub>2</sub> ratios by FTIR and satellite reveals that the satellite can hardly detect methane emissions of tropical biomass burning due to the used retrieval method.