---
title: 'Process‐evaluation of tropospheric humidity simulated by general circulation models using water vapor isotopologues: 1. Comparison between models and observations'
author: 'Risi, Camille and Noone, David and Worden, John and Frankenberg, Christian and Stiller, Gabriele and Kiefer, Michael and Funke, Bernd and Walker, Kaley and Bernath, Peter and Schneider, Matthias and Wunch, Debra and Sherlock, Vanessa and Deutscher, Nicholas and Griffith, David and Wennberg, Paul O. and Strong, Kimberly and Smale, Dan and Mahieu, Emmanuel and Barthlott, Sabine and Hase, Frank and García, Omaira and Notholt, Justus and Warneke, Thorsten and Toon, Geoffrey and Sayres, David and Bony, Sandrine and Lee, Jeonghoon and Brown, Derek and Uemura, Ryu and Sturm, Christophe'
type: 'journal-article'
year: 2012
publication: 'Journal of Geophysical Research: Atmospheres'
doi: '10.1029/2011jd016621'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

The goal of this study is to determine how H<sub>2</sub>O and HDO measurements in water vapor can be used to detect and diagnose biases in the representation of processes controlling tropospheric humidity in atmospheric general circulation models (GCMs). We analyze a large number of isotopic data sets (four satellite, sixteen ground‐based remote‐sensing, five surface in situ and three aircraft data sets) that are sensitive to different altitudes throughout the free troposphere. Despite significant differences between data sets, we identify some observed HDO/H<sub>2</sub>O characteristics that are robust across data sets and that can be used to evaluate models. We evaluate the isotopic GCM LMDZ, accounting for the effects of spatiotemporal sampling and instrument sensitivity. We find that LMDZ reproduces the spatial patterns in the lower and mid troposphere remarkably well. However, it underestimates the amplitude of seasonal variations in isotopic composition at all levels in the subtropics and in midlatitudes, and this bias is consistent across all data sets. LMDZ also underestimates the observed meridional isotopic gradient and the contrast between dry and convective tropical regions compared to satellite data sets. Comparison with six other isotope‐enabled GCMs from the SWING<sub>2</sub> project shows that biases exhibited by LMDZ are common to all models. The SWING<sub>2</sub> GCMs show a very large spread in isotopic behavior that is not obviously related to that of humidity, suggesting water vapor isotopic measurements could be used to expose model shortcomings. In a companion paper, the isotopic differences between models are interpreted in terms of biases in the representation of processes controlling humidity.