---
title: 'Role of continental recycling in intraseasonal variations of continental moisture as deduced from model simulations and water vapor isotopic measurements'
author: 'Risi, Camille and Noone, David and Frankenberg, Christian and Worden, John'
type: 'journal-article'
year: 2013
publication: 'Water Resources Research'
doi: '10.1002/wrcr.20312'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Climate models suggest an important role for land‐atmosphere feedbacks on climate, but exhibit a large dispersion in the simulation of this role. We focus here on the role of continental recycling in the intraseasonal variability of continental moisture, and we explore the possibility of using water isotopic measurements to observationally constrain this role. Based on water tagging, we design a diagnostic, named D<sub>1</sub>, to estimate the role of continental recycling on the intraseasonal variability of continental moisture simulated by the general circulation model LMDZ. In coastal regions, the intraseasonal variability of continental moisture is mainly driven by the variability in oceanic moisture convergence. More inland, the role of continental recycling becomes important. The simulation of this role is sensitive to model parameters modulating evapotranspiration. Then we show that δD in the low‐level water vapor is a good tracer for continental recycling, due to the enriched signature of transpiration. Over tropical land regions, the intraseasonal relationship between δD and precipitable water, named D1_iso, is a good observational proxy for D<sub>1</sub>. We test the possibility of using D1_iso for model evaluation using two satellite data sets: GOSAT and TES. LMDZ captures well the spatial patterns of D1_iso, but underestimates its values. However, a more accurate description of how atmospheric processes affect the isotopic composition of water vapor is necessary before concluding with certitude that LMDZ underestimates the role of continental recycling.