---
title: 'Impact of Raman Scattering on SIF Retrievals From Hyperspectral Satellite Observations'
author: 'Sanghavi, Suniti and Frankenberg, Christian and Nelson, Robert R. and O’Dell, Christopher W. and Rosenberg, Robert and Joiner, Joanna'
type: 'journal-article'
year: 2025
publication: 'Geophysical Research Letters'
doi: '10.1029/2024gl112777'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract
Solar‐induced chlorophyll fluorescence (SIF) retrieved from spaceborne measurements is widely used as an indicator of vegetation activity. However, this weak emission can be confused with the inelastic scattering component of sunlight that lacks distinctive Fraunhofer lines. Through high‐fidelity radiative transfer simulations of nadir‐mode observations near the  A‐band, we show that this signal can cause artificially high SIF estimates–reaching up to 0.35  over vegetation‐free regions like the Sahara, Greenland, and Antarctica. Current “zero‐level offset” corrections, originally intended to address instrument errors, partially remove these erroneous signals but leave significant residual biases (0.15 ) that correlate with surface brightness, elevation, and viewing geometry. We introduce a lookup table approach based on physical simulations to directly estimate and subtract inelastic scattering, which substantially improves SIF retrieval accuracy. Correcting the inelastic scattering effect refines the interpretation of global SIF applications–ranging from agricultural monitoring to assessments of ecosystem health and the carbon cycle.