---
title: 'The global methane budget 2000–2012'
author: 'Saunois, Marielle and Bousquet, Philippe and Poulter, Ben and Peregon, Anna and Ciais, Philippe and Canadell, Josep G. and Dlugokencky, Edward J. and Etiope, Giuseppe and Bastviken, David and Houweling, Sander and Janssens-Maenhout, Greet and Tubiello, Francesco N. and Castaldi, Simona and Jackson, Robert B. and Alexe, Mihai and Arora, Vivek K. and Beerling, David J. and Bergamaschi, Peter and Blake, Donald R. and Brailsford, Gordon and Brovkin, Victor and Bruhwiler, Lori and Crevoisier, Cyril and Crill, Patrick and Covey, Kristofer and Curry, Charles and Frankenberg, Christian and Gedney, Nicola and Höglund-Isaksson, Lena and Ishizawa, Misa and Ito, Akihiko and Joos, Fortunat and Kim, Heon-Sook and Kleinen, Thomas and Krummel, Paul and Lamarque, Jean-François and Langenfelds, Ray and Locatelli, Robin and Machida, Toshinobu and Maksyutov, Shamil and McDonald, Kyle C. and Marshall, Julia and Melton, Joe R. and Morino, Isamu and Naik, Vaishali and O''Doherty, Simon and Parmentier, Frans-Jan W. and Patra, Prabir K. and Peng, Changhui and Peng, Shushi and Peters, Glen P. and Pison, Isabelle and Prigent, Catherine and Prinn, Ronald and Ramonet, Michel and Riley, William J. and Saito, Makoto and Santini, Monia and Schroeder, Ronny and Simpson, Isobel J. and Spahni, Renato and Steele, Paul and Takizawa, Atsushi and Thornton, Brett F. and Tian, Hanqin and Tohjima, Yasunori and Viovy, Nicolas and Voulgarakis, Apostolos and van Weele, Michiel and van der Werf, Guido R. and Weiss, Ray and Wiedinmyer, Christine and Wilton, David J. and Wiltshire, Andy and Worthy, Doug and Wunch, Debra and Xu, Xiyan and Yoshida, Yukio and Zhang, Bowen and Zhang, Zhen and Zhu, Qiuan'
type: 'journal-article'
year: 2016
publication: 'Earth System Science Data'
doi: '10.5194/essd-8-697-2016'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. The global methane (CH<sub>4</sub>) budget is becoming an increasingly important component for managing realistic pathways to mitigate climate change. This relevance, due to a shorter atmospheric lifetime and a stronger warming potential than carbon dioxide, is challenged by the still unexplained changes of atmospheric CH<sub>4</sub> over the past decade. Emissions and concentrations of CH<sub>4</sub> are continuing to increase, making CH<sub>4</sub> the second most important human-induced greenhouse gas after carbon dioxide. Two major difficulties in reducing uncertainties come from the large variety of diffusive CH<sub>4</sub> sources that overlap geographically, and from the destruction of CH<sub>4</sub> by the very short-lived hydroxyl radical (OH). To address these difficulties, we have established a consortium of multi-disciplinary scientists under the umbrella of the Global Carbon Project to synthesize and stimulate research on the methane cycle, and producing regular (∼ biennial) updates of the global methane budget. This consortium includes atmospheric physicists and chemists, biogeochemists of surface and marine emissions, and socio-economists who study anthropogenic emissions. Following Kirschke et al. (2013), we propose here the first version of a living review paper that integrates results of top-down studies (exploiting atmospheric observations within an atmospheric inverse-modelling framework) and bottom-up models, inventories and data-driven approaches (including process-based models for estimating land surface emissions and atmospheric chemistry, and inventories for anthropogenic emissions, data-driven extrapolations).  For the 2003–2012 decade, global methane emissions are estimated by top-down inversions at 558 Tg CH<sub>4</sub> yr−1, range 540–568. About 60 % of global emissions are anthropogenic (range 50–65 %). Since 2010, the bottom-up global emission inventories have been closer to methane emissions in the most carbon-intensive Representative Concentrations Pathway (RCP<sub>8</sub>.5) and higher than all other RCP scenarios. Bottom-up approaches suggest larger global emissions (736 Tg CH<sub>4</sub> yr−1, range 596–884) mostly because of larger natural emissions from individual sources such as inland waters, natural wetlands and geological sources. Considering the atmospheric constraints on the top-down budget, it is likely that some of the individual emissions reported by the bottom-up approaches are overestimated, leading to too large global emissions. Latitudinal data from top-down emissions indicate a predominance of tropical emissions (∼ 64 % of the global budget, < 30° N) as compared to mid (∼ 32 %, 30–60° N) and high northern latitudes (∼ 4 %, 60–90° N). Top-down inversions consistently infer lower emissions in China (∼ 58 Tg CH<sub>4</sub> yr−1, range 51–72, −14 %) and higher emissions in Africa (86 Tg CH<sub>4</sub> yr−1, range 73–108, +19 %) than bottom-up values used as prior estimates. Overall, uncertainties for anthropogenic emissions appear smaller than those from natural sources, and the uncertainties on source categories appear larger for top-down inversions than for bottom-up inventories and models.  The most important source of uncertainty on the methane budget is attributable to emissions from wetland and other inland waters. We show that the wetland extent could contribute 30–40 % on the estimated range for wetland emissions. Other priorities for improving the methane budget include the following: (i) the development of process-based models for inland-water emissions, (ii) the intensification of methane observations at local scale (flux measurements) to constrain bottom-up land surface models, and at regional scale (surface networks and satellites) to constrain top-down inversions, (iii) improvements in the estimation of atmospheric loss by OH, and (iv) improvements of the transport models integrated in top-down inversions. The data presented here can be downloaded from the Carbon Dioxide Information Analysis Center (http://doi.org/10.3334/CDIAC/GLOBAL_METHANE_BUDGET_2016_V1.1) and the Global Carbon Project.