---
title: 'Variability and quasi-decadal changes in the methane budget over the period 2000–2012'
author: 'Saunois, Marielle and Bousquet, Philippe and Poulter, Ben and Peregon, Anna and Ciais, Philippe and Canadell, Josep G. and Dlugokencky, Edward J. and Etiope, Giuseppe and Bastviken, David and Houweling, Sander and Janssens-Maenhout, Greet and Tubiello, Francesco N. and Castaldi, Simona and Jackson, Robert B. and Alexe, Mihai and Arora, Vivek K. and Beerling, David J. and Bergamaschi, Peter and Blake, Donald R. and Brailsford, Gordon and Bruhwiler, Lori and Crevoisier, Cyril and Crill, Patrick and Covey, Kristofer and Frankenberg, Christian and Gedney, Nicola and Höglund-Isaksson, Lena and Ishizawa, Misa and Ito, Akihiko and Joos, Fortunat and Kim, Heon-Sook and Kleinen, Thomas and Krummel, Paul and Lamarque, Jean-François and Langenfelds, Ray and Locatelli, Robin and Machida, Toshinobu and Maksyutov, Shamil and Melton, Joe R. and Morino, Isamu and Naik, Vaishali and O''Doherty, Simon and Parmentier, Frans-Jan W. and Patra, Prabir K. and Peng, Changhui and Peng, Shushi and Peters, Glen P. and Pison, Isabelle and Prinn, Ronald and Ramonet, Michel and Riley, William J. and Saito, Makoto and Santini, Monia and Schroeder, Ronny and Simpson, Isobel J. and Spahni, Renato and Takizawa, Atsushi and Thornton, Brett F. and Tian, Hanqin and Tohjima, Yasunori and Viovy, Nicolas and Voulgarakis, Apostolos and Weiss, Ray and Wilton, David J. and Wiltshire, Andy and Worthy, Doug and Wunch, Debra and Xu, Xiyan and Yoshida, Yukio and Zhang, Bowen and Zhang, Zhen and Zhu, Qiuan'
type: 'journal-article'
year: 2017
publication: 'Atmospheric Chemistry and Physics'
doi: '10.5194/acp-17-11135-2017'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. Following the recent Global Carbon Project (GCP) synthesis of the decadal methane (CH<sub>4</sub>) budget over 2000–2012 (Saunois et al., 2016), we analyse here the same dataset with a focus on quasi-decadal and inter-annual variability in CH<sub>4</sub> emissions. The GCP dataset integrates results from top-down studies (exploiting atmospheric observations within an atmospheric inverse-modelling framework) and bottom-up models (including process-based models for estimating land surface emissions and atmospheric chemistry), inventories of anthropogenic emissions, and data-driven approaches.  The annual global methane emissions from top-down studies, which by construction match the observed methane growth rate within their uncertainties, all show an increase in total methane emissions over the period 2000–2012, but this increase is not linear over the 13 years. Despite differences between individual studies, the mean emission anomaly of the top-down ensemble shows no significant trend in total methane emissions over the period 2000–2006, during the plateau of atmospheric methane mole fractions, and also over the period 2008–2012, during the renewed atmospheric methane increase. However, the top-down ensemble mean produces an emission shift between 2006 and 2008, leading to 22 [16–32] Tg CH<sub>4</sub> yr−1 higher methane emissions over the period 2008–2012 compared to 2002–2006. This emission increase mostly originated from the tropics, with a smaller contribution from mid-latitudes and no significant change from boreal regions.  The regional contributions remain uncertain in top-down studies. Tropical South America and South and East Asia seem to contribute the most to the emission increase in the tropics. However, these two regions have only limited atmospheric measurements and remain therefore poorly constrained.  The sectorial partitioning of this emission increase between the periods 2002–2006 and 2008–2012 differs from one atmospheric inversion study to another. However, all top-down studies suggest smaller changes in fossil fuel emissions (from oil, gas, and coal industries) compared to the mean of the bottom-up inventories included in this study. This difference is partly driven by a smaller emission change in China from the top-down studies compared to the estimate in the Emission Database for Global Atmospheric Research (EDGARv<sub>4</sub>.2) inventory, which should be revised to smaller values in a near future. We apply isotopic signatures to the emission changes estimated for individual studies based on five emission sectors and find that for six individual top-down studies (out of eight) the average isotopic signature of the emission changes is not consistent with the observed change in atmospheric 13CH4. However, the partitioning in emission change derived from the ensemble mean is consistent with this isotopic constraint. At the global scale, the top-down ensemble mean suggests that the dominant contribution to the resumed atmospheric CH<sub>4</sub> growth after 2006 comes from microbial sources (more from agriculture and waste sectors than from natural wetlands), with an uncertain but smaller contribution from fossil CH<sub>4</sub> emissions. In addition, a decrease in biomass burning emissions (in agreement with the biomass burning emission databases) makes the balance of sources consistent with atmospheric 13CH4 observations.  In most of the top-down studies included here, OH concentrations are considered constant over the years (seasonal variations but without any inter-annual variability). As a result, the methane loss (in particular through OH oxidation) varies mainly through the change in methane concentrations and not its oxidants. For these reasons, changes in the methane loss could not be properly investigated in this study, although it may play a significant role in the recent atmospheric methane changes as briefly discussed at the end of the paper.