---
title: 'Validation of SCIAMACHY HDO/H
<sub>2</sub>
O measurements using the TCCON and NDACC-MUSICA networks'
author: 'Scheepmaker, R. A. and Frankenberg, C. and Deutscher, N. M. and Schneider, M. and Barthlott, S. and Blumenstock, T. and Garcia, O. E. and Hase, F. and Jones, N. and Mahieu, E. and Notholt, J. and Velazco, V. and Landgraf, J. and Aben, I.'
type: 'journal-article'
year: 2015
publication: 'Atmospheric Measurement Techniques'
doi: '10.5194/amt-8-1799-2015'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. Measurements of the atmospheric HDO/H<sub>2</sub>O ratio help us to better understand the hydrological cycle and improve models to correctly simulate tropospheric humidity and therefore climate change. We present an updated version of the column-averaged HDO/H<sub>2</sub>O ratio data set from the SCanning Imaging Absorption spectroMeter for Atmospheric CHartographY (SCIAMACHY). The data set is extended with 2 additional years, now covering 2003–2007, and is validated against co-located ground-based total column δD measurements from Fourier transform spectrometers (FTS) of the Total Carbon Column Observing Network (TCCON) and the Network for the Detection of Atmospheric Composition Change (NDACC, produced within the framework of the MUSICA project). Even though the time overlap among the available data is not yet ideal, we determined a mean negative bias in SCIAMACHY δD of −35 ± 30‰ compared to TCCON and −69 ± 15‰ compared to MUSICA (the uncertainty indicating the station-to-station standard deviation). The bias shows a latitudinal dependency, being largest (∼ −60 to −80‰) at the highest latitudes and smallest (∼ −20 to −30‰) at the lowest latitudes. We have tested the impact of an offset correction to the SCIAMACHY HDO and H<sub>2</sub>O columns. This correction leads to a humidity- and latitude-dependent shift in δD and an improvement of the bias by 27‰, although it does not lead to an improved correlation with the FTS measurements nor to a strong reduction of the latitudinal dependency of the bias. The correction might be an improvement for dry, high-altitude areas, such as the Tibetan Plateau and the Andes region. For these areas, however, validation is currently impossible due to a lack of ground stations. The mean standard deviation of single-sounding SCIAMACHY–FTS differences is ∼ 115‰, which is reduced by a factor ∼ 2 when we consider monthly means. When we relax the strict matching of individual measurements and focus on the mean seasonalities using all available FTS data, we find that the correlation coefficients between SCIAMACHY and the FTS networks improve from 0.2 to 0.7–0.8. Certain ground stations show a clear asymmetry in δD during the transition from the dry to the wet season and back, which is also detected by SCIAMACHY. This asymmetry points to a transition in the source region temperature or location of the water vapour and shows the added information that HDO/H<sub>2</sub>O measurements provide when used in combination with variations in humidity.