---
title: 'Methane retrievals from Greenhouse Gases Observing Satellite (GOSAT) shortwave infrared measurements: Performance comparison of proxy and physics retrieval algorithms'
author: 'Schepers, D. and Guerlet, S. and Butz, A. and Landgraf, J. and Frankenberg, C. and Hasekamp, O. and Blavier, J.‐F. and Deutscher, N. M. and Griffith, D. W. T. and Hase, F. and Kyro, E. and Morino, I. and Sherlock, V. and Sussmann, R. and Aben, I.'
type: 'journal-article'
year: 2012
publication: 'Journal of Geophysical Research: Atmospheres'
doi: '10.1029/2012jd017549'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

We compare two conceptually different methods for determining methane column‐averaged mixing ratios  from Greenhouse Gases Observing Satellite (GOSAT) shortwave infrared (SWIR) measurements. These methods account differently for light scattering by aerosol and cirrus. The proxy method retrieves a CO<sub>2</sub> column which, in conjunction with prior knowledge on CO<sub>2</sub> as a proxy for scattering effects. The physics‐based method accounts for scattering by retrieving three effective parameters of a scattering layer. Both retrievals are validated on a 19‐month data set using ground‐based  at 12 stations of the Total Carbon Column Observing Network (TCCON), showing comparable performance: for the proxy retrieval we find station‐dependent retrieval biases from −0.312% to 0.421% of  a standard deviation of 0.22% and a typical precision of 17 ppb. The physics method shows biases between −0.836% and −0.081% with a standard deviation of 0.24% and a precision similar to the proxy method. Complementing this validation we compared both retrievals with simulated methane fields from a global chemistry‐transport model. This identified shortcomings of both retrievals causing biases of up to 1ings and provide a satisfying validation of any methane retrieval from space‐borne SWIR measurements, in our opinion it is essential to further expand the network of TCCON stations.