---
title: 'HDO and  H
<sub>2</sub>
O total column retrievals from TROPOMI shortwave infrared measurements'
author: 'Scheepmaker, Remco A. and aan de Brugh, Joost and Hu, Haili and Borsdorff, Tobias and Frankenberg, Christian and Risi, Camille and Hasekamp, Otto and Aben, Ilse and Landgraf, Jochen'
type: 'journal-article'
year: 2016
publication: 'Atmospheric Measurement Techniques'
doi: '10.5194/amt-9-3921-2016'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. The TROPOspheric Monitoring Instrument (TROPOMI) on board the European Space Agency Sentinel-5 Precursor mission is scheduled for launch in the last quarter of 2016. As part of its operational processing the mission will provide CH<sub>4</sub> and CO total columns using backscattered sunlight in the shortwave infrared band (2.3 µm). By adapting the CO retrieval algorithm, we have developed a non-scattering algorithm to retrieve total column HDO and H<sub>2</sub>O from the same measurements under clear-sky conditions. The isotopologue ratio HDO ∕ H<sub>2</sub>O is a powerful diagnostic in the efforts to improve our understanding of the hydrological cycle and its role in climate change, as it provides an insight into the source and transport history of water vapour, nature's strongest greenhouse gas. Due to the weak reflectivity over water surfaces, we need to restrict the retrieval to cloud-free scenes over land. We exploit a novel 2-band filter technique, using strong vs. weak water or methane absorption bands, to prefilter scenes with medium-to-high-level clouds, cirrus or aerosol and to significantly reduce processing time. Scenes with cloud top heights ≲1 km, very low fractions of high-level clouds or an aerosol layer above a high surface albedo are not filtered out. We use an ensemble of realistic measurement simulations for various conditions to show the efficiency of the cloud filter and to quantify the performance of the retrieval. The single-measurement precision in terms of δD is better than 15–25 ‰ for even the lowest surface albedo (2–4 ‰ for high albedos), while a small bias remains possible of up to  ∼ 20 ‰ due to remaining aerosol or up to  ∼ 70 ‰ due to remaining cloud contamination. We also present an analysis of the sensitivity towards prior assumptions, which shows that the retrieval has a small but significant sensitivity to the a priori assumption of the atmospheric trace gas profiles. Averaging multiple measurements over time and space, however, will reduce these errors, due to the quasi-random nature of the profile uncertainties. The sensitivity of the retrieval with respect to instrumental parameters within the expected instrument performance is  < 3 ‰, which represents only a small contribution to the overall error budget. Spectroscopic uncertainties of the water lines, however, can have a larger and more systematic impact on the performance of the retrieval and warrant further reassessment of the water line parameters. With TROPOMI's high radiometric sensitivity, wide swath (resulting in daily global coverage) and efficient cloud filtering, in combination with a spatial resolution of 7 × 7 km2, we will greatly increase the amount of useful data on HDO, H<sub>2</sub>O and their ratio HDO ∕ H<sub>2</sub>O. We showcase the overall performance of the retrieval algorithm and cloud filter with an accurate simulation of TROPOMI measurements from a single overpass over parts of the USA and Mexico, based on MODIS satellite data and realistic conditions for the surface, atmosphere and chemistry (including isotopologues). This shows that TROPOMI will pave the way for new studies of the hydrological cycle, both globally and locally, on timescales of mere days and weeks instead of seasons and years and will greatly extend the HDO ∕ H<sub>2</sub>O datasets from the SCIAMACHY and GOSAT missions.