---
title: 'Water vapour total columns from SCIAMACHY spectra in the 2.36 μm window'
author: 'Schrijver, H. and Gloudemans, A. M. S. and Frankenberg, C. and Aben, I.'
type: 'journal-article'
year: 2009
publication: 'Atmospheric Measurement Techniques'
doi: '10.5194/amt-2-561-2009'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. The potential of the shortwave infrared channel of the atmospheric spectrometer SCIAMACHY on Envisat to provide accurate measurements of total atmospheric water vapour columns is explored. It is shown that good quality results can be obtained for cloud free scenes above the continents using the Iterative Maximum Likelihood Method. In addition to the standard cloud filter employed in this method, further cloud screening is obtained by comparing simultaneously retrieved methane columns with values expected from models. A novel method is used to correct for the scattering effects introduced in the spectra by the ice layer on the detector window.  The retrieved water vapour total vertical columns for the period 2003–2007 are compared with spatially and temporally collocated values from the European Centre for Mid-Range Weather Forecast (ECMWF) data. The observed differences for individual measurements have standard deviations not higher than 0.3 g/cm2 and an absolute mean value smaller than 0.01 g/cm2 with some regional excursions.  The use of recently published spectroscopic data for water vapour led to a significant improvement in the agreement of the retrieved water vapour total columns and the values derived from ECMWF data. This analysis thus supports the superior quality of the new spectroscopic information using atmospheric data.