---
title: 'Constraining global methane emissions and uptake by ecosystems'
author: 'Spahni, R. and Wania, R. and Neef, L. and van Weele, M. and Pison, I. and Bousquet, P. and Frankenberg, C. and Foster, P. N. and Joos, F. and Prentice, I. C. and van Velthoven, P.'
type: 'journal-article'
year: 2011
publication: 'Biogeosciences'
doi: '10.5194/bg-8-1643-2011'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. Natural methane (CH<sub>4</sub>) emissions from wet ecosystems are an important part of today's global CH<sub>4</sub> budget. Climate affects the exchange of CH<sub>4</sub> between ecosystems and the atmosphere by influencing CH<sub>4</sub> production, oxidation, and transport in the soil. The net CH<sub>4</sub> exchange depends on ecosystem hydrology, soil and vegetation characteristics. Here, the LPJ-WHyMe global dynamical vegetation model is used to simulate global net CH<sub>4</sub> emissions for different ecosystems: northern peatlands (45°–90° N), naturally inundated wetlands (60° S–45° N), rice agriculture and wet mineral soils. Mineral soils are a potential CH<sub>4</sub> sink, but can also be a source with the direction of the net exchange depending on soil moisture content. The geographical and seasonal distributions are evaluated against multi-dimensional atmospheric inversions for 2003–2005, using two independent four-dimensional variational assimilation systems. The atmospheric inversions are constrained by the atmospheric CH<sub>4</sub> observations of the SCIAMACHY satellite instrument and global surface networks. Compared to LPJ-WHyMe the inversions result in a~significant reduction in the emissions from northern peatlands and suggest that LPJ-WHyMe maximum annual emissions peak about one month late. The inversions do not put strong constraints on the division of sources between inundated wetlands and wet mineral soils in the tropics. Based on the inversion results we diagnose model parameters in LPJ-WHyMe and simulate the surface exchange of CH<sub>4</sub> over the period 1990–2008. Over the whole period we infer an increase of global ecosystem CH<sub>4</sub> emissions of +1.11 Tg CH<sub>4</sub> yr−1, not considering potential additional changes in wetland extent. The increase in simulated CH<sub>4</sub> emissions is attributed to enhanced soil respiration resulting from the observed rise in land temperature and in atmospheric carbon dioxide that were used as input. The long-term decline of the atmospheric CH<sub>4</sub> growth rate from 1990 to 2006 cannot be fully explained with the simulated ecosystem emissions. However, these emissions show an increasing trend of +3.62 Tg CH<sub>4</sub> yr−1 over 2005–2008 which can partly explain the renewed increase in atmospheric CH<sub>4</sub> concentration during recent years.