---
title: 'Orbiting Carbon Observatory-2 (OCO-2) cloud screening algorithms:  validation against collocated MODIS and CALIOP data'
author: 'Taylor, Thomas E. and O''Dell, Christopher W. and Frankenberg, Christian and Partain, Philip T. and Cronk, Heather Q. and Savtchenko, Andrey and Nelson, Robert R. and Rosenthal, Emily J. and Chang, Albert Y. and Fisher, Brenden and Osterman, Gregory B. and Pollock, Randy H. and Crisp, David and Eldering, Annmarie and Gunson, Michael R.'
type: 'journal-article'
year: 2016
publication: 'Atmospheric Measurement Techniques'
doi: '10.5194/amt-9-973-2016'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. The objective of the National Aeronautics and Space Administration's (NASA) Orbiting Carbon Observatory-2 (OCO-2) mission is to retrieve the column-averaged carbon dioxide (CO<sub>2</sub>) dry air mole fraction (XCO<sub>2</sub>) from satellite measurements of reflected sunlight in the near-infrared. These estimates can be biased by clouds and aerosols, i.e., contamination, within the instrument's field of view. Screening of the most contaminated soundings minimizes unnecessary calls to the computationally expensive Level 2 (L<sub>2</sub>) XCO<sub>2</sub> retrieval algorithm. Hence, robust cloud screening methods have been an important focus of the OCO-2 algorithm development team. Two distinct, computationally inexpensive cloud screening algorithms have been developed for this application. The A-Band Preprocessor (ABP) retrieves the surface pressure using measurements in the 0.76 µm O<sub>2</sub> A band, neglecting scattering by clouds and aerosols, which introduce photon path-length differences that can cause large deviations between the expected and retrieved surface pressure. The Iterative Maximum A Posteriori (IMAP) Differential Optical Absorption Spectroscopy (DOAS) Preprocessor (IDP) retrieves independent estimates of the CO<sub>2</sub> and H<sub>2</sub>O column abundances using observations taken at 1.61 µm (weak CO<sub>2</sub> band) and 2.06 µm (strong CO<sub>2</sub> band), while neglecting atmospheric scattering. The CO<sub>2</sub> and H<sub>2</sub>O column abundances retrieved in these two spectral regions differ significantly in the presence of cloud and scattering aerosols. The combination of these two algorithms, which are sensitive to different features in the spectra, provides the basis for cloud screening of the OCO-2 data set.To validate the OCO-2 cloud screening approach, collocated measurements from NASA's Moderate Resolution Imaging Spectrometer (MODIS), aboard the Aqua platform, were compared to results from the two OCO-2 cloud screening algorithms. With tuning of algorithmic threshold parameters that allows for processing of  ≃ 20–25 % of all OCO-2 soundings, agreement between the OCO-2 and MODIS cloud screening methods is found to be  ≃ 85 % over four 16-day orbit repeat cycles in both the winter (December) and spring (April–May) for OCO-2 nadir-land, glint-land and glint-water observations.No major, systematic, spatial or temporal dependencies were found, although slight differences in the seasonal data sets do exist and validation is more problematic with increasing solar zenith angle and when surfaces are covered in snow and ice and have complex topography. To further analyze the performance of the cloud screening algorithms, an initial comparison of OCO-2 observations was made to collocated measurements from the Cloud-Aerosol Lidar with Orthogonal Polarization (CALIOP) aboard the Cloud-Aerosol Lidar and Infrared Pathfinder Satellite Observations (CALIPSO). These comparisons highlight the strength of the OCO-2 cloud screening algorithms in identifying high, thin clouds but suggest some difficulty in identifying some clouds near the surface, even when the optical thicknesses are greater than 1.