---
title: 'Space‐based remote imaging spectroscopy of the Aliso Canyon CH<sub>4</sub> superemitter'
author: 'Thompson, D. R. and Thorpe, A. K. and Frankenberg, C. and Green, R. O. and Duren, R. and Guanter, L. and Hollstein, A. and Middleton, E. and Ong, L. and Ungar, S.'
type: 'journal-article'
year: 2016
publication: 'Geophysical Research Letters'
doi: '10.1002/2016gl069079'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

AbstractThe Aliso Canyon gas storage facility near Porter Ranch, California, produced a large accidental CH<sub>4</sub> release from October 2015 to February 2016. The Hyperion imaging spectrometer on board the EO‐1 satellite successfully detected this event, achieving the first orbital attribution of CH<sub>4</sub> to a single anthropogenic superemitter. Hyperion measured shortwave infrared signatures of CH<sub>4</sub> near 2.3 μm at 0.01 μm spectral resolution and 30 m spatial resolution. It detected the plume on three overpasses, mapping its magnitude and morphology. These orbital observations were consistent with measurements by airborne instruments. We evaluate Hyperion instrument performance, draw implications for future orbital instruments, and extrapolate the potential for a global survey of CH<sub>4</sub> superemitters.