---
title: 'Real-time remote detection and measurement for airborne imaging spectroscopy: a case study with methane'
author: 'Thompson, D. R. and Leifer, I. and Bovensmann, H. and Eastwood, M. and Fladeland, M. and Frankenberg, C. and Gerilowski, K. and Green, R. O. and Kratwurst, S. and Krings, T. and Luna, B. and Thorpe, A. K.'
type: 'journal-article'
year: 2015
publication: 'Atmospheric Measurement Techniques'
doi: '10.5194/amt-8-4383-2015'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. Localized anthropogenic sources of atmospheric CH<sub>4</sub> are highly uncertain and temporally variable. Airborne remote measurement is an effective method to detect and quantify these emissions. In a campaign context, the science yield can be dramatically increased by real-time retrievals that allow operators to coordinate multiple measurements of the most active areas. This can improve science outcomes for both single- and multiple-platform missions. We describe a case study of the NASA/ESA CO<sub>2</sub> and MEthane eXperiment (COMEX) campaign in California during June and August/September 2014. COMEX was a multi-platform campaign to measure CH<sub>4</sub> plumes released from anthropogenic sources including oil and gas infrastructure. We discuss principles for real-time spectral signature detection and measurement, and report performance on the NASA Next Generation Airborne Visible Infrared Spectrometer (AVIRIS-NG). AVIRIS-NG successfully detected CH<sub>4</sub> plumes in real-time at Gb s−1 data rates, characterizing fugitive releases in concert with other in situ and remote instruments. The teams used these real-time CH<sub>4</sub> detections to coordinate measurements across multiple platforms, including airborne in situ, airborne non-imaging remote sensing, and ground-based in situ instruments. To our knowledge this is the first reported use of real-time trace-gas signature detection in an airborne science campaign, and presages many future applications. Post-analysis demonstrates matched filter methods providing noise-equivalent (1σ) detection sensitivity for 1.0 % CH<sub>4</sub> column enhancements equal to 141 ppm m.