---
title: 'Airborne DOAS retrievals of methane, carbon dioxide, and water vapor concentrations at high spatial resolution: application to AVIRIS-NG'
author: 'Thorpe, Andrew K. and Frankenberg, Christian and Thompson, David R. and Duren, Riley M. and Aubrey, Andrew D. and Bue, Brian D. and Green, Robert O. and Gerilowski, Konstantin and Krings, Thomas and Borchardt, Jakob and Kort, Eric A. and Sweeney, Colm and Conley, Stephen and Roberts, Dar A. and Dennison, Philip E.'
type: 'journal-article'
year: 2017
publication: 'Atmospheric Measurement Techniques'
doi: '10.5194/amt-10-3833-2017'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. At local scales, emissions of methane and carbon dioxide are highly uncertain. Localized sources of both trace gases can create strong local gradients in its columnar abundance, which can be discerned using absorption spectroscopy at high spatial resolution. In a previous study, more than 250 methane plumes were observed in the San Juan Basin near Four Corners during April 2015 using the next-generation Airborne Visible/Infrared Imaging Spectrometer (AVIRIS-NG) and a linearized matched filter. For the first time, we apply the iterative maximum a posteriori differential optical absorption spectroscopy (IMAP-DOAS) method to AVIRIS-NG data and generate gas concentration maps for methane, carbon dioxide, and water vapor plumes. This demonstrates a comprehensive greenhouse gas monitoring capability that targets methane and carbon dioxide, the two dominant anthropogenic climate-forcing agents. Water vapor results indicate the ability of these retrievals to distinguish between methane and water vapor despite spectral interference in the shortwave infrared. We focus on selected cases from anthropogenic and natural sources, including emissions from mine ventilation shafts, a gas processing plant, tank, pipeline leak, and natural seep. In addition, carbon dioxide emissions were mapped from the flue-gas stacks of two coal-fired power plants and a water vapor plume was observed from the combined sources of cooling towers and cooling ponds. Observed plumes were consistent with known and suspected emission sources verified by the true color AVIRIS-NG scenes and higher-resolution Google Earth imagery. Real-time detection and geolocation of methane plumes by AVIRIS-NG provided unambiguous identification of individual emission source locations and communication to a ground team for rapid follow-up. This permitted verification of a number of methane emission sources using a thermal camera, including a tank and buried natural gas pipeline.