---
title: 'Methane emissions decline from reduced oil, natural gas, and refinery production during COVID-19'
author: 'Thorpe, A K and Kort, E A and Cusworth, D H and Ayasse, A K and Bue, B D and Yadav, V and Thompson, D R and Frankenberg, C and Herner, J and Falk, M and Green, R O and Miller, C E and Duren, R M'
type: 'journal-article'
year: 2023
publication: 'Environmental Research Communications'
doi: '10.1088/2515-7620/acb5e5'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract
In the summer of 2020, the AVIRIS-NG airborne imaging spectrometer surveyed California’s Southern San Joaquin Valley and the South Bay (Los Angeles County) to identify anthropogenic methane (CH<sub>4</sub>) point source plumes, estimate emission rates, and attribute sources to both facilities and emission sectors. These flights were designed to revisit regions previously surveyed by the 2016–2017 California Methane Survey and to assess the socioeconomic responses of COVID-19 on emissions across multiple sectors. For regions flown by both the California Methane Survey and the California COVID campaigns, total CH<sub>4</sub> point source emissions from the energy and oil & natural gas sectors were 34.8% lower during the summer 2020 flights, however, emission trends varied across sector. For the energy sector, there was a 28.2% decrease driven by reductions in refinery emissions consistent with a drop in production, which was offset in part with increases from powerplants. For the oil & natural gas sector, CH<sub>4</sub> emissions declined 34.2% and significant variability was observed at the oilfield scale. Emissions declined for all but the Buena Vista and Cymric fields with an observed positive relationship between production and emissions. In addition to characterizing the short-term impact of COVID-19 on CH<sub>4</sub> emissions, this study demonstrates the broader potential of remote sensing with sufficient sensitivity, spatial resolution, and spatio-temporal completeness to quantify changes in CH<sub>4</sub> emissions at the scale of key sectors and facilities.