---
title: 'Attribution of individual methane and carbon dioxide emission sources using EMIT observations from space'
author: 'Thorpe, Andrew K. and Green, Robert O. and Thompson, David R. and Brodrick, Philip G. and Chapman, John W. and Elder, Clayton D. and Irakulis-Loitxate, Itziar and Cusworth, Daniel H. and Ayasse, Alana K. and Duren, Riley M. and Frankenberg, Christian and Guanter, Luis and Worden, John R. and Dennison, Philip E. and Roberts, Dar A. and Chadwick, K. Dana and Eastwood, Michael L. and Fahlen, Jay E. and Miller, Charles E.'
type: 'journal-article'
year: 2023
publication: 'Science Advances'
doi: '10.1126/sciadv.adh2391'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Carbon dioxide and methane emissions are the two primary anthropogenic climate-forcing agents and an important source of uncertainty in the global carbon budget. Uncertainties are further magnified when emissions occur at fine spatial scales (<1 km), making attribution challenging. We present the first observations from NASA’s Earth Surface Mineral Dust Source Investigation (EMIT) imaging spectrometer showing quantification and attribution of fine-scale methane (0.3 to 73 tonnes CH
4
hour
−1
) and carbon dioxide sources (1571 to 3511 tonnes CO
2
hour
−1
) spanning the oil and gas, waste, and energy sectors. For selected countries observed during the first 30 days of EMIT operations, methane emissions varied at a regional scale, with the largest total emissions observed for Turkmenistan (731 ± 148 tonnes CH
4
hour
−1
). These results highlight the contributions of current and planned point source imagers in closing global carbon budgets.