---
title: 'A double peak in the seasonality of California''s photosynthesis as observed from space'
author: 'Turner, Alexander J. and Köhler, Philipp and Magney, Troy S. and Frankenberg, Christian and Fung, Inez and Cohen, Ronald C.'
type: 'journal-article'
year: 2020
publication: 'Biogeosciences'
doi: '10.5194/bg-17-405-2020'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. Solar-induced chlorophyll fluorescence (SIF) has been shown to be a powerful proxy for photosynthesis and gross primary productivity (GPP).
The recently launched TROPOspheric Monitoring Instrument (TROPOMI) features the required spectral resolution and signal-to-noise ratio to retrieve SIF from space.
Here, we present a downscaling method to obtain 500 m spatial resolution SIF over California.
We report daily values based on a 14 d window.
TROPOMI SIF data show a strong correspondence with daily GPP estimates at AmeriFlux sites across multiple ecosystems in California.
We find a linear relationship between SIF and GPP that is largely invariant across ecosystems with an intercept that is not significantly different from zero.
Measurements of SIF from TROPOMI agree with MODerate Resolution Imaging Spectroradiometer (MODIS) vegetation indices – the normalized difference vegetation index (NDVI), enhanced vegetation index (EVI), and near-infrared reflectance of vegetation index (NIRv) – at annual timescales but indicate different temporal dynamics at monthly and daily timescales.
TROPOMI SIF data show a double peak in the seasonality of photosynthesis, a feature that is not present in the MODIS vegetation indices.
The different seasonality in the vegetation indices may be due to a clear-sky bias in the vegetation indices, whereas previous work has shown SIF to have a low sensitivity to clouds and to detect the downregulation of photosynthesis even when plants appear green.
We further decompose the spatiotemporal patterns in the SIF data based on land cover.
The double peak in the seasonality of California's photosynthesis is due to two processes that are out of phase: grasses, chaparral, and oak savanna ecosystems show an April maximum, while evergreen forests peak in June.
An empirical orthogonal function (EOF) analysis corroborates the phase offset and spatial patterns driving the double peak.
The EOF analysis further indicates that two spatiotemporal patterns explain 84 % of the variability in the SIF data.
Results shown here are promising for obtaining global GPP at sub-kilometer spatial scales and identifying the processes driving carbon uptake.