---
title: 'Extreme events driving year-to-year differences in gross primary productivity across the US'
author: 'Turner, Alexander J. and Köhler, Philipp and Magney, Troy S. and Frankenberg, Christian and Fung, Inez and Cohen, Ronald C.'
type: 'journal-article'
year: 2021
publication: 'Biogeosciences'
doi: '10.5194/bg-18-6579-2021'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. Solar-induced chlorophyll fluorescence (SIF) has previously been shown to strongly correlate with gross primary productivity (GPP); however this relationship has not yet been quantified for the recently launched TROPOspheric Monitoring Instrument (TROPOMI). Here we use a Gaussian mixture model to develop a parsimonious relationship between SIF from TROPOMI and GPP from flux towers across the conterminous United States (CONUS). The mixture model indicates the SIF–GPP relationship can be characterized by a linear model with two terms. We then estimate GPP across CONUS at 500 m spatial resolution over a 16 d moving window. We observe four extreme precipitation events that induce regional GPP anomalies: drought in western Texas, flooding in the midwestern US, drought in South Dakota, and drought in California. Taken together, these events account for 28 % of the year-to-year GPP differences across CONUS. Despite these large regional anomalies, we find that CONUS GPP varies by less than 4 % between 2018 and 2019.