---
title: 'Toward More Accurate Modeling of Canopy Radiative Transfer and Leaf Electron Transport in Land Surface Modeling'
author: 'Wang, Yujie and Frankenberg, Christian'
type: 'journal-article'
year: 2024
publication: 'Journal of Advances in Modeling Earth Systems'
doi: '10.1029/2023ms003992'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

AbstractModeling leaf photosynthesis is essential for quantifying the carbon, water, and energy fluxes of the terrestrial biosphere. However, due to the lack of simultaneous measurements of leaf light absorption and gas exchange, canopy radiative transfer (RT) and photosynthesis modeling often rely on simplified assumptions about light absorption and electron transport. These assumptions ignore variations in leaf biophysical traits and environmental conditions. In this study, we utilized a next‐generation land surface model (LSM)—CliMA Land, which incorporates hyperspectral canopy RT and provides a more accurate representation of trait variations. We evaluated the potential bias in electron transport estimates introduced by the broadband RT schemes used in traditional LSMs. Additionally, we explored the impact of different leaf electron transport parameterization schemes on global‐scale photosynthesis and fluorescence modeling. We showed that (a) traditional LSMs that disregard the impacts of leaf temperature and leaf traits on electron transport tend to overestimate electron transport rates. (b) Photosynthesis and fluorescence within a grid can exhibit biases exceeding 20%, with these biases demonstrating contrasting seasonality. (c) Global estimates of integrated photosynthesis and fluorescence differ by 8.1% and 8.8%, respectively. These results underscore the importance of adopting more sophisticated and accurate modeling schemes, such as hyperspectral canopy RT, in future LSMs and Earth system modeling to enhance the reliability of modeling outcomes.