---
title: 'Testing stomatal models at the stand level in deciduous angiosperm and evergreen gymnosperm forests using CliMA Land (v0.1)'
author: 'Wang, Yujie and Köhler, Philipp and He, Liyin and Doughty, Russell and Braghiere, Renato K. and Wood, Jeffrey D. and Frankenberg, Christian'
type: 'journal-article'
year: 2021
publication: 'Geoscientific Model Development'
doi: '10.5194/gmd-14-6741-2021'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. At the leaf level, stomata control the exchange of water and carbon across the air–leaf interface. Stomatal conductance is typically modeled
empirically, based on environmental conditions at the leaf surface. Recently developed stomatal optimization models show great skills at predicting
carbon and water fluxes at both the leaf and tree levels. However, how well the optimization models perform at
larger scales has not been extensively evaluated. Furthermore, stomatal models are often used with simple single-leaf representations of canopy radiative transfer (RT), such as
big-leaf models. Nevertheless, the single-leaf canopy RT schemes do not have the capability to model optical properties of the leaves nor the entire
canopy. As a result, they are unable to directly link canopy optical properties with light distribution within the canopy to remote sensing data
observed from afar. Here, we incorporated one optimization-based and two empirical stomatal models with a comprehensive RT model in the land
component of a new Earth system model within CliMA, the Climate Modelling Alliance. The model allowed us to simultaneously simulate carbon and water
fluxes as well as leaf and canopy reflectance and fluorescence spectra. We tested our model by comparing our modeled carbon and water fluxes and
solar-induced chlorophyll fluorescence (SIF) to two flux tower observations (a gymnosperm forest and an angiosperm forest) and satellite SIF
retrievals, respectively. All three stomatal models quantitatively predicted the carbon and water fluxes for both forests. The optimization model,
in particular, showed increased skill in predicting the water flux given the lower error (ca. 14.2 % and 21.8 % improvement for the
gymnosperm and angiosperm forests, respectively) and better 1:1 comparison (slope increases from ca. 0.34 to 0.91 for the gymnosperm forest and
from ca. 0.38 to 0.62 for the angiosperm forest). Our model also predicted the SIF yield, quantitatively reproducing seasonal cycles for both
forests. We found that using stomatal optimization with a comprehensive RT model showed high accuracy in simulating land surface processes. The
ever-increasing number of regional and global datasets of terrestrial plants, such as leaf area index and chlorophyll contents, will help
parameterize the land model and improve future Earth system modeling in general.