---
title: 'GriddingMachine, a database and software for Earth system modeling at global and regional scales'
author: 'Wang, Yujie and Köhler, Philipp and Braghiere, Renato K. and Longo, Marcos and Doughty, Russell and Bloom, A. Anthony and Frankenberg, Christian'
type: 'journal-article'
year: 2022
publication: 'Scientific Data'
doi: '10.1038/s41597-022-01346-x'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

AbstractLand and Earth system modeling is moving towards more explicit biophysical representations, requiring increasing variety of datasets for initialization and benchmarking. However, researchers often have difficulties in identifying and integrating non-standardized datasets from various sources. We aim towards a standardized database and one-stop distribution method of global datasets. Here, we present the GriddingMachine as (1) a database of global-scale datasets commonly used to parameterize or benchmark the models, from plant traits to vegetation indices and geophysical information and (2) a cross-platform open source software to download and request a subset of datasets with only a few lines of code. The GriddingMachine datasets can be accessed either manually through traditional HTTP, or automatically using modern programming languages including Julia, Matlab, Octave, Python, and R. The GriddingMachine collections can be used for any land and Earth modeling framework and ecological research at the regional and global scales, and the number of datasets will continue to grow to meet the increasing needs of research communities.