---
title: 'On the impact of canopy model complexity on simulated carbon, water, and solar-induced chlorophyll fluorescence fluxes'
author: 'Wang, Yujie and Frankenberg, Christian'
type: 'journal-article'
year: 2022
publication: 'Biogeosciences'
doi: '10.5194/bg-19-29-2022'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. Lack of direct carbon, water, and energy flux observations at global scales makes it difficult to calibrate land surface models (LSMs). The
increasing number of remote-sensing-based products provide an alternative way to verify or constrain land models given their global coverage and
satisfactory spatial and temporal resolutions. However, these products and LSMs often differ in their assumptions and model setups, for example, the
canopy model complexity. The disagreements hamper the fusion of global-scale datasets with LSMs. To evaluate how much the canopy complexity affects
predicted canopy fluxes, we simulated and compared the carbon, water, and solar-induced chlorophyll fluorescence (SIF) fluxes using five different
canopy complexity setups from a one-layered canopy to a multi-layered canopy with leaf angular distributions. We modeled the canopy fluxes using the
recently developed land model by the Climate Modeling Alliance, CliMA Land. Our model results suggested that (1) when using the same model inputs, model-predicted carbon, water, and SIF fluxes were all higher for simpler canopy setups; (2) when accounting for vertical photosynthetic capacity
heterogeneity, differences between canopy complexity levels increased compared to the scenario of a uniform canopy; and (3) SIF fluxes modeled with
different canopy complexity levels changed with sun-sensor geometry. Given the different modeled canopy fluxes with different canopy complexities,
we recommend (1) not misusing parameters inverted with different canopy complexities or assumptions to avoid biases in model outputs and (2) using a
complex canopy model with angular distribution and a hyperspectral radiation transfer scheme when linking land processes to remotely sensed spectra.