---
title: 'Scientific Communities Striving for a Common Cause: Innovations in Carbon Cycle Science'
author: 'Whelan, Mary E. and Anderegg, Leander D. L. and Badgley, Grayson and Campbell, J. Elliott and Commane, Roisin and Frankenberg, Christian and Hilton, Timothy W. and Kuai, Le and Parazoo, Nicholas and Shiga, Yoichi and Wang, Yuting and Worden, John'
type: 'journal-article'
year: 2020
publication: 'Bulletin of the American Meteorological Society'
doi: '10.1175/bams-d-19-0306.1'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

AbstractWhere does the carbon released by burning fossil fuels go? Currently, ocean and land systems remove about half of the CO<sub>2</sub> emitted by human activities; the remainder stays in the atmosphere. These removal processes are sensitive to feedbacks in the energy, carbon, and water cycles that will change in the future. Observing how much carbon is taken up on land through photosynthesis is complicated because carbon is simultaneously respired by plants, animals, and microbes. Global observations from satellites and air samples suggest that natural ecosystems take up about as much CO<sub>2</sub> as they emit. To match the data, our land models generate imaginary Earths where carbon uptake and respiration are roughly balanced, but the absolute quantities of carbon being exchanged vary widely. Getting the magnitude of the flux is essential to make sure our models are capturing the right pattern for the right reasons. Combining two cutting-edge tools, carbonyl sulfide (OCS) and solar-induced fluorescence (SIF), will help develop an independent answer of how much carbon is being taken up by global ecosystems. Photosynthesis requires CO<sub>2</sub>, light, and water. OCS provides a spatially and temporally integrated picture of the “front door” of photosynthesis, proportional to CO<sub>2</sub> uptake and water loss through plant stomata. SIF provides a high-resolution snapshot of the “side door,” scaling with the light captured by leaves. These two independent pieces of information help us understand plant water and carbon exchange. A coordinated effort to generate SIF and OCS data through satellite, airborne, and ground observations will improve our process-based models to predict how these cycles will change in the future.