---
title: 'The ecosystem wilting point defines drought response and recovery of a
<scp>
<i>Quercus‐Carya</i>
</scp>
forest'
author: 'Wood, Jeffrey D. and Gu, Lianhong and Hanson, Paul J. and Frankenberg, Christian and Sack, Lawren'
type: 'journal-article'
year: 2023
publication: 'Global Change Biology'
doi: '10.1111/gcb.16582'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract

Soil and atmospheric droughts increasingly threaten plant survival and productivity around the world. Yet, conceptual gaps constrain our ability to predict ecosystem‐scale drought impacts under climate change. Here, we introduce the ecosystem wilting point (Ψ
EWP
), a property that integrates the drought response of an ecosystem's plant community across the soil–plant–atmosphere continuum. Specifically, Ψ
EWP
defines a threshold below which the capacity of the root system to extract soil water and the ability of the leaves to maintain stomatal function are strongly diminished. We combined ecosystem flux and leaf water potential measurements to derive the Ψ
EWP
of a
Quercus‐Carya
forest from an “ecosystem pressure–volume (PV) curve,” which is analogous to the tissue‐level technique. When community predawn leaf water potential (Ψ
pd
) was above Ψ
EWP
(=−2.0 MPa), the forest was highly responsive to environmental dynamics. When Ψ
pd
fell below Ψ
EWP
, the forest became insensitive to environmental variation and was a net source of carbon dioxide for nearly 2 months. Thus, Ψ
EWP
is a threshold defining marked shifts in ecosystem functional state. Though there was rainfall‐induced recovery of ecosystem gas exchange following soaking rains, a legacy of structural and physiological damage inhibited canopy photosynthetic capacity. Although over 16 growing seasons, only 10% of Ψ
pd
observations fell below Ψ
EWP
, the forest is commonly only 2–4 weeks of intense drought away from reaching Ψ
EWP
, and thus highly reliant on frequent rainfall to replenish the soil water supply. We propose, based on a bottom‐up analysis of root density profiles and soil moisture characteristic curves, that soil water acquisition capacity is the major determinant of Ψ
EWP
, and species in an ecosystem require compatible leaf‐level traits such as turgor loss point so that leaf wilting is coordinated with the inability to extract further water from the soil.