---
title: 'Profiles of CH
<sub>4</sub>
, HDO, H
<sub>2</sub>
O, and N
<sub>2</sub>
O with improved lower tropospheric vertical resolution from Aura TES radiances'
author: 'Worden, J. and Kulawik, S. and Frankenberg, C. and Payne, V. and Bowman, K. and Cady-Peirara, K. and Wecht, K. and Lee, J.-E. and Noone, D.'
type: 'journal-article'
year: 2012
publication: 'Atmospheric Measurement Techniques'
doi: '10.5194/amt-5-397-2012'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. Thermal infrared (IR) radiances measured near 8 microns contain information about the vertical distribution of water vapor (H<sub>2</sub>O), the water isotopologue HDO, and methane (CH<sub>4</sub>), key gases in the water and carbon cycles. Previous versions (Version 4 or less) of the TES profile retrieval algorithm used a "spectral-window" approach to minimize uncertainty from interfering species at the expense of reduced vertical resolution and sensitivity. In this manuscript we document changes to the vertical resolution and uncertainties of the TES version 5 retrieval algorithm. In this version (Version 5), joint estimates of H<sub>2</sub>O, HDO, CH<sub>4</sub> and nitrous oxide (N<sub>2</sub>O) are made using radiances from almost the entire spectral region between 1100 cm−1 and 1330 cm−1. The TES retrieval constraints are also modified in order to better use this information. The new H<sub>2</sub>O estimates show improved vertical resolution in the lower troposphere and boundary layer, while the new HDO/H<sub>2</sub>O estimates can now profile the HDO/H<sub>2</sub>O ratio between 925 hPa and 450 hPa in the tropics and during summertime at high latitudes. The new retrievals are now sensitive to methane in the free troposphere between 800 and 150 mb with peak sensitivity near 500 hPa; whereas in previous versions the sensitivity peaked at 200 hPa. However, the upper troposphere methane concentrations are biased high relative to the lower troposphere by approximately 4% on average. This bias is likely related to temperature, calibration, and/or methane spectroscopy errors. This bias can be mitigated by normalizing the CH<sub>4</sub> estimate by the ratio of the N<sub>2</sub>O estimate relative to the N<sub>2</sub>O prior, under the assumption that the same systematic error affects both the N<sub>2</sub>O and CH<sub>4</sub> estimates. We demonstrate that applying this ratio theoretically reduces the CH<sub>4</sub> estimate for non-retrieved parameters that jointly affect both the N<sub>2</sub>O and CH<sub>4</sub> estimates. The relative upper troposphere to lower troposphere bias is approximately 2.8% after this bias correction. Quality flags based upon the vertical variability of the methane and N<sub>2</sub>O estimates can be used to reduce this bias further. While these new CH<sub>4</sub>, HDO/H<sub>2</sub>O, and H<sub>2</sub>O estimates are consistent with previous TES retrievals in the altitude regions where the sensitivities overlap, future comparisons with independent profile measurement will be required to characterize the biases of these new retrievals and determine if the calculated uncertainties using the new constraints are consistent with actual uncertainties.