---
title: 'CH
<sub>4</sub>
and CO distributions over tropical fires during October 2006 as observed by the Aura TES satellite instrument and modeled by GEOS-Chem'
author: 'Worden, J. and Wecht, K. and Frankenberg, C. and Alvarado, M. and Bowman, K. and Kort, E. and Kulawik, S. and Lee, M. and Payne, V. and Worden, H.'
type: 'journal-article'
year: 2013
publication: 'Atmospheric Chemistry and Physics'
doi: '10.5194/acp-13-3679-2013'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. Tropical fires represent a highly uncertain source of atmospheric methane (CH<sub>4</sub>) because of the variability of fire emissions and the dependency of the fire CH<sub>4</sub> emission factors (g kg−1 dry matter burned) on fuel type and combustion phase. In this paper we use new observations of CH<sub>4</sub> and CO in the free troposphere from the Aura Tropospheric Emission Sounder (TES) satellite instrument to place constraints on the role of tropical fire emissions versus microbial production (e.g. in wetlands and livestock) during the (October) 2006 El Niño, a time of significant fire emissions from Indonesia. We first compare the global CH<sub>4</sub> distributions from TES using the GEOS-Chem model. We find a mean bias between the observations and model of 26.3 ppb CH<sub>4</sub> that is independent of latitude between 50° S and 80° N, consistent with previous validation studies of TES CH<sub>4</sub> retrievals using aircraft measurements. The slope of the distribution of CH<sub>4</sub> versus CO as observed by TES and modeled by GEOS-Chem is consistent (within the TES observation error) for air parcels over the Indonesian peat fires, South America, and Africa. The CH<sub>4</sub> and CO distributions are correlated between R = 0.42 and R = 0.46, with these correlations primarily limited by the TES random error. Over Indonesia, the observed slope of 0.13 (ppb ppb−1) ±0.01, as compared to a modeled slope of 0.153 (ppb ppb−1) ±0.005 and an emission ratio used within the GEOS-Chem model of approximately 0.11 (ppb ppb−1), indicates that most of the observed methane enhancement originated from the fire. Slopes of 0.47 (ppb ppb−1) ±0.04 and 0.44 (ppb ppb−1) ±0.03 over South America and Africa show that the methane in the observed air parcels primarily came from microbial-generated emissions. Sensitivity studies using GEOS-Chem show that part of the observed correlation for the Indonesian observations and most of the observed correlations over South America and Africa are a result of transport and mixing of the fire and nearby microbial-generated emissions into the observed air parcels. Differences between observed and modeled CH<sub>4</sub> distributions over South America and southern Africa indicate that the magnitude of the methane emissions for this time period are inconsistent with observations even if the relative distribution of fire versus biotic emissions are consistent. This study shows the potential for estimation of CH<sub>4</sub> emissions over tropical regions using joint satellite observations of CH<sub>4</sub> and CO.