---
title: 'Evaluation and attribution of OCO-2 XCO
<sub>2</sub>
uncertainties'
author: 'Worden, John R. and Doran, Gary and Kulawik, Susan and Eldering, Annmarie and Crisp, David and Frankenberg, Christian and O''Dell, Chris and Bowman, Kevin'
type: 'journal-article'
year: 2017
publication: 'Atmospheric Measurement Techniques'
doi: '10.5194/amt-10-2759-2017'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. Evaluating and attributing uncertainties in total column atmospheric CO<sub>2</sub> measurements (XCO<sub>2</sub>) from the OCO-2 instrument is critical for testing hypotheses related to the underlying processes controlling XCO<sub>2</sub> and for developing quality flags needed to choose those measurements that are usable for carbon cycle science.Here we test the reported uncertainties of version 7 OCO-2 XCO<sub>2</sub> measurements by examining variations of the XCO<sub>2</sub> measurements and their calculated uncertainties within small regions (∼  100 km  ×  10.5 km) in which natural CO<sub>2</sub> variability is expected to be small relative to variations imparted by noise or interferences. Over 39 000 of these small neighborhoods comprised of approximately 190 observations per neighborhood are used for this analysis. We find that a typical ocean measurement has a precision and accuracy of 0.35 and 0.24 ppm respectively for calculated precisions larger than  ∼  0.25 ppm. These values are approximately consistent with the calculated errors of 0.33 and 0.14 ppm for the noise and interference error, assuming that the accuracy is bounded by the calculated interference error. The actual precision for ocean data becomes worse as the signal-to-noise increases or the calculated precision decreases below 0.25 ppm for reasons that are not well understood. A typical land measurement, both nadir and glint, is found to have a precision and accuracy of approximately 0.75 and 0.65 ppm respectively as compared to the calculated precision and accuracy of approximately 0.36 and 0.2 ppm. The differences in accuracy between ocean and land suggests that the accuracy of XCO<sub>2</sub> data is likely related to interferences such as aerosols or surface albedo as they vary less over ocean than land. The accuracy as derived here is also likely a lower bound as it does not account for possible systematic biases between the regions used in this analysis.