---
title: 'Quantifying lower tropospheric methane concentrations using GOSAT near-IR and TES thermal IR measurements'
author: 'Worden, J. R. and Turner, A. J. and Bloom, A. and Kulawik, S. S. and Liu, J. and Lee, M. and Weidner, R. and Bowman, K. and Frankenberg, C. and Parker, R. and Payne, V. H.'
type: 'journal-article'
year: 2015
publication: 'Atmospheric Measurement Techniques'
doi: '10.5194/amt-8-3433-2015'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. Evaluating surface fluxes of CH<sub>4</sub> using total column data requires models to accurately account for the transport and chemistry of methane in the free troposphere and stratosphere, thus reducing sensitivity to the underlying fluxes. Vertical profiles of methane have increased sensitivity to surface fluxes because lower tropospheric methane is more sensitive to surface fluxes than a total column, and quantifying free-tropospheric CH<sub>4</sub> concentrations helps to evaluate the impact of transport and chemistry uncertainties on estimated surface fluxes. Here we demonstrate the potential for estimating lower tropospheric CH<sub>4</sub> concentrations through the combination of free-tropospheric methane measurements from the Aura Tropospheric Emission Spectrometer (TES) and XCH<sub>4</sub> (dry-mole air fraction of methane) from the Greenhouse gases Observing SATellite – Thermal And Near-infrared for carbon Observation (GOSAT TANSO, herein GOSAT for brevity). The calculated precision of these estimates ranges from 10 to 30 ppb for a monthly average on a 4° × 5° latitude/longitude grid making these data suitable for evaluating lower-tropospheric methane concentrations. Smoothing error is approximately 10 ppb or less. Comparisons between these data and the GEOS-Chem model demonstrate that these lower-tropospheric CH<sub>4</sub> estimates can resolve enhanced concentrations over flux regions that are challenging to resolve with total column measurements. We also use the GEOS-Chem model and surface measurements in background regions across a range of latitudes to determine that these lower-tropospheric estimates are biased low by approximately 65 ppb, with an accuracy of approximately 6 ppb (after removal of the bias) and an actual precision of approximately 30 ppb. This 6 ppb accuracy is consistent with the accuracy of TES and GOSAT methane retrievals.