---
title: 'El Niño, the 2006 Indonesian peat fires, and the distribution of atmospheric methane'
author: 'Worden, John and Jiang, Zhe and Jones, Dylan B. A. and Alvarado, Matthew and Bowman, Kevin and Frankenberg, Christian and Kort, Eric A. and Kulawik, Susan S. and Lee, Meemong and Liu, Junjie and Payne, Vivienne and Wecht, Kevin and Worden, Helen'
type: 'journal-article'
year: 2013
publication: 'Geophysical Research Letters'
doi: '10.1002/grl.50937'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Dry conditions from a moderate El Niño during the fall of 2006 resulted in enhanced burning in Indonesia with fire emissions of CO approximately 4–6 times larger than the prior year. Here we use new tropospheric methane and CO data from the Aura Tropospheric Emission Spectrometer and new CO profile measurements from the Terra Measurements of Pollution in the Troposphere (MOPITT) satellite instruments with the Goddard Earth Observing System (GEOS)‐Chem model to estimate methane emissions of 4.25 ± 0.75 Tg for October–November 2006 from these fires. Errors in convective parameterization in GEOS‐Chem, evaluated by comparing MOPITT and GEOS‐Chem CO profiles, are the primary uncertainty of the emissions estimate. The El Niño related Indonesian fires increased the tropical distribution of atmospheric methane relative to 2005, indicating that tropical biomass burning can compensate for expected decreases in tropical wetland methane emissions from reduced rainfall during El Niño as found in previous studies.