---
title: 'A method for evaluating bias in global measurements of CO
<sub>2</sub>
total columns from space'
author: 'Wunch, D. and Wennberg, P. O. and Toon, G. C. and Connor, B. J. and Fisher, B. and Osterman, G. B. and Frankenberg, C. and Mandrake, L. and O''Dell, C. and Ahonen, P. and Biraud, S. C. and Castano, R. and Cressie, N. and Crisp, D. and Deutscher, N. M. and Eldering, A. and Fisher, M. L. and Griffith, D. W. T. and Gunson, M. and Heikkinen, P. and Keppel-Aleks, G. and Kyrö, E. and Lindenmaier, R. and Macatangay, R. and Mendonca, J. and Messerschmidt, J. and Miller, C. E. and Morino, I. and Notholt, J. and Oyafuso, F. A. and Rettinger, M. and Robinson, J. and Roehl, C. M. and Salawitch, R. J. and Sherlock, V. and Strong, K. and Sussmann, R. and Tanaka, T. and Thompson, D. R. and Uchino, O. and Warneke, T. and Wofsy, S. C.'
type: 'journal-article'
year: 2011
publication: 'Atmospheric Chemistry and Physics'
doi: '10.5194/acp-11-12317-2011'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. We describe a method of evaluating systematic errors in measurements of total column dry-air mole fractions of CO<sub>2</sub> (XCO<sub>2</sub>) from space, and we illustrate the method by applying it to the v2.8 Atmospheric CO<sub>2</sub> Observations from Space retrievals of the Greenhouse Gases Observing Satellite (ACOS-GOSAT) measurements over land. The approach exploits the lack of large gradients in XCO<sub>2</sub> south of 25° S to identify large-scale offsets and other biases in the ACOS-GOSAT data with several retrieval parameters and errors in instrument calibration. We demonstrate the effectiveness of the method by comparing the ACOS-GOSAT data in the Northern Hemisphere with ground truth provided by the Total Carbon Column Observing Network (TCCON). We use the observed correlation between free-tropospheric potential temperature and XCO<sub>2</sub> in the Northern Hemisphere to define a dynamically informed coincidence criterion between the ground-based TCCON measurements and the ACOS-GOSAT measurements. We illustrate that this approach provides larger sample sizes, hence giving a more robust comparison than one that simply uses time, latitude and longitude criteria. Our results show that the agreement with the TCCON data improves after accounting for the systematic errors, but that extrapolation to conditions found outside the region south of 25° S may be problematic (e.g., high airmasses, large surface pressure biases, M-gain, measurements made over ocean). A preliminary evaluation of the improved v2.9 ACOS-GOSAT data is also discussed.