---
title: 'Investigating Diurnal and Seasonal Cycles of Vegetation Optical Depth Retrieved From GNSS Signals in a Broadleaf Forest'
author: 'Yao, Yitong and Humphrey, Vincent and Konings, Alexandra G. and Wang, Yujie and Yin, Yi and Holtzman, Nataniel and Wood, Jeffrey D. and Bar‐On, Yinon and Frankenberg, Christian'
type: 'journal-article'
year: 2024
publication: 'Geophysical Research Letters'
doi: '10.1029/2023gl107121'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract
Vegetation Optical Depth (VOD) has emerged as a valuable metric to quantify water stress on vegetation's carbon uptake from a remote sensing perspective. However, existing spaceborne microwave remote sensing platforms face limitations in capturing the diurnal VOD variations and global products lack site‐level validation against plant physiology. To address these challenges, we leveraged the Global Navigation Satellite System (GNSS) L‐band microwave signal, measuring its attenuation by the canopy of a temperate broadleaf forest using a pair of GNSS receivers. This approach allowed us to collect continuous VOD observations at a sub‐hourly scale. We found a significant seasonal‐scale correlation between VOD and leaf water potential. The VOD diurnal amplitude is affected by soil moisture, plant transpiration and leaf surface water. Additionally, VOD can help independently estimate plant transpiration. Our findings pave the way for a deeper understanding of response of the vegetation to water stress at finer temporal scales.