---
title: 'Unequal exposure to heatwaves in Los Angeles: Impact of uneven green spaces'
author: 'Yin, Yi and He, Liyin and Wennberg, Paul O. and Frankenberg, Christian'
type: 'journal-article'
year: 2023
publication: 'Science Advances'
doi: '10.1126/sciadv.ade8501'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Cities worldwide are experiencing record-breaking summer temperatures. Urban environments exacerbate extreme heat, resulting in not only the urban heat island but also intracity variations in heat exposure. Understanding these disparities is crucial to support equitable climate mitigation and adaptation efforts. We found persistent negative correlations between daytime land surface temperature (LST) and median household income across the Los Angeles metropolitan area based on Ecosystem Spaceborne Thermal Radiometer Experiment on Space Station observations from 2018 to 2021. Lower evapotranspiration resulting from the unequal distribution of vegetation cover is a major factor leading to higher LST in low-income neighborhoods. Disparities worsen with higher regional mean surface temperature, with a $10,000 decrease in income leading to ~0.2°C LST increase at 20°C and up to ~0.7°C at 45°C. With more frequent and intense heat waves projected in the future, equitable mitigation measures, such as increasing surface albedo and tree cover in low-income neighborhoods, are necessary to address these disparities.