---
title: 'Cropland Carbon Uptake Delayed and Reduced by 2019 Midwest Floods'
author: 'Yin, Yi and Byrne, Brendan and Liu, Junjie and Wennberg, Paul O. and Davis, Kenneth J. and Magney, Troy and Köhler, Philipp and He, Liyin and Jeyaram, Rupesh and Humphrey, Vincent and Gerken, Tobias and Feng, Sha and Digangi, Joshua P. and Frankenberg, Christian'
type: 'journal-article'
year: 2020
publication: 'AGU Advances'
doi: '10.1029/2019av000140'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

AbstractWhile large‐scale floods directly impact human lives and infrastructures, they also profoundly impact agricultural productivity. New satellite observations of vegetation activity and atmospheric CO<sub>2</sub> offer the opportunity to quantify the effects of such extreme events on cropland carbon sequestration. Widespread flooding during spring and early summer 2019 induced conditions that delayed crop planting across the U.S. Midwest. As a result, satellite observations of solar‐induced chlorophyll fluorescence from TROPOspheric Monitoring Instrument and Orbiting Carbon Observatory reveal a 16‐day shift in the seasonal cycle of photosynthesis relative to 2018, along with a 15% lower peak value. We estimate a reduction of 0.21 PgC in cropland gross primary productivity in June and July, partially compensated in August and September (+0.14 PgC). The extension of the 2019 growing season into late September is likely to have benefited from increased water availability and late‐season temperature. Ultimately, this change is predicted to reduce the crop productivity in the Midwest Corn/Soy belt by ~15% compared to 2018. Using an atmospheric transport model, we show that a decline of ~0.1 PgC in the net carbon uptake during June and July is consistent with observed CO<sub>2</sub> enhancements of up to 10 ppm in the midday boundary layer from Atmospheric Carbon and Transport‐America aircraft and over 3 ppm in column‐averaged dry‐air mole fractions from Orbiting Carbon Observatory. This study quantifies the impact of floods on cropland productivity and demonstrates the potential of combining solar‐induced chlorophyll fluorescence with atmospheric CO<sub>2</sub> observations to monitor regional carbon flux anomalies.