---
title: 'Accelerating methane growth rate from 2010 to 2017: leading contributions from the tropics and East Asia'
author: 'Yin, Yi and Chevallier, Frederic and Ciais, Philippe and Bousquet, Philippe and Saunois, Marielle and Zheng, Bo and Worden, John and Bloom, A. Anthony and Parker, Robert J. and Jacob, Daniel J. and Dlugokencky, Edward J. and Frankenberg, Christian'
type: 'journal-article'
year: 2021
publication: 'Atmospheric Chemistry and Physics'
doi: '10.5194/acp-21-12631-2021'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. After stagnating in the early 2000s, the atmospheric methane growth rate has been positive since 2007 with a significant acceleration starting in 2014. While the causes for previous growth rate variations are still not well determined, this recent increase can be studied with dense surface and satellite observations. Here, we use an ensemble of six multi-species atmospheric inversions that have the capacity to assimilate observations of the main species in the methane oxidation chain – namely, methane, formaldehyde, and carbon monoxide – to simultaneously optimize both the methane sources and sinks at each model grid. We show that the surge of the atmospheric growth rate between 2010–2013 and 2014–2017 is most likely explained by an increase of global CH<sub>4</sub> emissions by 17.5±1.5 Tg yr−1 (mean ± 1σ), while variations in the hydroxyl radicals (OH) remained small. The inferred emission increase is consistently supported by both surface and satellite observations, with leading contributions from the tropical wetlands (∼ 35 %) and anthropogenic emissions in China (∼ 20 %). Such a high consecutive atmospheric growth rate has not been observed since the 1980s and corresponds to unprecedented global total CH<sub>4</sub> emissions.