---
title: 'Fire decline in dry tropical ecosystems enhances decadal land carbon sink'
author: 'Yin, Yi and Bloom, A. Anthony and Worden, John and Saatchi, Sassan and Yang, Yan and Williams, Mathew and Liu, Junjie and Jiang, Zhe and Worden, Helen and Bowman, Kevin and Frankenberg, Christian and Schimel, David'
type: 'journal-article'
year: 2020
publication: 'Nature Communications'
doi: '10.1038/s41467-020-15852-2'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

AbstractThe terrestrial carbon sink has significantly increased in the past decades, but the underlying mechanisms are still unclear. The current synthesis of process-based estimates of land and ocean sinks requires an additional sink of 0.6 PgC yr−1 in the last decade to explain the observed airborne fraction. A concurrent global fire decline was observed in association with tropical agriculture expansion and landscape fragmentation. Here we show that a decline of 0.2 ± 0.1 PgC yr−1 in fire emissions during 2008–2014 relative to 2001–2007 also induced an additional carbon sink enhancement of 0.4 ± 0.2 PgC yr−1 attributable to carbon cycle feedbacks, amounting to a combined sink increase comparable to the 0.6 PgC yr−1 budget imbalance. Our results suggest that the indirect effects of fire, in addition to the direct emissions, is an overlooked mechanism for explaining decadal-scale changes in the land carbon sink and highlight the importance of fire management in climate mitigation.