---
title: 'Inferring drivers of tropical isoprene: competing  effects of emissions and chemistry'
author: 'Yoon, James Young Suk and Wells, Kelley C. and Millet, Dylan B. and Frankenberg, Christian and Sanghavi, Suniti and Swann, Abigail L. S. and Thornton, Joel A. and Turner, Alexander J.'
type: 'journal-article'
year: 2026
publication: 'Atmospheric Chemistry and Physics'
doi: '10.5194/acp-26-4509-2026'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract. Isoprene is the most significant non-methane hydrocarbon by total emissions and an important control on the tropospheric oxidative capacity. In the atmosphere, isoprene is oxidized by the hydroxyl radical (OH) on the order of hours depending on local OH concentrations. Using isoprene retrievals from the Cross-track infrared sounder (CrIS), we monitor global isoprene column variability and observe differing isoprene column responses to El Niño-Southern Oscillation across three tropical regions: Amazonia, the Maritime Continent, and equatorial Africa. We find correlations between isoprene column variability and temperature over Amazonia, which suggests that isoprene emissions drive Amazonian isoprene variability (“emissions-controlled”). In the Maritime Continent, we find strong correlations between isoprene columns, precipitation and soil moisture, as well as an anti-correlation between isoprene and formaldehyde retrievals. These correlations suggest that isoprene columns may be modulated by non-anthropogenic NOx emissions, namely soil and biomass burning NOx (“chemistry-controlled”), although convection and lightning NOx may also modulate isoprene column retrievals if the lofted isoprene flux is large enough. In equatorial Africa, both biomass burning and temperature can explain isoprene variability during different periods, representing an intermediate regime with contributions from emissions and chemistry. We suggest that these isoprene regimes are caused by differences in the dynamic temperature and oxidant range between the three regions, and we specifically highlight oil palm plantations in the Maritime Continent as an area of co-located isoprene and soil NOx fluxes. By leveraging CrIS isoprene retrievals, we can study interactions between VOC and NOx sources over tropical areas with few in-situ observations.