---
title: 'High‐Resolution Global Contiguous SIF of OCO‐2'
author: 'Yu, L. and Wen, J. and Chang, C. Y. and Frankenberg, C. and Sun, Y.'
type: 'journal-article'
year: 2019
publication: 'Geophysical Research Letters'
doi: '10.1029/2018gl081109'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

AbstractThe Orbiting Carbon Observatory‐2 (OCO‐2) collects solar‐induced chlorophyll fluorescence (SIF) at high spatial resolution along orbits (
oco2_orbit), but its discontinuous spatial coverage precludes its full potential for understanding the mechanistic SIF‐photosynthesis relationship. This study developed a spatially contiguous global OCO‐2 SIF product at 0.05° and 16‐day resolutions (
oco2_005) using machine learning constrained by physiological understandings. This was achieved by stratifying biomes and times for training and predictions, which accounts for varying plant physiological properties in space and time. 
oco2_005 accurately preserved the spatiotemporal variations of 
oco2_orbit across the globe. Validation of 
oco2_005 with Chlorophyll Fluorescence Imaging Spectrometer airborne measurements revealed striking consistency (R<sub>2</sub> = 0.72; regression slope = 0.96). Further, without time and biome stratification, (1) 
oco2_005 of croplands, deciduous temperate, and needleleaf forests would be underestimated during the peak season, (2) 
oco2_005 of needleleaf forests would be overestimated during autumn, and (3) the capability of 
oco2_005 to detect drought would be diminished.