---
title: 'Solar‐Induced Fluorescence Detects Interannual Variation in Gross Primary Production of Coniferous Forests in the Western United States'
author: 'Zuromski, Lauren M. and Bowling, David R. and Köhler, Philipp and Frankenberg, Christian and Goulden, Michael L. and Blanken, Peter D. and Lin, John C.'
type: 'journal-article'
year: 2018
publication: 'Geophysical Research Letters'
doi: '10.1029/2018gl077906'
materials: ''
supplement: ''
orcid_type: 'journal-article'
toc: false
---

## Abstract

Abstract
Quantifying gross primary production (GPP), the largest flux of the terrestrial carbon cycle, remains difficult at the landscape scale. Evergreen needleleaf (coniferous) forests in the western United States constitute an important carbon reservoir whose annual GPP varies from year‐to‐year due to drought, mortality, and other ecosystem disturbances. Evergreen forest productivity is challenging to determine via traditional remote sensing indices (i.e., NDVI and EVI), because detecting environmental stress conditions is difficult. We investigated the utility of solar‐induced chlorophyll fluorescence (SIF) to detect year‐to‐year variation in GPP in four coniferous forests varying in species composition in the western United States (Sierra Nevada, Cascade, and Rocky Mountains). We show that annually averaged, satellite‐based observations of SIF (retrieved from GOME‐2) were significantly correlated with annual GPP observed at eddy covariance towers over several years. Further, SIF responded quantitatively to drought‐induced mortality, suggesting that SIF may be capable of detecting ecosystem disturbance in coniferous forests.